In [15]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/RERUM")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [16]:
%time train_df = pd.read_csv(r"../dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"../dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"../dataset/Hillstrom/Men/val_men.csv")

CPU times: user 22.9 ms, sys: 10 ms, total: 32.9 ms
Wall time: 31.8 ms
CPU times: user 11.5 ms, sys: 5.02 ms, total: 16.5 ms
Wall time: 16.1 ms
CPU times: user 5.22 ms, sys: 0 ns, total: 5.22 ms
Wall time: 5.21 ms

In [17]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [18]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [19]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [20]:
epochs = 150
early_stop_metric = "ema_qini"
ema = True
ema_alpha = 0.25
patience = 20
early_stop_start = 30
print (f" epochs = {epochs}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 early stop = ema_qini
 use ema = True
 ema alpha = 0.25
 patience = 20
 early stop start = 30

In [21]:
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 100
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 1e-5, 1e-3, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True)
    grid_outcome_dropout = trial.suggest_float("outcome_dropout", 0.1, 0.5)
    grid_shared_dropout = trial.suggest_float("shared_dropout", 0.0, 0.4    )
    grid_shared_hidden = trial.suggest_categorical("shared_hidden", [128, 256, 384, 512])
    grid_outcome_hidden = trial.suggest_categorical("outcome_hidden", [64, 128, 256])
    grid_ziln_lambda = trial.suggest_float("ziln_lambda", 5, 50.0, log=True)
    grid_pos_weight = trial.suggest_float("pos_weight", 1.0, 20.0, log=True)

    val_auqc_list = []
    val_ate_err_list = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=grid_shared_hidden,
            outcome_hidden=grid_outcome_hidden,
            outcome_dropout=grid_outcome_dropout,
            shared_dropout=grid_shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            ziln_lambda=grid_ziln_lambda,
            pos_weight=grid_pos_weight
        )

        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_men_val_t_on_device = x_men_val_t.to(device)
        y0_pred, y1_pred = tarnet.predict(x_men_val_t_on_device)

        uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
        y_true = y_men_val_t.detach().cpu().numpy().flatten()
        t_true = t_men_val_t.detach().cpu().numpy().flatten()
        
        current_val_auqc = auqc(y_true, t_true, uplift_pred, bins=100, plot=False)
        ate_pred = uplift_pred.mean()
        ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
        current_val_ate_err = abs(ate_pred - ate_true)

        val_auqc_list.append(current_val_auqc)
        val_ate_err_list.append(current_val_ate_err)

    # Calculate aggregated metrics across the 5 validation seeds
    mean_auqc = float(np.mean(val_auqc_list))
    std_auqc = float(np.std(val_auqc_list))
    mean_ate_err = float(np.mean(val_ate_err_list))

    # Apply penalty for instability and miscalibration
    penalty_std = std_auqc * 0.5
    penalty_ate = mean_ate_err * 0.05

    final_score = mean_auqc - penalty_std - penalty_ate - penalty_std

    trial.set_user_attr("mean_val_auqc", mean_auqc)
    trial.set_user_attr("std_Val_auqc", std_auqc)
    trial.set_user_attr("mean_val_ate_err", mean_ate_err)
    trial.set_user_attr("final_score", final_score)
    return final_score

def print_trial_callback(study, trial):
    value = float(trial.value) if trial.value is not None else float("nan")
    best_trial = study.best_trial
    best_value = float(best_trial.value) if best_trial.value is not None else float("nan")
    print(
        f"Finished trial {trial.number}: val score: {value:.4f} - "
        f"with hyperparameters: {trial.params} | "
        f"best trial: {best_trial.number} score: {best_value:.4f}",
        flush=True
    )

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True, callbacks=[print_trial_callback])

trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": round(float(t.params["lr"]), 4),
        "weight_decay": round(float(t.params["weight_decay"]), 4),
        "shared_hidden": int(t.params["shared_hidden"]),
        "outcome_hidden": int(t.params["outcome_hidden"]),
        "shared_dropout": round(float(t.params["shared_dropout"]), 3),
        "outcome_dropout": round(float(t.params["outcome_dropout"]), 3),
        "ziln_lambda": round(float(t.params["ziln_lambda"]), 3),
        "pos_weight": round(float(t.params["pos_weight"]), 3),
        "mean_val_auqc": float(t.value),
        "std_Val_auqc": float(t.user_attrs.get("std_Val_auqc", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_val_auqc", ascending=True).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "shared_hidden": int(best_params["shared_hidden"]),
    "outcome_hidden": int(best_params["outcome_hidden"]),
    "shared_dropout": float(best_params["shared_dropout"]),
    "outcome_dropout": float(best_params["outcome_dropout"]),
    "ziln_lambda": float(best_params["ziln_lambda"]),
    "pos_weight": float(best_params["pos_weight"]),
    "mean_Val_auqc": float(study.best_value),
    "std_Val_auqc": float(study.best_trial.user_attrs.get("std_Val_auqc", np.nan))
})

  0%|          | 0/100 [00:00<?, ?it/s]

Finished trial 0: val score: 0.5050 - with hyperparameters: {'lr': 9.008296332262975e-05, 'weight_decay': 3.2543813547868006e-05, 'outcome_dropout': 0.26330970370677254, 'shared_dropout': 0.17735402643744136, 'shared_hidden': 512, 'outcome_hidden': 256, 'ziln_lambda': 10.235980761081278, 'pos_weight': 3.4889116308840054} | best trial: 0 score: 0.5050

Best trial: 0. Best value: 0.504956:   1%|          | 1/100 [01:18<2:09:31, 78.50s/it]

Finished trial 1: val score: 0.4617 - with hyperparameters: {'lr': 2.2049986176238194e-05, 'weight_decay': 7.293306303133679e-06, 'outcome_dropout': 0.3671615491304012, 'shared_dropout': 0.30697964005463274, 'shared_hidden': 128, 'outcome_hidden': 256, 'ziln_lambda': 29.735895976238673, 'pos_weight': 2.8747396589909275} | best trial: 0 score: 0.5050

Best trial: 0. Best value: 0.504956:   2%|▏         | 2/100 [03:10<2:40:07, 98.04s/it]

Finished trial 2: val score: 0.3277 - with hyperparameters: {'lr': 1.134555608987272e-05, 'weight_decay': 0.00071089078282492, 'outcome_dropout': 0.4131096387665075, 'shared_dropout': 0.076574980662182, 'shared_hidden': 128, 'outcome_hidden': 128, 'ziln_lambda': 16.0005578795518, 'pos_weight': 7.123602754976329} | best trial: 0 score: 0.5050

Best trial: 0. Best value: 0.504956:   3%|▎         | 3/100 [05:42<3:18:32, 122.81s/it]

Finished trial 3: val score: 0.5464 - with hyperparameters: {'lr': 2.4454926025162452e-05, 'weight_decay': 0.0010735213412582276, 'outcome_dropout': 0.22632945192822662, 'shared_dropout': 0.18648736221787213, 'shared_hidden': 128, 'outcome_hidden': 128, 'ziln_lambda': 8.653564492484831, 'pos_weight': 4.6805117162663095} | best trial: 3 score: 0.5464

Best trial: 3. Best value: 0.546363:   4%|▍         | 4/100 [07:40<3:13:45, 121.10s/it]

Finished trial 4: val score: 0.2023 - with hyperparameters: {'lr': 1.6368917725071812e-05, 'weight_decay': 1.0605829043483175e-05, 'outcome_dropout': 0.3479165728467064, 'shared_dropout': 0.13910947108087265, 'shared_hidden': 128, 'outcome_hidden': 64, 'ziln_lambda': 28.628887341123743, 'pos_weight': 13.89063283014309} | best trial: 3 score: 0.5464

Best trial: 3. Best value: 0.546363:   5%|▌         | 5/100 [10:00<3:22:31, 127.91s/it]

Finished trial 5: val score: 0.4939 - with hyperparameters: {'lr': 0.00014250539251029222, 'weight_decay': 4.399323157684873e-05, 'outcome_dropout': 0.4112925476171102, 'shared_dropout': 0.1094142783085165, 'shared_hidden': 128, 'outcome_hidden': 128, 'ziln_lambda': 30.390441228024866, 'pos_weight': 7.14037956255353} | best trial: 3 score: 0.5464

Best trial: 3. Best value: 0.546363:   6%|▌         | 6/100 [11:17<2:53:01, 110.44s/it]

Finished trial 6: val score: 0.3413 - with hyperparameters: {'lr': 0.0009990866502564775, 'weight_decay': 0.00011261231805771254, 'outcome_dropout': 0.14879368503318605, 'shared_dropout': 0.1248211900241119, 'shared_hidden': 384, 'outcome_hidden': 256, 'ziln_lambda': 13.548246830152832, 'pos_weight': 5.245656519564363} | best trial: 3 score: 0.5464

Best trial: 3. Best value: 0.546363:   7%|▋         | 7/100 [12:34<2:34:08, 99.44s/it]

Finished trial 7: val score: 0.4161 - with hyperparameters: {'lr': 0.00025296974370762513, 'weight_decay': 2.2121853219458705e-05, 'outcome_dropout': 0.3535315070716821, 'shared_dropout': 0.05810942783068005, 'shared_hidden': 128, 'outcome_hidden': 64, 'ziln_lambda': 14.193372516001604, 'pos_weight': 4.958250653585322} | best trial: 3 score: 0.5464

Best trial: 3. Best value: 0.546363:   8%|▊         | 8/100 [13:48<2:20:20, 91.53s/it]

Finished trial 8: val score: 0.5410 - with hyperparameters: {'lr': 1.2123796249075328e-05, 'weight_decay': 0.005439748475001624, 'outcome_dropout': 0.4045663277340735, 'shared_dropout': 0.0636555439421553, 'shared_hidden': 256, 'outcome_hidden': 64, 'ziln_lambda': 11.931361967019276, 'pos_weight': 8.646365709623298} | best trial: 3 score: 0.5464

Best trial: 3. Best value: 0.546363:   9%|▉         | 9/100 [16:02<2:38:37, 104.59s/it]

Finished trial 9: val score: 0.4586 - with hyperparameters: {'lr': 0.0007878422776391468, 'weight_decay': 5.9446992496636186e-05, 'outcome_dropout': 0.2699639795839518, 'shared_dropout': 0.20723613872025518, 'shared_hidden': 512, 'outcome_hidden': 256, 'ziln_lambda': 15.910793788975504, 'pos_weight': 2.078759026578569} | best trial: 3 score: 0.5464

Best trial: 3. Best value: 0.546363:  10%|█         | 10/100 [17:17<2:23:06, 95.40s/it]

Finished trial 10: val score: 0.5851 - with hyperparameters: {'lr': 4.2366023635300504e-05, 'weight_decay': 0.009980143580923594, 'outcome_dropout': 0.15821942727288918, 'shared_dropout': 0.3988169894338867, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 5.238115829140946, 'pos_weight': 1.188379842713556} | best trial: 10 score: 0.5851

Best trial: 10. Best value: 0.585141:  11%|█         | 11/100 [18:31<2:12:01, 89.01s/it]

Finished trial 11: val score: 0.5848 - with hyperparameters: {'lr': 4.357895992238864e-05, 'weight_decay': 0.008255218449199632, 'outcome_dropout': 0.13888266797942037, 'shared_dropout': 0.37964744567547637, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 5.100394945681761, 'pos_weight': 1.003983252265178} | best trial: 10 score: 0.5851

Best trial: 10. Best value: 0.585141:  12%|█▏        | 12/100 [19:44<2:03:29, 84.20s/it]

Finished trial 12: val score: 0.5944 - with hyperparameters: {'lr': 4.3772377326071444e-05, 'weight_decay': 0.00668999668154443, 'outcome_dropout': 0.13785128072892697, 'shared_dropout': 0.39643030941912827, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 5.4596498571397625, 'pos_weight': 1.0009139888493837} | best trial: 12 score: 0.5944

Best trial: 12. Best value: 0.594375:  13%|█▎        | 13/100 [20:57<1:57:11, 80.82s/it]

Finished trial 13: val score: 0.5950 - with hyperparameters: {'lr': 4.4990969139654556e-05, 'weight_decay': 1.1912912375338296e-06, 'outcome_dropout': 0.10402897423476959, 'shared_dropout': 0.39737192041735475, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 5.104020278175405, 'pos_weight': 1.0683642131413829} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  14%|█▍        | 14/100 [22:10<1:52:28, 78.47s/it]

Finished trial 14: val score: 0.5725 - with hyperparameters: {'lr': 5.887824315478104e-05, 'weight_decay': 1.3643755509190505e-06, 'outcome_dropout': 0.19377632515379445, 'shared_dropout': 0.30956014952520344, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 7.245225897018141, 'pos_weight': 1.6489011213529787} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  15%|█▌        | 15/100 [23:23<1:48:54, 76.87s/it]

Finished trial 15: val score: 0.4726 - with hyperparameters: {'lr': 0.00020421588258586035, 'weight_decay': 1.6763390255124038e-06, 'outcome_dropout': 0.10396041739941056, 'shared_dropout': 0.33264558867577915, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 48.54811801925459, 'pos_weight': 1.5696434390870715} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  16%|█▌        | 16/100 [24:37<1:46:06, 75.80s/it]

Finished trial 16: val score: 0.5670 - with hyperparameters: {'lr': 3.126262068178552e-05, 'weight_decay': 0.0002495051018534156, 'outcome_dropout': 0.20469793757383037, 'shared_dropout': 0.2532488912395039, 'shared_hidden': 256, 'outcome_hidden': 128, 'ziln_lambda': 6.878161594335821, 'pos_weight': 2.2952361110842574} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  17%|█▋        | 17/100 [26:06<1:50:37, 79.97s/it]

Finished trial 17: val score: 0.4088 - with hyperparameters: {'lr': 7.710200359427955e-05, 'weight_decay': 0.001122943876712852, 'outcome_dropout': 0.1068103042702909, 'shared_dropout': 0.005558394074240469, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 6.280308986509581, 'pos_weight': 1.3525912065584416} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  18%|█▊        | 18/100 [27:23<1:47:52, 78.93s/it]

Finished trial 18: val score: 0.4826 - with hyperparameters: {'lr': 0.00035112391277070587, 'weight_decay': 4.187122297271153e-06, 'outcome_dropout': 0.48341249117246493, 'shared_dropout': 0.35456505436547014, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 8.880399605197354, 'pos_weight': 17.642331888272494} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  19%|█▉        | 19/100 [28:36<1:44:15, 77.23s/it]

Finished trial 19: val score: 0.4953 - with hyperparameters: {'lr': 0.00010777712811235026, 'weight_decay': 0.002510988435677233, 'outcome_dropout': 0.17769821471073594, 'shared_dropout': 0.2547464938417015, 'shared_hidden': 384, 'outcome_hidden': 64, 'ziln_lambda': 20.359201437544403, 'pos_weight': 2.110860648675616} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  20%|██        | 20/100 [29:50<1:41:30, 76.14s/it]

Finished trial 20: val score: 0.3738 - with hyperparameters: {'lr': 5.881723838453847e-05, 'weight_decay': 0.00021450012904720788, 'outcome_dropout': 0.24167219289881953, 'shared_dropout': 0.26784876698790633, 'shared_hidden': 512, 'outcome_hidden': 128, 'ziln_lambda': 6.150087701146802, 'pos_weight': 1.004890802968087} | best trial: 13 score: 0.5950

Best trial: 13. Best value: 0.594984:  21%|██        | 21/100 [31:04<1:39:25, 75.51s/it]

Finished trial 21: val score: 0.5958 - with hyperparameters: {'lr': 3.9430227951251144e-05, 'weight_decay': 0.003191533997343456, 'outcome_dropout': 0.1509032125061239, 'shared_dropout': 0.3891575960210555, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 5.020462617936189, 'pos_weight': 1.2375220689972812} | best trial: 21 score: 0.5958

Best trial: 21. Best value: 0.595814:  22%|██▏       | 22/100 [32:17<1:37:17, 74.84s/it]

Finished trial 22: val score: 0.5909 - with hyperparameters: {'lr': 3.4438804294937805e-05, 'weight_decay': 0.002961444738299521, 'outcome_dropout': 0.12399691330473991, 'shared_dropout': 0.3614349627256254, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 5.274459826975594, 'pos_weight': 1.5191842618200067} | best trial: 21 score: 0.5958

Best trial: 21. Best value: 0.595814:  23%|██▎       | 23/100 [33:33<1:36:21, 75.08s/it]

Finished trial 23: val score: 0.5822 - with hyperparameters: {'lr': 6.163185472489417e-05, 'weight_decay': 0.002656494696578087, 'outcome_dropout': 0.164556663743382, 'shared_dropout': 0.3964049587090849, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 8.784210517670017, 'pos_weight': 1.2740528298118297} | best trial: 21 score: 0.5958

Best trial: 21. Best value: 0.595814:  24%|██▍       | 24/100 [34:46<1:34:22, 74.51s/it]

Finished trial 24: val score: 0.5627 - with hyperparameters: {'lr': 1.9467175801116132e-05, 'weight_decay': 0.0005981439941096743, 'outcome_dropout': 0.29960818167835435, 'shared_dropout': 0.3314548746824102, 'shared_hidden': 256, 'outcome_hidden': 128, 'ziln_lambda': 7.454710433089012, 'pos_weight': 1.8073577119274165} | best trial: 21 score: 0.5958

Best trial: 21. Best value: 0.595814:  25%|██▌       | 25/100 [36:57<1:54:19, 91.46s/it]

Finished trial 25: val score: 0.5847 - with hyperparameters: {'lr': 3.5617680706455756e-05, 'weight_decay': 0.0003100514115297763, 'outcome_dropout': 0.20913482067476485, 'shared_dropout': 0.288271138924153, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 6.12197143940498, 'pos_weight': 2.834257436507427} | best trial: 21 score: 0.5958

Best trial: 21. Best value: 0.595814:  26%|██▌       | 26/100 [38:12<1:46:33, 86.40s/it]

Finished trial 26: val score: 0.5949 - with hyperparameters: {'lr': 2.7647110037248605e-05, 'weight_decay': 0.004910003896898628, 'outcome_dropout': 0.12824806060046606, 'shared_dropout': 0.36027827935764073, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 5.089254537974553, 'pos_weight': 1.288193945831092} | best trial: 21 score: 0.5958

Best trial: 21. Best value: 0.595814:  27%|██▋       | 27/100 [39:28<1:41:21, 83.31s/it]

Finished trial 27: val score: 0.5965 - with hyperparameters: {'lr': 1.57359267965606e-05, 'weight_decay': 3.084560169591885e-06, 'outcome_dropout': 0.11028347044816877, 'shared_dropout': 0.34348656134580313, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 7.836926867806968, 'pos_weight': 3.2263177987787746} | best trial: 27 score: 0.5965

Best trial: 27. Best value: 0.596463:  28%|██▊       | 28/100 [40:53<1:40:32, 83.78s/it]

Finished trial 28: val score: 0.4794 - with hyperparameters: {'lr': 1.0053519342611747e-05, 'weight_decay': 2.494241377092949e-06, 'outcome_dropout': 0.10032275833767675, 'shared_dropout': 0.33311302655772257, 'shared_hidden': 384, 'outcome_hidden': 64, 'ziln_lambda': 7.938259761519057, 'pos_weight': 2.623906425157032} | best trial: 27 score: 0.5965

Best trial: 27. Best value: 0.596463:  29%|██▉       | 29/100 [43:23<2:02:39, 103.65s/it]

Finished trial 29: val score: 0.5603 - with hyperparameters: {'lr': 1.4578839803745229e-05, 'weight_decay': 1.7018455928060414e-05, 'outcome_dropout': 0.26218693176201, 'shared_dropout': 0.22680365454883822, 'shared_hidden': 512, 'outcome_hidden': 256, 'ziln_lambda': 10.537222917550945, 'pos_weight': 2.866701114576598} | best trial: 27 score: 0.5965

Best trial: 27. Best value: 0.596463:  30%|███       | 30/100 [45:02<1:59:22, 102.32s/it]

Finished trial 30: val score: 0.4871 - with hyperparameters: {'lr': 0.00011019752509918824, 'weight_decay': 3.7019097029227737e-06, 'outcome_dropout': 0.18919647998609157, 'shared_dropout': 0.3670727053644752, 'shared_hidden': 512, 'outcome_hidden': 256, 'ziln_lambda': 10.251315180672856, 'pos_weight': 3.6063169130022583} | best trial: 27 score: 0.5965

Best trial: 27. Best value: 0.596463:  31%|███       | 31/100 [46:17<1:48:13, 94.11s/it]

Finished trial 31: val score: 0.5966 - with hyperparameters: {'lr': 2.58688074134942e-05, 'weight_decay': 1.0002707354555866e-06, 'outcome_dropout': 0.12718656597343378, 'shared_dropout': 0.3543667223096523, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 6.215520964547509, 'pos_weight': 3.734516612155282} | best trial: 31 score: 0.5966

Best trial: 31. Best value: 0.596558:  32%|███▏      | 32/100 [47:34<1:40:50, 88.98s/it]

Finished trial 32: val score: 0.5890 - with hyperparameters: {'lr': 1.972747307612064e-05, 'weight_decay': 1.1553648010195195e-06, 'outcome_dropout': 0.16659414261955904, 'shared_dropout': 0.3039117353055369, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 6.208598446024967, 'pos_weight': 3.7067547750841214} | best trial: 31 score: 0.5966

Best trial: 31. Best value: 0.596558:  33%|███▎      | 33/100 [48:54<1:36:21, 86.29s/it]

Finished trial 33: val score: 0.5872 - with hyperparameters: {'lr': 2.0552821433731808e-05, 'weight_decay': 6.122035413813759e-06, 'outcome_dropout': 0.12154645739005393, 'shared_dropout': 0.3386626191309757, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 6.747475839904863, 'pos_weight': 5.851946547745404} | best trial: 31 score: 0.5966

Best trial: 31. Best value: 0.596558:  34%|███▍      | 34/100 [50:14<1:33:01, 84.57s/it]

Finished trial 34: val score: 0.6029 - with hyperparameters: {'lr': 1.4792776445117685e-05, 'weight_decay': 1.0018472601656955e-06, 'outcome_dropout': 0.14779076739699773, 'shared_dropout': 0.3073217618745751, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 8.27420295481496, 'pos_weight': 3.85350037953808} | best trial: 34 score: 0.6029

Best trial: 34. Best value: 0.602885:  35%|███▌      | 35/100 [51:31<1:29:09, 82.30s/it]

Finished trial 35: val score: 0.5398 - with hyperparameters: {'lr': 1.5247649333869134e-05, 'weight_decay': 2.2614686017165244e-06, 'outcome_dropout': 0.23539159803204077, 'shared_dropout': 0.2857423188779711, 'shared_hidden': 256, 'outcome_hidden': 128, 'ziln_lambda': 8.221047459452606, 'pos_weight': 3.9680604262595125} | best trial: 34 score: 0.6029

Best trial: 34. Best value: 0.602885:  36%|███▌      | 36/100 [53:43<1:43:39, 97.19s/it]

Finished trial 36: val score: 0.5982 - with hyperparameters: {'lr': 2.495557149887684e-05, 'weight_decay': 7.751455826000395e-06, 'outcome_dropout': 0.15632815117403703, 'shared_dropout': 0.31145186805059605, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 11.414378513332602, 'pos_weight': 10.167913850360675} | best trial: 34 score: 0.6029

Best trial: 34. Best value: 0.602885:  37%|███▋      | 37/100 [54:57<1:34:31, 90.02s/it]

Finished trial 37: val score: 0.4172 - with hyperparameters: {'lr': 2.4160024568564467e-05, 'weight_decay': 1.088102813941378e-05, 'outcome_dropout': 0.17807774040963045, 'shared_dropout': 0.16804767138993212, 'shared_hidden': 128, 'outcome_hidden': 256, 'ziln_lambda': 11.38627534590663, 'pos_weight': 10.057050023720386} | best trial: 34 score: 0.6029

Best trial: 34. Best value: 0.602885:  38%|███▊      | 38/100 [56:41<1:37:34, 94.43s/it]

Finished trial 38: val score: 0.6091 - with hyperparameters: {'lr': 1.2412013984801367e-05, 'weight_decay': 4.249974095401842e-06, 'outcome_dropout': 0.21500130678618473, 'shared_dropout': 0.3020977037378795, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 19.20593972969663, 'pos_weight': 6.2165821863394815} | best trial: 38 score: 0.6091

Best trial: 38. Best value: 0.609125:  39%|███▉      | 39/100 [58:00<1:31:11, 89.69s/it]

Finished trial 39: val score: 0.1977 - with hyperparameters: {'lr': 1.2296415437142812e-05, 'weight_decay': 6.876259073494569e-06, 'outcome_dropout': 0.21527997966314766, 'shared_dropout': 0.22642957627056332, 'shared_hidden': 128, 'outcome_hidden': 64, 'ziln_lambda': 22.395899025675163, 'pos_weight': 6.40962094252616} | best trial: 38 score: 0.6091

Best trial: 38. Best value: 0.609125:  40%|████      | 40/100 [1:00:22<1:45:29, 105.49s/it]

Finished trial 40: val score: 0.6045 - with hyperparameters: {'lr': 2.5096764062175425e-05, 'weight_decay': 1.0866690169126938e-05, 'outcome_dropout': 0.30905083042183557, 'shared_dropout': 0.31230745301944846, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 18.516088107812106, 'pos_weight': 10.98469036512195} | best trial: 38 score: 0.6091

Best trial: 38. Best value: 0.609125:  41%|████      | 41/100 [1:01:35<1:34:07, 95.73s/it]

Finished trial 41: val score: 0.6090 - with hyperparameters: {'lr': 1.8463997409713082e-05, 'weight_decay': 1.186847856299273e-05, 'outcome_dropout': 0.2676374715323687, 'shared_dropout': 0.31697204350155783, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 19.061463517541146, 'pos_weight': 11.680944118509347} | best trial: 38 score: 0.6091

Best trial: 38. Best value: 0.609125:  42%|████▏     | 42/100 [1:02:50<1:26:27, 89.43s/it]

Finished trial 42: val score: 0.6084 - with hyperparameters: {'lr': 1.3360943462198925e-05, 'weight_decay': 2.2842543298638885e-05, 'outcome_dropout': 0.3158784977706588, 'shared_dropout': 0.3080989541276297, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 19.647038353656423, 'pos_weight': 12.018654890391563} | best trial: 38 score: 0.6091

Best trial: 38. Best value: 0.609125:  43%|████▎     | 43/100 [1:04:13<1:23:01, 87.40s/it]

Finished trial 43: val score: 0.6117 - with hyperparameters: {'lr': 1.2502262338832115e-05, 'weight_decay': 3.8021786959721707e-05, 'outcome_dropout': 0.3160428227233147, 'shared_dropout': 0.279103978236204, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 18.580122979891797, 'pos_weight': 14.532152328608426} | best trial: 43 score: 0.6117

Best trial: 43. Best value: 0.611689:  44%|████▍     | 44/100 [1:05:34<1:19:56, 85.65s/it]

Finished trial 44: val score: 0.6128 - with hyperparameters: {'lr': 1.025004509046397e-05, 'weight_decay': 3.151150907965055e-05, 'outcome_dropout': 0.31933259345192777, 'shared_dropout': 0.27529181101161543, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 18.78495026312251, 'pos_weight': 13.402656233702768} | best trial: 44 score: 0.6128

Best trial: 44. Best value: 0.612823:  45%|████▌     | 45/100 [1:07:00<1:18:29, 85.62s/it]

Finished trial 45: val score: 0.6134 - with hyperparameters: {'lr': 1.0099729706388255e-05, 'weight_decay': 3.190277915458555e-05, 'outcome_dropout': 0.30312630398734647, 'shared_dropout': 0.277748022053283, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 25.880224413690996, 'pos_weight': 14.086695293020169} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  46%|████▌     | 46/100 [1:08:25<1:16:58, 85.53s/it]

Finished trial 46: val score: 0.4778 - with hyperparameters: {'lr': 1.007131135297011e-05, 'weight_decay': 6.185982462765585e-05, 'outcome_dropout': 0.33320566074020186, 'shared_dropout': 0.27404511310000934, 'shared_hidden': 256, 'outcome_hidden': 256, 'ziln_lambda': 25.329163563734625, 'pos_weight': 19.770948053896976} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  47%|████▋     | 47/100 [1:10:28<1:25:26, 96.73s/it]

Finished trial 47: val score: 0.1961 - with hyperparameters: {'lr': 1.7770574577640943e-05, 'weight_decay': 3.949527255620856e-05, 'outcome_dropout': 0.38746691359406427, 'shared_dropout': 0.2368482592757759, 'shared_hidden': 128, 'outcome_hidden': 64, 'ziln_lambda': 31.900855767003794, 'pos_weight': 14.721053864306125} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  48%|████▊     | 48/100 [1:12:43<1:33:56, 108.39s/it]

Finished trial 48: val score: 0.6124 - with hyperparameters: {'lr': 1.1234558460096961e-05, 'weight_decay': 0.00013069847253890864, 'outcome_dropout': 0.28144790308119305, 'shared_dropout': 0.2850133841580191, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 17.267254247291493, 'pos_weight': 14.171384585348914} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  49%|████▉     | 49/100 [1:14:07<1:25:44, 100.87s/it]

Finished trial 49: val score: 0.4354 - with hyperparameters: {'lr': 1.12092288775555e-05, 'weight_decay': 0.00011073822540694958, 'outcome_dropout': 0.368574423572693, 'shared_dropout': 0.19895437859541337, 'shared_hidden': 512, 'outcome_hidden': 128, 'ziln_lambda': 14.309049965765771, 'pos_weight': 8.132583859269179} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  50%|█████     | 50/100 [1:16:43<1:37:56, 117.54s/it]

Finished trial 50: val score: 0.6065 - with hyperparameters: {'lr': 1.1801123362682399e-05, 'weight_decay': 8.474680026160934e-05, 'outcome_dropout': 0.2895391342694757, 'shared_dropout': 0.16183528329380156, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 16.951475156266163, 'pos_weight': 14.26918758852155} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  51%|█████     | 51/100 [1:17:56<1:25:06, 104.22s/it]

Finished trial 51: val score: 0.6110 - with hyperparameters: {'lr': 1.2922343641930878e-05, 'weight_decay': 1.5888952588845543e-05, 'outcome_dropout': 0.27637647361555856, 'shared_dropout': 0.25210290602519025, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 23.85046502223986, 'pos_weight': 16.533751183646007} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  52%|█████▏    | 52/100 [1:19:14<1:17:00, 96.26s/it]

Finished trial 52: val score: 0.6018 - with hyperparameters: {'lr': 1.329514519424478e-05, 'weight_decay': 2.5373318373287737e-05, 'outcome_dropout': 0.3278013918839552, 'shared_dropout': 0.24193454683612803, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 26.118811222598314, 'pos_weight': 16.415669062445115} | best trial: 45 score: 0.6134

Best trial: 45. Best value: 0.613441:  53%|█████▎    | 53/100 [1:20:35<1:11:41, 91.51s/it]

Finished trial 53: val score: 0.6150 - with hyperparameters: {'lr': 1.0099409836193258e-05, 'weight_decay': 0.00017089996027425702, 'outcome_dropout': 0.2880654388429349, 'shared_dropout': 0.2804489378826317, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 22.57570480038999, 'pos_weight': 15.724854107667813} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  54%|█████▍    | 54/100 [1:21:59<1:08:29, 89.33s/it]

Finished trial 54: val score: 0.4365 - with hyperparameters: {'lr': 0.00046673689902155543, 'weight_decay': 0.000167771814148276, 'outcome_dropout': 0.2897027537420815, 'shared_dropout': 0.263846482148455, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 22.96703171279813, 'pos_weight': 12.773348988717824} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  55%|█████▌    | 55/100 [1:23:12<1:03:23, 84.52s/it]

Finished trial 55: val score: 0.6121 - with hyperparameters: {'lr': 1.1133898912292136e-05, 'weight_decay': 6.496451754022007e-05, 'outcome_dropout': 0.2564349464621816, 'shared_dropout': 0.2886761840148231, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 33.546977098809045, 'pos_weight': 16.169593350262403} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  56%|█████▌    | 56/100 [1:24:32<1:01:00, 83.20s/it]

Finished trial 56: val score: 0.6137 - with hyperparameters: {'lr': 1.0000567223131755e-05, 'weight_decay': 5.820973961224166e-05, 'outcome_dropout': 0.2489119083155791, 'shared_dropout': 0.2779032146632534, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 36.9752517182121, 'pos_weight': 19.514490166249992} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  57%|█████▋    | 57/100 [1:25:55<59:32, 83.09s/it]

Finished trial 57: val score: 0.6088 - with hyperparameters: {'lr': 1.0152860573635035e-05, 'weight_decay': 5.8673098149994065e-05, 'outcome_dropout': 0.2440533138391176, 'shared_dropout': 0.2110099860524825, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 34.67539574023377, 'pos_weight': 19.527183153665284} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  58%|█████▊    | 58/100 [1:27:14<57:17, 81.84s/it]

Finished trial 58: val score: 0.6072 - with hyperparameters: {'lr': 1.6455703121673563e-05, 'weight_decay': 0.00015349954540214844, 'outcome_dropout': 0.25218386928959613, 'shared_dropout': 0.28747043479850687, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 37.220007001322685, 'pos_weight': 17.283761624139988} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  59%|█████▉    | 59/100 [1:28:28<54:23, 79.60s/it]

Finished trial 59: val score: 0.3766 - with hyperparameters: {'lr': 1.079321967525183e-05, 'weight_decay': 0.0004148594590484224, 'outcome_dropout': 0.3401262209833657, 'shared_dropout': 0.2586910789074933, 'shared_hidden': 256, 'outcome_hidden': 64, 'ziln_lambda': 45.963835837941645, 'pos_weight': 8.70786568544296} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  60%|██████    | 60/100 [1:30:50<1:05:29, 98.25s/it]

Finished trial 60: val score: 0.6114 - with hyperparameters: {'lr': 1.6689044131765685e-05, 'weight_decay': 7.425440841442996e-05, 'outcome_dropout': 0.36355962791864743, 'shared_dropout': 0.2959968832513, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 41.467092011242656, 'pos_weight': 13.070236178886132} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  61%|██████    | 61/100 [1:32:10<1:00:14, 92.69s/it]

Finished trial 61: val score: 0.6136 - with hyperparameters: {'lr': 1.3776683556029696e-05, 'weight_decay': 3.167856043825977e-05, 'outcome_dropout': 0.2836600477804736, 'shared_dropout': 0.27575526019013796, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 27.090978630758425, 'pos_weight': 15.349923953139475} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  62%|██████▏   | 62/100 [1:33:28<55:53, 88.25s/it]

Finished trial 62: val score: 0.6144 - with hyperparameters: {'lr': 1.0069899911606366e-05, 'weight_decay': 2.9926530447808526e-05, 'outcome_dropout': 0.2794238754105739, 'shared_dropout': 0.27501367319005465, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 28.06189745626696, 'pos_weight': 16.104021731268343} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  63%|██████▎   | 63/100 [1:34:52<53:44, 87.14s/it]

Finished trial 63: val score: 0.6079 - with hyperparameters: {'lr': 1.4473534436191933e-05, 'weight_decay': 4.86243401055676e-05, 'outcome_dropout': 0.2826957604917721, 'shared_dropout': 0.241728935192997, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 28.342483914993622, 'pos_weight': 18.239021871728795} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  64%|██████▍   | 64/100 [1:36:08<50:13, 83.70s/it]

Finished trial 64: val score: 0.6088 - with hyperparameters: {'lr': 1.721304139619367e-05, 'weight_decay': 2.808950232816795e-05, 'outcome_dropout': 0.30405631686973533, 'shared_dropout': 0.26807068130126865, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 21.15857969434055, 'pos_weight': 15.18252761655825} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  65%|██████▌   | 65/100 [1:37:21<46:57, 80.49s/it]

Finished trial 65: val score: 0.4446 - with hyperparameters: {'lr': 0.00018063570320935973, 'weight_decay': 0.0001227554632530137, 'outcome_dropout': 0.2277460276762081, 'shared_dropout': 0.3232078358511929, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 27.93759528184312, 'pos_weight': 13.343934928384812} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  66%|██████▌   | 66/100 [1:38:37<44:53, 79.21s/it]

Finished trial 66: val score: 0.5419 - with hyperparameters: {'lr': 1.4306040637957937e-05, 'weight_decay': 1.6916523042253164e-05, 'outcome_dropout': 0.29288188314417074, 'shared_dropout': 0.21435671283248223, 'shared_hidden': 512, 'outcome_hidden': 256, 'ziln_lambda': 30.08477743298095, 'pos_weight': 18.69714754633207} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  67%|██████▋   | 67/100 [1:40:16<46:52, 85.22s/it]

Finished trial 67: val score: 0.6079 - with hyperparameters: {'lr': 2.2257837059515205e-05, 'weight_decay': 3.33398551075982e-05, 'outcome_dropout': 0.27391251155504315, 'shared_dropout': 0.2745099974162453, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 17.007116515392887, 'pos_weight': 10.06133080966054} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  68%|██████▊   | 68/100 [1:41:29<43:31, 81.60s/it]

Finished trial 68: val score: 0.3269 - with hyperparameters: {'lr': 1.0883511388302233e-05, 'weight_decay': 5.074413178874923e-05, 'outcome_dropout': 0.45177209429982657, 'shared_dropout': 0.18992391505909223, 'shared_hidden': 128, 'outcome_hidden': 128, 'ziln_lambda': 14.733654800984674, 'pos_weight': 15.548901800820525} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  69%|██████▉   | 69/100 [1:44:17<55:31, 107.47s/it]

Finished trial 69: val score: 0.6092 - with hyperparameters: {'lr': 1.0306459516002492e-05, 'weight_decay': 8.573050490124234e-05, 'outcome_dropout': 0.318487671873915, 'shared_dropout': 0.22505431736299789, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 25.304624407023834, 'pos_weight': 11.657042091991231} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  70%|███████   | 70/100 [1:45:40<50:04, 100.14s/it]

Finished trial 70: val score: 0.6094 - with hyperparameters: {'lr': 1.3673612812155646e-05, 'weight_decay': 0.0002627730510044415, 'outcome_dropout': 0.3473348170512883, 'shared_dropout': 0.25251569359936904, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 38.94046477257516, 'pos_weight': 13.681317238414179} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  71%|███████   | 71/100 [1:47:00<45:30, 94.14s/it]

Finished trial 71: val score: 0.6132 - with hyperparameters: {'lr': 1.1798434120184799e-05, 'weight_decay': 0.00015086790901070897, 'outcome_dropout': 0.2620300699209177, 'shared_dropout': 0.29351973708851564, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 31.52930258885685, 'pos_weight': 16.242266321588318} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  72%|███████▏  | 72/100 [1:48:21<41:58, 89.94s/it]

Finished trial 72: val score: 0.6097 - with hyperparameters: {'lr': 1.1975277414150367e-05, 'weight_decay': 0.00017332092853181226, 'outcome_dropout': 0.2585146209371476, 'shared_dropout': 0.3259271319787349, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 21.61860361385671, 'pos_weight': 17.563038020777554} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  73%|███████▎  | 73/100 [1:49:44<39:35, 87.98s/it]

Finished trial 73: val score: 0.6064 - with hyperparameters: {'lr': 2.0704809995999988e-05, 'weight_decay': 0.0003810883066518845, 'outcome_dropout': 0.3003585797478474, 'shared_dropout': 0.2956351334607031, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 26.79243065728461, 'pos_weight': 15.684332370846723} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  74%|███████▍  | 74/100 [1:50:57<36:13, 83.61s/it]

Finished trial 74: val score: 0.5945 - with hyperparameters: {'lr': 1.577323108009734e-05, 'weight_decay': 0.0001221690676064367, 'outcome_dropout': 0.2794178181427517, 'shared_dropout': 0.10371927173871943, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 31.60363709956368, 'pos_weight': 9.08239969879815} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  75%|███████▌  | 75/100 [1:52:10<33:30, 80.40s/it]

Finished trial 75: val score: 0.6110 - with hyperparameters: {'lr': 1.009477888994996e-05, 'weight_decay': 3.2566163039991155e-05, 'outcome_dropout': 0.2464266989024873, 'shared_dropout': 0.27368454907398176, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 23.88802857423277, 'pos_weight': 12.928727096684469} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  76%|███████▌  | 76/100 [1:53:32<32:20, 80.87s/it]

Finished trial 76: val score: 0.6107 - with hyperparameters: {'lr': 1.1483763271088518e-05, 'weight_decay': 4.473031536072187e-05, 'outcome_dropout': 0.22800177314065648, 'shared_dropout': 0.29578818237808396, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 35.83372688753231, 'pos_weight': 18.308634956342377} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  77%|███████▋  | 77/100 [1:54:51<30:47, 80.32s/it]

Finished trial 77: val score: 0.4644 - with hyperparameters: {'lr': 1.3693728592876751e-05, 'weight_decay': 2.0618215331062403e-05, 'outcome_dropout': 0.26744881487872074, 'shared_dropout': 0.28245711875919055, 'shared_hidden': 384, 'outcome_hidden': 64, 'ziln_lambda': 17.359205498663258, 'pos_weight': 10.957276222433201} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  78%|███████▊  | 78/100 [1:57:32<38:18, 104.50s/it]

Finished trial 78: val score: 0.4687 - with hyperparameters: {'lr': 1.818435249896521e-05, 'weight_decay': 0.001248910995814506, 'outcome_dropout': 0.2861716433737464, 'shared_dropout': 0.006763499918743421, 'shared_hidden': 256, 'outcome_hidden': 128, 'ziln_lambda': 13.270910523999085, 'pos_weight': 19.945895680452452} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  79%|███████▉  | 79/100 [1:59:20<36:57, 105.61s/it]

Finished trial 79: val score: 0.5541 - with hyperparameters: {'lr': 5.0933670774336325e-05, 'weight_decay': 9.572385554581463e-05, 'outcome_dropout': 0.29815293512967855, 'shared_dropout': 0.3435887673314772, 'shared_hidden': 384, 'outcome_hidden': 256, 'ziln_lambda': 29.672947816948778, 'pos_weight': 12.27286569483489} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  80%|████████  | 80/100 [2:00:47<33:20, 100.01s/it]

Finished trial 80: val score: 0.4264 - with hyperparameters: {'lr': 2.213394946503205e-05, 'weight_decay': 0.0005784700589100905, 'outcome_dropout': 0.3299163383282172, 'shared_dropout': 0.23787436726513092, 'shared_hidden': 512, 'outcome_hidden': 128, 'ziln_lambda': 15.357490948394581, 'pos_weight': 14.014495341085818} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  81%|████████  | 81/100 [2:02:47<33:29, 105.76s/it]

Finished trial 81: val score: 0.6117 - with hyperparameters: {'lr': 1.1498790788656917e-05, 'weight_decay': 6.506249043886176e-05, 'outcome_dropout': 0.25328700707570584, 'shared_dropout': 0.28922381854112156, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 33.49784335964641, 'pos_weight': 16.767705522837094} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  82%|████████▏ | 82/100 [2:04:07<29:28, 98.25s/it]

Finished trial 82: val score: 0.6117 - with hyperparameters: {'lr': 1.2162739602122257e-05, 'weight_decay': 0.0002060744552094938, 'outcome_dropout': 0.2594610007241894, 'shared_dropout': 0.2547305993064235, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 42.55054091317446, 'pos_weight': 15.72372925115246} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  83%|████████▎ | 83/100 [2:05:25<26:06, 92.17s/it]

Finished trial 83: val score: 0.6003 - with hyperparameters: {'lr': 2.9710084561390664e-05, 'weight_decay': 7.262203574842445e-05, 'outcome_dropout': 0.30835613352005037, 'shared_dropout': 0.26544758768820464, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 32.45611771587352, 'pos_weight': 16.376411034374122} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  84%|████████▍ | 84/100 [2:06:39<23:04, 86.53s/it]

Finished trial 84: val score: 0.6083 - with hyperparameters: {'lr': 1.561253477052812e-05, 'weight_decay': 0.00013759275350975225, 'outcome_dropout': 0.23465624404463675, 'shared_dropout': 0.30004716933073605, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 20.42335855793914, 'pos_weight': 14.779877240867451} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  85%|████████▌ | 85/100 [2:07:55<20:51, 83.41s/it]

Finished trial 85: val score: 0.6106 - with hyperparameters: {'lr': 1.0020271102185006e-05, 'weight_decay': 1.4600997906370988e-05, 'outcome_dropout': 0.3235897989111612, 'shared_dropout': 0.3217795920722815, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 24.05993085240359, 'pos_weight': 10.88644960065999} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  86%|████████▌ | 86/100 [2:09:26<19:58, 85.62s/it]

Finished trial 86: val score: 0.5835 - with hyperparameters: {'lr': 7.673360874825924e-05, 'weight_decay': 3.0286528156245353e-05, 'outcome_dropout': 0.2705723288823898, 'shared_dropout': 0.28167416833409414, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 27.22388154969966, 'pos_weight': 18.09964625428302} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  87%|████████▋ | 87/100 [2:10:39<17:44, 81.89s/it]

Finished trial 87: val score: 0.3322 - with hyperparameters: {'lr': 1.314571885049059e-05, 'weight_decay': 2.2182732959293938e-05, 'outcome_dropout': 0.2794588953453148, 'shared_dropout': 0.2614979447127678, 'shared_hidden': 128, 'outcome_hidden': 128, 'ziln_lambda': 29.97651168518188, 'pos_weight': 14.260168688166488} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  88%|████████▊ | 88/100 [2:13:09<20:27, 102.27s/it]

Finished trial 88: val score: 0.6080 - with hyperparameters: {'lr': 1.150278740549147e-05, 'weight_decay': 9.748373645394542e-05, 'outcome_dropout': 0.23696532022110206, 'shared_dropout': 0.24432301306170853, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 36.80220716703346, 'pos_weight': 7.845573399000251} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  89%|████████▉ | 89/100 [2:14:27<17:27, 95.23s/it]

Finished trial 89: val score: 0.6127 - with hyperparameters: {'lr': 1.5017899119631435e-05, 'weight_decay': 5.02435712835136e-05, 'outcome_dropout': 0.31036682822054634, 'shared_dropout': 0.2908940010418355, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 39.30744019699564, 'pos_weight': 16.13215659846213} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  90%|█████████ | 90/100 [2:15:45<14:59, 89.99s/it]

Finished trial 90: val score: 0.4756 - with hyperparameters: {'lr': 1.8978096664316193e-05, 'weight_decay': 3.7991153305278346e-05, 'outcome_dropout': 0.3411623789407977, 'shared_dropout': 0.31515090199030216, 'shared_hidden': 384, 'outcome_hidden': 64, 'ziln_lambda': 42.754073381134326, 'pos_weight': 12.301476212106584} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  91%|█████████ | 91/100 [2:17:58<15:24, 102.71s/it]

Finished trial 91: val score: 0.6092 - with hyperparameters: {'lr': 1.4703461390868013e-05, 'weight_decay': 4.9477721679221436e-05, 'outcome_dropout': 0.3097018779248052, 'shared_dropout': 0.2880137011707325, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 38.98775262811981, 'pos_weight': 16.93646998205514} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  92%|█████████▏| 92/100 [2:19:16<12:44, 95.56s/it]

Finished trial 92: val score: 0.6126 - with hyperparameters: {'lr': 1.1137821020318502e-05, 'weight_decay': 5.9379601601576066e-05, 'outcome_dropout': 0.29264596178344804, 'shared_dropout': 0.2739516945038334, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 34.439708733772754, 'pos_weight': 4.46380363580579} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  93%|█████████▎| 93/100 [2:20:39<10:41, 91.61s/it]

Finished trial 93: val score: 0.6110 - with hyperparameters: {'lr': 1.2697267585732056e-05, 'weight_decay': 0.00020494835396360405, 'outcome_dropout': 0.29414710319369547, 'shared_dropout': 0.27237845878618516, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 38.598729931258724, 'pos_weight': 5.441348052244907} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  94%|█████████▍| 94/100 [2:21:59<08:48, 88.03s/it]

Finished trial 94: val score: 0.6065 - with hyperparameters: {'lr': 1.6403972471844837e-05, 'weight_decay': 1.969796400007284e-05, 'outcome_dropout': 0.31596288222084334, 'shared_dropout': 0.24789012551424847, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 25.149871839605527, 'pos_weight': 4.482060173938505} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  95%|█████████▌| 95/100 [2:23:13<07:00, 84.08s/it]

Finished trial 95: val score: 0.6088 - with hyperparameters: {'lr': 1.3768589717603457e-05, 'weight_decay': 5.558222933847052e-05, 'outcome_dropout': 0.2673763294500231, 'shared_dropout': 0.30487880937469386, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 47.11495247981648, 'pos_weight': 13.623866474021145} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  96%|█████████▌| 96/100 [2:24:35<05:33, 83.28s/it]

Finished trial 96: val score: 0.6139 - with hyperparameters: {'lr': 1.106674558926274e-05, 'weight_decay': 3.897316727635781e-05, 'outcome_dropout': 0.2872270832228997, 'shared_dropout': 0.2770933564515767, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 28.564566128380815, 'pos_weight': 4.959908247524567} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  97%|█████████▋| 97/100 [2:25:57<04:09, 83.02s/it]

Finished trial 97: val score: 0.4619 - with hyperparameters: {'lr': 0.0005298294871100667, 'weight_decay': 2.675634196893982e-05, 'outcome_dropout': 0.35494591267008385, 'shared_dropout': 0.2631216670822469, 'shared_hidden': 256, 'outcome_hidden': 128, 'ziln_lambda': 28.97998342324641, 'pos_weight': 4.149252196941403} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  98%|█████████▊| 98/100 [2:27:10<02:39, 79.83s/it]

Finished trial 98: val score: 0.5180 - with hyperparameters: {'lr': 1.2426861008552955e-05, 'weight_decay': 3.932587071008923e-05, 'outcome_dropout': 0.3025639802028496, 'shared_dropout': 0.22824452660378744, 'shared_hidden': 384, 'outcome_hidden': 256, 'ziln_lambda': 34.198815498584935, 'pos_weight': 5.179233580889123} | best trial: 53 score: 0.6150

Best trial: 53. Best value: 0.615044:  99%|█████████▉| 99/100 [2:28:59<01:28, 88.80s/it]

Finished trial 99: val score: 0.6151 - with hyperparameters: {'lr': 1.0854831006299919e-05, 'weight_decay': 8.908710439814211e-06, 'outcome_dropout': 0.3234603151576131, 'shared_dropout': 0.27800315821960286, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 31.34196044665029, 'pos_weight': 4.577124939815833} | best trial: 99 score: 0.6151

Best trial: 99. Best value: 0.615147: 100%|██████████| 100/100 [2:30:22<00:00, 90.23s/it]

In [22]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_Loss: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 99
Best mean_Val_Loss: 0.615147
Best params: {'lr': 1.0854831006299919e-05, 'weight_decay': 8.908710439814211e-06, 'outcome_dropout': 0.3234603151576131, 'shared_dropout': 0.27800315821960286, 'shared_hidden': 384, 'outcome_hidden': 128, 'ziln_lambda': 31.34196044665029, 'pos_weight': 4.577124939815833}

Best config table:

,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,ziln_lambda,pos_weight,mean_Val_auqc,std_Val_auqc
0,0.000011,0.000009,384.0,128.0,0.278003,0.32346,31.34196,4.577125,0.615147,0.051226

Top 10 trials:

,trial,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,ziln_lambda,pos_weight,mean_val_auqc,std_Val_auqc
0,47,0.0000,0.0000,128,64,0.237,0.387,31.901,14.721,0.196116,0.161331
1,39,0.0000,0.0000,128,64,0.226,0.215,22.396,6.410,0.197725,0.159989
2,4,0.0000,0.0000,128,64,0.139,0.348,28.629,13.891,0.202258,0.162450
3,68,0.0000,0.0001,128,128,0.190,0.452,14.734,15.549,0.326926,0.200931
4,2,0.0000,0.0007,128,128,0.077,0.413,16.001,7.124,0.327702,0.196000
5,87,0.0000,0.0000,128,128,0.261,0.279,29.977,14.260,0.332192,0.202858
6,6,0.0010,0.0001,384,256,0.125,0.149,13.548,5.246,0.341273,0.018150
7,20,0.0001,0.0002,512,128,0.268,0.242,6.150,1.005,0.373825,0.033948
8,59,0.0000,0.0004,256,64,0.259,0.340,45.964,8.708,0.376646,0.158061
9,17,0.0001,0.0011,384,128,0.006,0.107,6.280,1.353,0.408835,0.069173

In [23]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_shared_hidden = int(best_cfg['shared_hidden'])
best_outcome_hidden = int(best_cfg['outcome_hidden'])
best_shared_dropout = float(best_cfg['shared_dropout'])
best_outcome_dropout = float(best_cfg['outcome_dropout'])
best_ziln_lambda = float(best_cfg['ziln_lambda'])
best_pos_weight = float(best_cfg['pos_weight'])

print("Evaluating on test with best validation config:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"  shared_hidden={best_shared_hidden}, outcome_hidden={best_outcome_hidden}")
print(f"  shared_dropout={best_shared_dropout:.3f}, outcome_dropout={best_outcome_dropout:.3f}")
print(f"Number of seeds: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=best_shared_hidden,
        outcome_hidden=best_outcome_hidden,
        outcome_dropout=best_outcome_dropout,
        shared_dropout=best_shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
        ziln_lambda=best_ziln_lambda,
        pos_weight=best_pos_weight
    )

    tarnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'PER-SEED DETAILS (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'TEST SUMMARY (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Evaluating on test with best validation config:
  lr=1.1e-05, weight_decay=8.9e-06
  shared_hidden=384, outcome_hidden=128
  shared_dropout=0.278, outcome_dropout=0.323
Number of seeds: 5
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Loss: 258.1118 | Cls: 2.3972 | Reg: 8.1589 | mu_t: 4.3789 | sigma_t: 0.7450 | mu_c: 4.3590 | sigma_c: 0.7277 | Val Loss: 9.2694 | F1_c: 0.0000 | PR_AUC_c: 0.0105 | F1_t: 0.0000 | PR_AUC_t: 0.0121 | Val Qini: 0.6895 | EMA Qini: 0.6895 | Best EMA: 0.6895 ⭐ NEW BEST EMA
Epoch 2/150 | Loss: 273.0853 | Cls: 2.3973 | Reg: 8.6366 | mu_t: 4.3790 | sigma_t: 0.7456 | mu_c: 4.3593 | sigma_c: 0.7282 | Val Loss: 9.2687 | F1_c: 0.0000 | PR_AUC_c: 0.0107 | F1_t: 0.0000 | PR_AUC_t: 0.0120 | Val Qini: 0.6979 | EMA Qini: 0.6916 | Best EMA: 0.6916 ⭐ NEW BEST EMA
Epoch 3/150 | Loss: 247.0017 | Cls: 2.3967 | Reg: 7.8044 | mu_t: 4.3794 | sigma_t: 0.7461 | mu_c: 4.3597 | sigma_c: 0.7278 | Val Loss: 9.2681 | F1_c: 0.0000 | PR_AUC_c: 0.0108 | F1_t: 0.0000 | PR_AUC_t: 0.0120 | Val Qini: 0.7030 | EMA Qini: 0.6944 | Best EMA: 0.6944 ⭐ NEW BEST EMA
Epoch 4/150 | Loss: 285.1187 | Cls: 2.3972 | Reg: 9.0205 | mu_t: 4.3791 | sigma_t: 0.7465 | mu_c: 4.3602 | sigma_c: 0.7281 | Val Loss: 9.2675 | F1_c: 0.0000 | PR_AUC_c: 0.0107 | F1_t: 0.0000 | PR_AUC_t: 0.0123 | Val Qini: 0.7067 | EMA Qini: 0.6975 | Best EMA: 0.6975 ⭐ NEW BEST EMA
Epoch 5/150 | Loss: 301.9498 | Cls: 2.3969 | Reg: 9.5576 | mu_t: 4.3789 | sigma_t: 0.7467 | mu_c: 4.3597 | sigma_c: 0.7281 | Val Loss: 9.2668 | F1_c: 0.0000 | PR_AUC_c: 0.0107 | F1_t: 0.0000 | PR_AUC_t: 0.0124 | Val Qini: 0.7145 | EMA Qini: 0.7017 | Best EMA: 0.7017 ⭐ NEW BEST EMA
Epoch 6/150 | Loss: 254.4126 | Cls: 2.3975 | Reg: 8.0408 | mu_t: 4.3783 | sigma_t: 0.7474 | mu_c: 4.3596 | sigma_c: 0.7283 | Val Loss: 9.2663 | F1_c: 0.0000 | PR_AUC_c: 0.0106 | F1_t: 0.0000 | PR_AUC_t: 0.0125 | Val Qini: 0.7170 | EMA Qini: 0.7056 | Best EMA: 0.7056 ⭐ NEW BEST EMA
Epoch 7/150 | Loss: 277.3190 | Cls: 2.3962 | Reg: 8.7717 | mu_t: 4.3782 | sigma_t: 0.7478 | mu_c: 4.3600 | sigma_c: 0.7282 | Val Loss: 9.2657 | F1_c: 0.0000 | PR_AUC_c: 0.0106 | F1_t: 0.0000 | PR_AUC_t: 0.0125 | Val Qini: 0.7258 | EMA Qini: 0.7106 | Best EMA: 0.7106 ⭐ NEW BEST EMA
Epoch 8/150 | Loss: 283.7383 | Cls: 2.3967 | Reg: 8.9765 | mu_t: 4.3779 | sigma_t: 0.7479 | mu_c: 4.3601 | sigma_c: 0.7285 | Val Loss: 9.2652 | F1_c: 0.0000 | PR_AUC_c: 0.0106 | F1_t: 0.0000 | PR_AUC_t: 0.0125 | Val Qini: 0.7300 | EMA Qini: 0.7154 | Best EMA: 0.7154 ⭐ NEW BEST EMA
Epoch 9/150 | Loss: 286.2200 | Cls: 2.3950 | Reg: 9.0558 | mu_t: 4.3782 | sigma_t: 0.7487 | mu_c: 4.3600 | sigma_c: 0.7287 | Val Loss: 9.2645 | F1_c: 0.0000 | PR_AUC_c: 0.0107 | F1_t: 0.0000 | PR_AUC_t: 0.0125 | Val Qini: 0.7318 | EMA Qini: 0.7195 | Best EMA: 0.7195 ⭐ NEW BEST EMA
Epoch 10/150 | Loss: 283.8456 | Cls: 2.3952 | Reg: 8.9800 | mu_t: 4.3782 | sigma_t: 0.7492 | mu_c: 4.3602 | sigma_c: 0.7287 | Val Loss: 9.2640 | F1_c: 0.0000 | PR_AUC_c: 0.0108 | F1_t: 0.0000 | PR_AUC_t: 0.0126 | Val Qini: 0.7350 | EMA Qini: 0.7234 | Best EMA: 0.7234 ⭐ NEW BEST EMA
Epoch 11/150 | Loss: 250.2840 | Cls: 2.3942 | Reg: 7.9092 | mu_t: 4.3785 | sigma_t: 0.7495 | mu_c: 4.3603 | sigma_c: 0.7286 | Val Loss: 9.2634 | F1_c: 0.0000 | PR_AUC_c: 0.0107 | F1_t: 0.0000 | PR_AUC_t: 0.0125 | Val Qini: 0.7411 | EMA Qini: 0.7278 | Best EMA: 0.7278 ⭐ NEW BEST EMA
Epoch 12/150 | Loss: 309.7068 | Cls: 2.3948 | Reg: 9.8051 | mu_t: 4.3776 | sigma_t: 0.7501 | mu_c: 4.3604 | sigma_c: 0.7291 | Val Loss: 9.2628 | F1_c: 0.0000 | PR_AUC_c: 0.0109 | F1_t: 0.0000 | PR_AUC_t: 0.0126 | Val Qini: 0.7416 | EMA Qini: 0.7313 | Best EMA: 0.7313 ⭐ NEW BEST EMA
Epoch 13/150 | Loss: 292.9493 | Cls: 2.3944 | Reg: 9.2705 | mu_t: 4.3778 | sigma_t: 0.7506 | mu_c: 4.3600 | sigma_c: 0.7290 | Val Loss: 9.2623 | F1_c: 0.0000 | PR_AUC_c: 0.0109 | F1_t: 0.0000 | PR_AUC_t: 0.0127 | Val Qini: 0.7467 | EMA Qini: 0.7351 | Best EMA: 0.7351 ⭐ NEW BEST EMA
Epoch 14/150 | Loss: 255.5590 | Cls: 2.3945 | Reg: 8.0775 | mu_t: 4.3778 | sigma_t: 0.7514 | mu_c: 4.3600 | sigma_c: 0.7289 | Val Loss: 9.2618 | F1_c: 0.0000 | PR_AUC_c: 0.0109 | F1_t: 0.0000 | PR_AUC_t: 0.0127 | Val Qini: 0.7473 | EMA Qini: 0.7382 | Best EMA: 0.7382 ⭐ NEW BEST EMA
Epoch 15/150 | Loss: 268.4310 | Cls: 2.3958 | Reg: 8.4881 | mu_t: 4.3777 | sigma_t: 0.7515 | mu_c: 4.3605 | sigma_c: 0.7291 | Val Loss: 9.2613 | F1_c: 0.0000 | PR_AUC_c: 0.0109 | F1_t: 0.0000 | PR_AUC_t: 0.0128 | Val Qini: 0.7540 | EMA Qini: 0.7421 | Best EMA: 0.7421 ⭐ NEW BEST EMA
Epoch 16/150 | Loss: 295.4407 | Cls: 2.3948 | Reg: 9.3500 | mu_t: 4.3771 | sigma_t: 0.7521 | mu_c: 4.3607 | sigma_c: 0.7291 | Val Loss: 9.2608 | F1_c: 0.0000 | PR_AUC_c: 0.0108 | F1_t: 0.0000 | PR_AUC_t: 0.0129 | Val Qini: 0.7551 | EMA Qini: 0.7454 | Best EMA: 0.7454 ⭐ NEW BEST EMA
Epoch 17/150 | Loss: 309.2174 | Cls: 2.3952 | Reg: 9.7895 | mu_t: 4.3777 | sigma_t: 0.7524 | mu_c: 4.3613 | sigma_c: 0.7297 | Val Loss: 9.2603 | F1_c: 0.0000 | PR_AUC_c: 0.0109 | F1_t: 0.0000 | PR_AUC_t: 0.0130 | Val Qini: 0.7602 | EMA Qini: 0.7491 | Best EMA: 0.7491 ⭐ NEW BEST EMA
Epoch 18/150 | Loss: 266.2639 | Cls: 2.3940 | Reg: 8.4191 | mu_t: 4.3775 | sigma_t: 0.7531 | mu_c: 4.3605 | sigma_c: 0.7300 | Val Loss: 9.2598 | F1_c: 0.0000 | PR_AUC_c: 0.0110 | F1_t: 0.0000 | PR_AUC_t: 0.0132 | Val Qini: 0.7651 | EMA Qini: 0.7531 | Best EMA: 0.7531 ⭐ NEW BEST EMA
Epoch 19/150 | Loss: 265.2553 | Cls: 2.3924 | Reg: 8.3869 | mu_t: 4.3781 | sigma_t: 0.7531 | mu_c: 4.3607 | sigma_c: 0.7300 | Val Loss: 9.2593 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0134 | Val Qini: 0.7696 | EMA Qini: 0.7572 | Best EMA: 0.7572 ⭐ NEW BEST EMA
Epoch 20/150 | Loss: 288.4682 | Cls: 2.3947 | Reg: 9.1275 | mu_t: 4.3773 | sigma_t: 0.7537 | mu_c: 4.3605 | sigma_c: 0.7300 | Val Loss: 9.2588 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0135 | Val Qini: 0.7744 | EMA Qini: 0.7615 | Best EMA: 0.7615 ⭐ NEW BEST EMA
Epoch 21/150 | Loss: 297.2316 | Cls: 2.3927 | Reg: 9.4072 | mu_t: 4.3778 | sigma_t: 0.7540 | mu_c: 4.3610 | sigma_c: 0.7299 | Val Loss: 9.2583 | F1_c: 0.0000 | PR_AUC_c: 0.0114 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7824 | EMA Qini: 0.7667 | Best EMA: 0.7667 ⭐ NEW BEST EMA
Epoch 22/150 | Loss: 256.9957 | Cls: 2.3906 | Reg: 8.1235 | mu_t: 4.3779 | sigma_t: 0.7544 | mu_c: 4.3607 | sigma_c: 0.7302 | Val Loss: 9.2578 | F1_c: 0.0000 | PR_AUC_c: 0.0114 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7878 | EMA Qini: 0.7720 | Best EMA: 0.7720 ⭐ NEW BEST EMA
Epoch 23/150 | Loss: 287.5275 | Cls: 2.3913 | Reg: 9.0976 | mu_t: 4.3777 | sigma_t: 0.7546 | mu_c: 4.3604 | sigma_c: 0.7302 | Val Loss: 9.2573 | F1_c: 0.0000 | PR_AUC_c: 0.0114 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7813 | EMA Qini: 0.7743 | Best EMA: 0.7743 ⭐ NEW BEST EMA
Epoch 24/150 | Loss: 247.6440 | Cls: 2.3905 | Reg: 7.8251 | mu_t: 4.3779 | sigma_t: 0.7557 | mu_c: 4.3606 | sigma_c: 0.7301 | Val Loss: 9.2568 | F1_c: 0.0000 | PR_AUC_c: 0.0113 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7842 | EMA Qini: 0.7768 | Best EMA: 0.7768 ⭐ NEW BEST EMA
Epoch 25/150 | Loss: 323.8127 | Cls: 2.3932 | Reg: 10.2552 | mu_t: 4.3776 | sigma_t: 0.7558 | mu_c: 4.3611 | sigma_c: 0.7302 | Val Loss: 9.2563 | F1_c: 0.0000 | PR_AUC_c: 0.0114 | F1_t: 0.0000 | PR_AUC_t: 0.0137 | Val Qini: 0.7874 | EMA Qini: 0.7794 | Best EMA: 0.7794 ⭐ NEW BEST EMA
Epoch 26/150 | Loss: 276.8026 | Cls: 2.3931 | Reg: 8.7553 | mu_t: 4.3775 | sigma_t: 0.7566 | mu_c: 4.3609 | sigma_c: 0.7304 | Val Loss: 9.2558 | F1_c: 0.0000 | PR_AUC_c: 0.0114 | F1_t: 0.0000 | PR_AUC_t: 0.0138 | Val Qini: 0.7878 | EMA Qini: 0.7815 | Best EMA: 0.7815 ⭐ NEW BEST EMA
Epoch 27/150 | Loss: 280.1714 | Cls: 2.3922 | Reg: 8.8629 | mu_t: 4.3781 | sigma_t: 0.7565 | mu_c: 4.3609 | sigma_c: 0.7306 | Val Loss: 9.2554 | F1_c: 0.0000 | PR_AUC_c: 0.0114 | F1_t: 0.0000 | PR_AUC_t: 0.0138 | Val Qini: 0.7853 | EMA Qini: 0.7825 | Best EMA: 0.7825 ⭐ NEW BEST EMA
Epoch 28/150 | Loss: 266.1212 | Cls: 2.3913 | Reg: 8.4146 | mu_t: 4.3782 | sigma_t: 0.7569 | mu_c: 4.3612 | sigma_c: 0.7312 | Val Loss: 9.2550 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0138 | Val Qini: 0.7880 | EMA Qini: 0.7839 | Best EMA: 0.7839 ⭐ NEW BEST EMA
Epoch 29/150 | Loss: 303.5137 | Cls: 2.3905 | Reg: 9.6077 | mu_t: 4.3778 | sigma_t: 0.7571 | mu_c: 4.3611 | sigma_c: 0.7312 | Val Loss: 9.2545 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0138 | Val Qini: 0.7883 | EMA Qini: 0.7850 | Best EMA: 0.7850 ⭐ NEW BEST EMA
Epoch 30/150 | Loss: 298.7020 | Cls: 2.3917 | Reg: 9.4541 | mu_t: 4.3778 | sigma_t: 0.7575 | mu_c: 4.3613 | sigma_c: 0.7310 | Val Loss: 9.2540 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0138 | Val Qini: 0.7829 | EMA Qini: 0.7844 | Best EMA: 0.7850 (patience: 0/20)
Epoch 31/150 | Loss: 280.9021 | Cls: 2.3894 | Reg: 8.8863 | mu_t: 4.3776 | sigma_t: 0.7580 | mu_c: 4.3616 | sigma_c: 0.7315 | Val Loss: 9.2535 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0137 | Val Qini: 0.7847 | EMA Qini: 0.7845 | Best EMA: 0.7850 (patience: 1/20)
Epoch 32/150 | Loss: 272.7623 | Cls: 2.3920 | Reg: 8.6265 | mu_t: 4.3773 | sigma_t: 0.7584 | mu_c: 4.3619 | sigma_c: 0.7314 | Val Loss: 9.2530 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0137 | Val Qini: 0.7911 | EMA Qini: 0.7862 | Best EMA: 0.7862 ⭐ NEW BEST EMA
Epoch 33/150 | Loss: 262.9236 | Cls: 2.3897 | Reg: 8.3126 | mu_t: 4.3775 | sigma_t: 0.7589 | mu_c: 4.3621 | sigma_c: 0.7313 | Val Loss: 9.2524 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0137 | Val Qini: 0.7900 | EMA Qini: 0.7871 | Best EMA: 0.7871 ⭐ NEW BEST EMA
Epoch 34/150 | Loss: 311.0540 | Cls: 2.3913 | Reg: 9.8482 | mu_t: 4.3773 | sigma_t: 0.7594 | mu_c: 4.3619 | sigma_c: 0.7313 | Val Loss: 9.2518 | F1_c: 0.0000 | PR_AUC_c: 0.0113 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7918 | EMA Qini: 0.7883 | Best EMA: 0.7883 ⭐ NEW BEST EMA
Epoch 35/150 | Loss: 290.7268 | Cls: 2.3879 | Reg: 9.1998 | mu_t: 4.3765 | sigma_t: 0.7599 | mu_c: 4.3617 | sigma_c: 0.7317 | Val Loss: 9.2511 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7919 | EMA Qini: 0.7892 | Best EMA: 0.7892 ⭐ NEW BEST EMA
Epoch 36/150 | Loss: 295.7402 | Cls: 2.3899 | Reg: 9.3597 | mu_t: 4.3767 | sigma_t: 0.7603 | mu_c: 4.3611 | sigma_c: 0.7321 | Val Loss: 9.2505 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7886 | EMA Qini: 0.7891 | Best EMA: 0.7892 (patience: 1/20)
Epoch 37/150 | Loss: 265.4261 | Cls: 2.3867 | Reg: 8.3926 | mu_t: 4.3769 | sigma_t: 0.7607 | mu_c: 4.3618 | sigma_c: 0.7317 | Val Loss: 9.2500 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0136 | Val Qini: 0.7867 | EMA Qini: 0.7885 | Best EMA: 0.7892 (patience: 2/20)
Epoch 38/150 | Loss: 278.5447 | Cls: 2.3884 | Reg: 8.8111 | mu_t: 4.3762 | sigma_t: 0.7609 | mu_c: 4.3620 | sigma_c: 0.7322 | Val Loss: 9.2494 | F1_c: 0.0000 | PR_AUC_c: 0.0110 | F1_t: 0.0000 | PR_AUC_t: 0.0134 | Val Qini: 0.7831 | EMA Qini: 0.7871 | Best EMA: 0.7892 (patience: 3/20)
Epoch 39/150 | Loss: 286.3914 | Cls: 2.3898 | Reg: 9.0614 | mu_t: 4.3765 | sigma_t: 0.7611 | mu_c: 4.3615 | sigma_c: 0.7325 | Val Loss: 9.2489 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0135 | Val Qini: 0.7779 | EMA Qini: 0.7848 | Best EMA: 0.7892 (patience: 4/20)
Epoch 40/150 | Loss: 288.1687 | Cls: 2.3875 | Reg: 9.1182 | mu_t: 4.3757 | sigma_t: 0.7623 | mu_c: 4.3619 | sigma_c: 0.7325 | Val Loss: 9.2484 | F1_c: 0.0000 | PR_AUC_c: 0.0113 | F1_t: 0.0000 | PR_AUC_t: 0.0134 | Val Qini: 0.7784 | EMA Qini: 0.7832 | Best EMA: 0.7892 (patience: 5/20)
Epoch 41/150 | Loss: 284.6936 | Cls: 2.3881 | Reg: 9.0073 | mu_t: 4.3763 | sigma_t: 0.7627 | mu_c: 4.3618 | sigma_c: 0.7323 | Val Loss: 9.2479 | F1_c: 0.0000 | PR_AUC_c: 0.0113 | F1_t: 0.0000 | PR_AUC_t: 0.0134 | Val Qini: 0.7757 | EMA Qini: 0.7813 | Best EMA: 0.7892 (patience: 6/20)
Epoch 42/150 | Loss: 304.2390 | Cls: 2.3887 | Reg: 9.6309 | mu_t: 4.3763 | sigma_t: 0.7630 | mu_c: 4.3618 | sigma_c: 0.7324 | Val Loss: 9.2474 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0134 | Val Qini: 0.7729 | EMA Qini: 0.7792 | Best EMA: 0.7892 (patience: 7/20)
Epoch 43/150 | Loss: 278.6205 | Cls: 2.3870 | Reg: 8.8135 | mu_t: 4.3766 | sigma_t: 0.7637 | mu_c: 4.3622 | sigma_c: 0.7328 | Val Loss: 9.2469 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0132 | Val Qini: 0.7755 | EMA Qini: 0.7783 | Best EMA: 0.7892 (patience: 8/20)
Epoch 44/150 | Loss: 261.1926 | Cls: 2.3852 | Reg: 8.2575 | mu_t: 4.3763 | sigma_t: 0.7640 | mu_c: 4.3623 | sigma_c: 0.7327 | Val Loss: 9.2464 | F1_c: 0.0000 | PR_AUC_c: 0.0110 | F1_t: 0.0000 | PR_AUC_t: 0.0130 | Val Qini: 0.7728 | EMA Qini: 0.7769 | Best EMA: 0.7892 (patience: 9/20)
Epoch 45/150 | Loss: 307.9975 | Cls: 2.3863 | Reg: 9.7509 | mu_t: 4.3766 | sigma_t: 0.7639 | mu_c: 4.3627 | sigma_c: 0.7330 | Val Loss: 9.2458 | F1_c: 0.0000 | PR_AUC_c: 0.0110 | F1_t: 0.0000 | PR_AUC_t: 0.0126 | Val Qini: 0.7721 | EMA Qini: 0.7757 | Best EMA: 0.7892 (patience: 10/20)
Epoch 46/150 | Loss: 286.0019 | Cls: 2.3861 | Reg: 9.0491 | mu_t: 4.3759 | sigma_t: 0.7650 | mu_c: 4.3630 | sigma_c: 0.7331 | Val Loss: 9.2453 | F1_c: 0.0000 | PR_AUC_c: 0.0110 | F1_t: 0.0000 | PR_AUC_t: 0.0123 | Val Qini: 0.7691 | EMA Qini: 0.7740 | Best EMA: 0.7892 (patience: 11/20)
Epoch 47/150 | Loss: 266.2599 | Cls: 2.3864 | Reg: 8.4192 | mu_t: 4.3767 | sigma_t: 0.7654 | mu_c: 4.3626 | sigma_c: 0.7333 | Val Loss: 9.2448 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0122 | Val Qini: 0.7635 | EMA Qini: 0.7714 | Best EMA: 0.7892 (patience: 12/20)
Epoch 48/150 | Loss: 265.8115 | Cls: 2.3860 | Reg: 8.4049 | mu_t: 4.3758 | sigma_t: 0.7659 | mu_c: 4.3629 | sigma_c: 0.7332 | Val Loss: 9.2442 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0120 | Val Qini: 0.7628 | EMA Qini: 0.7693 | Best EMA: 0.7892 (patience: 13/20)
Epoch 49/150 | Loss: 271.9827 | Cls: 2.3863 | Reg: 8.6018 | mu_t: 4.3768 | sigma_t: 0.7666 | mu_c: 4.3626 | sigma_c: 0.7336 | Val Loss: 9.2438 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0117 | Val Qini: 0.7610 | EMA Qini: 0.7672 | Best EMA: 0.7892 (patience: 14/20)
Epoch 50/150 | Loss: 270.0728 | Cls: 2.3835 | Reg: 8.5409 | mu_t: 4.3764 | sigma_t: 0.7662 | mu_c: 4.3627 | sigma_c: 0.7340 | Val Loss: 9.2433 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0115 | Val Qini: 0.7576 | EMA Qini: 0.7648 | Best EMA: 0.7892 (patience: 15/20)
Epoch 51/150 | Loss: 321.1884 | Cls: 2.3860 | Reg: 10.1717 | mu_t: 4.3761 | sigma_t: 0.7671 | mu_c: 4.3626 | sigma_c: 0.7340 | Val Loss: 9.2428 | F1_c: 0.0000 | PR_AUC_c: 0.0111 | F1_t: 0.0000 | PR_AUC_t: 0.0114 | Val Qini: 0.7579 | EMA Qini: 0.7631 | Best EMA: 0.7892 (patience: 16/20)
Epoch 52/150 | Loss: 270.9023 | Cls: 2.3842 | Reg: 8.5674 | mu_t: 4.3755 | sigma_t: 0.7675 | mu_c: 4.3622 | sigma_c: 0.7339 | Val Loss: 9.2422 | F1_c: 0.0000 | PR_AUC_c: 0.0112 | F1_t: 0.0000 | PR_AUC_t: 0.0114 | Val Qini: 0.7577 | EMA Qini: 0.7617 | Best EMA: 0.7892 (patience: 17/20)
Epoch 53/150 | Loss: 232.6698 | Cls: 2.3813 | Reg: 7.3476 | mu_t: 4.3762 | sigma_t: 0.7677 | mu_c: 4.3633 | sigma_c: 0.7339 | Val Loss: 9.2416 | F1_c: 0.0000 | PR_AUC_c: 0.0113 | F1_t: 0.0000 | PR_AUC_t: 0.0113 | Val Qini: 0.7567 | EMA Qini: 0.7605 | Best EMA: 0.7892 (patience: 18/20)
Epoch 54/150 | Loss: 261.0408 | Cls: 2.3831 | Reg: 8.2528 | mu_t: 4.3758 | sigma_t: 0.7681 | mu_c: 4.3630 | sigma_c: 0.7342 | Val Loss: 9.2410 | F1_c: 0.0000 | PR_AUC_c: 0.0113 | F1_t: 0.0000 | PR_AUC_t: 0.0112 | Val Qini: 0.7569 | EMA Qini: 0.7596 | Best EMA: 0.7892 (patience: 19/20)
Epoch 55/150 | Loss: 318.0583 | Cls: 2.3851 | Reg: 10.0719 | mu_t: 4.3766 | sigma_t: 0.7686 | mu_c: 4.3633 | sigma_c: 0.7341 | Val Loss: 9.2405 | F1_c: 0.0000 | PR_AUC_c: 0.0113 | F1_t: 0.0000 | PR_AUC_t: 0.0111 | Val Qini: 0.7544 | EMA Qini: 0.7583 | Best EMA: 0.7892 (patience: 20/20)

🛑 Early stopping triggered at epoch 55!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 35
   Best EMA Qini: 0.7892
   Raw Qini at best EMA epoch: 0.7919
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Loss: 278.6067 | Cls: 2.4098 | Reg: 8.8124 | mu_t: 4.4116 | sigma_t: 0.7114 | mu_c: 4.4098 | sigma_c: 0.6885 | Val Loss: 9.3239 | F1_c: 0.0000 | PR_AUC_c: 0.0067 | F1_t: 0.0000 | PR_AUC_t: 0.0092 | Val Qini: 0.7032 | EMA Qini: 0.7032 | Best EMA: 0.7032 ⭐ NEW BEST EMA
Epoch 2/150 | Loss: 321.3806 | Cls: 2.4096 | Reg: 10.1771 | mu_t: 4.4106 | sigma_t: 0.7115 | mu_c: 4.4091 | sigma_c: 0.6887 | Val Loss: 9.3230 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0000 | PR_AUC_t: 0.0092 | Val Qini: 0.7090 | EMA Qini: 0.7046 | Best EMA: 0.7046 ⭐ NEW BEST EMA
Epoch 3/150 | Loss: 289.4644 | Cls: 2.4088 | Reg: 9.1588 | mu_t: 4.4105 | sigma_t: 0.7124 | mu_c: 4.4093 | sigma_c: 0.6890 | Val Loss: 9.3220 | F1_c: 0.0000 | PR_AUC_c: 0.0067 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7080 | EMA Qini: 0.7055 | Best EMA: 0.7055 ⭐ NEW BEST EMA
Epoch 4/150 | Loss: 290.8725 | Cls: 2.4096 | Reg: 9.2037 | mu_t: 4.4101 | sigma_t: 0.7129 | mu_c: 4.4089 | sigma_c: 0.6888 | Val Loss: 9.3210 | F1_c: 0.0000 | PR_AUC_c: 0.0068 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7140 | EMA Qini: 0.7076 | Best EMA: 0.7076 ⭐ NEW BEST EMA
Epoch 5/150 | Loss: 285.5014 | Cls: 2.4072 | Reg: 9.0324 | mu_t: 4.4109 | sigma_t: 0.7132 | mu_c: 4.4095 | sigma_c: 0.6891 | Val Loss: 9.3200 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7164 | EMA Qini: 0.7098 | Best EMA: 0.7098 ⭐ NEW BEST EMA
Epoch 6/150 | Loss: 283.1517 | Cls: 2.4081 | Reg: 8.9574 | mu_t: 4.4089 | sigma_t: 0.7142 | mu_c: 4.4093 | sigma_c: 0.6891 | Val Loss: 9.3190 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7145 | EMA Qini: 0.7110 | Best EMA: 0.7110 ⭐ NEW BEST EMA
Epoch 7/150 | Loss: 229.4586 | Cls: 2.4051 | Reg: 7.2444 | mu_t: 4.4089 | sigma_t: 0.7145 | mu_c: 4.4092 | sigma_c: 0.6894 | Val Loss: 9.3180 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7166 | EMA Qini: 0.7124 | Best EMA: 0.7124 ⭐ NEW BEST EMA
Epoch 8/150 | Loss: 244.6690 | Cls: 2.4047 | Reg: 7.7297 | mu_t: 4.4089 | sigma_t: 0.7154 | mu_c: 4.4095 | sigma_c: 0.6896 | Val Loss: 9.3170 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7208 | EMA Qini: 0.7145 | Best EMA: 0.7145 ⭐ NEW BEST EMA
Epoch 9/150 | Loss: 299.5507 | Cls: 2.4083 | Reg: 9.4807 | mu_t: 4.4082 | sigma_t: 0.7160 | mu_c: 4.4082 | sigma_c: 0.6898 | Val Loss: 9.3159 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7193 | EMA Qini: 0.7157 | Best EMA: 0.7157 ⭐ NEW BEST EMA
Epoch 10/150 | Loss: 269.5566 | Cls: 2.4062 | Reg: 8.5237 | mu_t: 4.4084 | sigma_t: 0.7161 | mu_c: 4.4087 | sigma_c: 0.6899 | Val Loss: 9.3150 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7206 | EMA Qini: 0.7169 | Best EMA: 0.7169 ⭐ NEW BEST EMA
Epoch 11/150 | Loss: 256.0393 | Cls: 2.4056 | Reg: 8.0925 | mu_t: 4.4083 | sigma_t: 0.7171 | mu_c: 4.4093 | sigma_c: 0.6903 | Val Loss: 9.3140 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7220 | EMA Qini: 0.7182 | Best EMA: 0.7182 ⭐ NEW BEST EMA
Epoch 12/150 | Loss: 286.0179 | Cls: 2.4059 | Reg: 9.0490 | mu_t: 4.4076 | sigma_t: 0.7177 | mu_c: 4.4087 | sigma_c: 0.6900 | Val Loss: 9.3131 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0000 | PR_AUC_t: 0.0093 | Val Qini: 0.7202 | EMA Qini: 0.7187 | Best EMA: 0.7187 ⭐ NEW BEST EMA