In [15]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/RERUM")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [16]:
%time train_df = pd.read_csv(r"../dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"../dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"../dataset/Hillstrom/Men/val_men.csv")

CPU times: user 21.7 ms, sys: 7.01 ms, total: 28.7 ms
Wall time: 28.5 ms
CPU times: user 12.8 ms, sys: 4 ms, total: 16.8 ms
Wall time: 16.7 ms
CPU times: user 4.15 ms, sys: 0 ns, total: 4.15 ms
Wall time: 4.15 ms

In [17]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [18]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [19]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [20]:
epochs = 150
early_stop_metric = "loss"
ema = True
ema_alpha = 0.15
patience = 20
early_stop_start = 30
print (f" epochs = {epochs}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 early stop = ema_qini
 use ema = True
 ema alpha = 0.15
 patience = 20
 early stop start = 30

In [ ]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    grid_outcome_dropout = trial.suggest_float("outcome_dropout", 0.0, 0.5)
    grid_shared_dropout = trial.suggest_float("shared_dropout", 0.0, 0.5)
    grid_outcome_hidden = trial.suggest_int("outcome_hidden", 50, 400, step=50)
    grid_shared_hidden = trial.suggest_int("shared_hidden", 50, 400, step=50)

    val_losses = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=grid_shared_hidden,
            outcome_hidden=grid_outcome_hidden,
            outcome_dropout=grid_outcome_dropout,
            shared_dropout=grid_shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
        )

        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        current_val_loss = tarnet.validate(val_loader)
        val_losses.append(current_val_loss)

    mean_val_loss = float(np.mean(val_losses))
    std_val_loss = float(np.std(val_losses, ddof=1)) if len(val_losses) > 1 else 0.0
    trial.set_user_attr("std_Val_Loss", std_val_loss)
    return mean_val_loss

def print_trial_callback(study, trial):
    value = float(trial.value) if trial.value is not None else float("nan")
    best_trial = study.best_trial
    best_value = float(best_trial.value) if best_trial.value is not None else float("nan")
    print(
        f"Finished trial {trial.number}: val loss: {value:.4f} - "
        f"with hyperparameters: {trial.params} | "
        f"best trial: {best_trial.number} loss: {best_value:.4f}",
        flush=True
    )

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="minimize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True, callbacks=[print_trial_callback])

trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": round(float(t.params["lr"]), 4),
        "weight_decay": round(float(t.params["weight_decay"]), 4),
        "shared_hidden": int(t.params["shared_hidden"]),
        "outcome_hidden": int(t.params["outcome_hidden"]),
        "shared_dropout": round(float(t.params["shared_dropout"]), 3),
        "outcome_dropout": round(float(t.params["outcome_dropout"]), 3),
        "mean_Val_Loss": float(t.value),
        "std_Val_Loss": float(t.user_attrs.get("std_Val_Loss", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_Loss", ascending=True).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "shared_hidden": int(best_params["shared_hidden"]),
    "outcome_hidden": int(best_params["outcome_hidden"]),
    "shared_dropout": float(best_params["shared_dropout"]),
    "outcome_dropout": float(best_params["outcome_dropout"]),
    "mean_Val_Loss": float(study.best_value),
    "std_Val_Loss": float(study.best_trial.user_attrs.get("std_Val_Loss", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Finished trial 0: val AUQC: 0.8794 - with hyperparameters: {'lr': 0.00015006912017686197, 'weight_decay': 2.3884552609633584e-05, 'outcome_dropout': 0.2041371296334657, 'shared_dropout': 0.2216925330468017, 'outcome_hidden': 250, 'shared_hidden': 350} | best trial: 0 AUQC: 0.8794

Best trial: 0. Best value: 0.879399:   2%|▏         | 1/50 [01:34<1:17:06, 94.41s/it]

Finished trial 1: val AUQC: 0.8728 - with hyperparameters: {'lr': 0.00043025465630583485, 'weight_decay': 9.52546685451366e-05, 'outcome_dropout': 0.29511631137958266, 'shared_dropout': 0.369412397917029, 'outcome_hidden': 350, 'shared_hidden': 150} | best trial: 0 AUQC: 0.8794

Best trial: 0. Best value: 0.879399:   4%|▍         | 2/50 [03:22<1:21:54, 102.39s/it]

Finished trial 2: val AUQC: 0.8241 - with hyperparameters: {'lr': 0.00013064516400914498, 'weight_decay': 1.4849237750214059e-05, 'outcome_dropout': 0.10786555667219, 'shared_dropout': 0.33395193641300147, 'outcome_hidden': 350, 'shared_hidden': 250} | best trial: 0 AUQC: 0.8794

Best trial: 0. Best value: 0.879399:   6%|▌         | 3/50 [05:20<1:25:56, 109.71s/it]

Finished trial 3: val AUQC: 0.8647 - with hyperparameters: {'lr': 0.00019247010007262055, 'weight_decay': 3.283818020859842e-05, 'outcome_dropout': 0.2613110440775303, 'shared_dropout': 0.299393430173892, 'outcome_hidden': 300, 'shared_hidden': 300} | best trial: 0 AUQC: 0.8794

Best trial: 0. Best value: 0.879399:   8%|▊         | 4/50 [06:53<1:19:04, 103.15s/it]

Finished trial 4: val AUQC: 0.8912 - with hyperparameters: {'lr': 0.0002973589597623869, 'weight_decay': 2.251587423515786e-05, 'outcome_dropout': 0.01370644680148092, 'shared_dropout': 0.35647536041824224, 'outcome_hidden': 350, 'shared_hidden': 100} | best trial: 4 AUQC: 0.8912

Best trial: 4. Best value: 0.89122:  10%|█         | 5/50 [08:57<1:22:56, 110.58s/it]

Finished trial 5: val AUQC: 0.8291 - with hyperparameters: {'lr': 0.00039113022808842586, 'weight_decay': 2.560408643824531e-05, 'outcome_dropout': 0.08545516508355222, 'shared_dropout': 0.14723337668580588, 'outcome_hidden': 250, 'shared_hidden': 350} | best trial: 4 AUQC: 0.8912

Best trial: 4. Best value: 0.89122:  12%|█▏        | 6/50 [10:46<1:20:39, 109.98s/it]

Finished trial 6: val AUQC: 0.8718 - with hyperparameters: {'lr': 0.00021838287274388984, 'weight_decay': 3.2001115759103645e-05, 'outcome_dropout': 0.3277017809120966, 'shared_dropout': 0.09709158836045251, 'outcome_hidden': 350, 'shared_hidden': 150} | best trial: 4 AUQC: 0.8912

Best trial: 4. Best value: 0.89122:  14%|█▍        | 7/50 [12:09<1:12:29, 101.14s/it]

Finished trial 7: val AUQC: 0.8526 - with hyperparameters: {'lr': 0.00014628116480793656, 'weight_decay': 8.973244662799929e-05, 'outcome_dropout': 0.22728212392032476, 'shared_dropout': 0.09606758791930864, 'outcome_hidden': 200, 'shared_hidden': 200} | best trial: 4 AUQC: 0.8912

Best trial: 4. Best value: 0.89122:  16%|█▌        | 8/50 [13:54<1:11:45, 102.52s/it]

Finished trial 8: val AUQC: 0.7790 - with hyperparameters: {'lr': 0.0001842312281105819, 'weight_decay': 3.196367765376636e-05, 'outcome_dropout': 0.11911251517980004, 'shared_dropout': 0.2576010310834246, 'outcome_hidden': 50, 'shared_hidden': 150} | best trial: 4 AUQC: 0.8912

Best trial: 4. Best value: 0.89122:  18%|█▊        | 9/50 [15:33<1:09:07, 101.16s/it]

Finished trial 9: val AUQC: 0.8993 - with hyperparameters: {'lr': 0.0002083346159867299, 'weight_decay': 2.2272741555350945e-05, 'outcome_dropout': 0.4646573494713398, 'shared_dropout': 0.005304115836440082, 'outcome_hidden': 100, 'shared_hidden': 200} | best trial: 9 AUQC: 0.8993

Best trial: 9. Best value: 0.899307:  20%|██        | 10/50 [17:22<1:09:07, 103.68s/it]

Finished trial 10: val AUQC: 0.5442 - with hyperparameters: {'lr': 6.0910572984078646e-05, 'weight_decay': 1.0567003600929912e-05, 'outcome_dropout': 0.49045704847869076, 'shared_dropout': 0.4985212367923584, 'outcome_hidden': 50, 'shared_hidden': 50} | best trial: 9 AUQC: 0.8993

Best trial: 9. Best value: 0.899307:  22%|██▏       | 11/50 [19:00<1:06:22, 102.12s/it]

Finished trial 11: val AUQC: 0.8919 - with hyperparameters: {'lr': 0.00029203354979893465, 'weight_decay': 1.831632614215415e-05, 'outcome_dropout': 0.40948472869292696, 'shared_dropout': 0.03279399006103448, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 9 AUQC: 0.8993

Best trial: 9. Best value: 0.899307:  24%|██▍       | 12/50 [21:02<1:08:22, 107.95s/it]

Finished trial 12: val AUQC: 0.8941 - with hyperparameters: {'lr': 0.0002922321263730087, 'weight_decay': 1.659657116485e-05, 'outcome_dropout': 0.4668246144864449, 'shared_dropout': 0.0006644481366900393, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 9 AUQC: 0.8993

Best trial: 9. Best value: 0.899307:  26%|██▌       | 13/50 [23:03<1:08:58, 111.85s/it]

Finished trial 13: val AUQC: 0.8442 - with hyperparameters: {'lr': 8.628669867568073e-05, 'weight_decay': 5.066860304648549e-05, 'outcome_dropout': 0.4884353067639258, 'shared_dropout': 0.0007661904337891589, 'outcome_hidden': 150, 'shared_hidden': 250} | best trial: 9 AUQC: 0.8993

Best trial: 9. Best value: 0.899307:  28%|██▊       | 14/50 [25:27<1:13:03, 121.76s/it]

Finished trial 14: val AUQC: 0.9176 - with hyperparameters: {'lr': 0.0002671761032701927, 'weight_decay': 1.3069408023158698e-05, 'outcome_dropout': 0.3828593524325523, 'shared_dropout': 0.07147158073517534, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  30%|███       | 15/50 [27:01<1:06:10, 113.45s/it]

Finished trial 15: val AUQC: 0.9105 - with hyperparameters: {'lr': 0.0001097631266198382, 'weight_decay': 1.0521418715635453e-05, 'outcome_dropout': 0.38091785220979, 'shared_dropout': 0.14815431540001178, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  32%|███▏      | 16/50 [29:44<1:12:41, 128.27s/it]

Finished trial 16: val AUQC: 0.9090 - with hyperparameters: {'lr': 0.00010159848822260334, 'weight_decay': 1.1036711982081233e-05, 'outcome_dropout': 0.37431260115633475, 'shared_dropout': 0.17497790301707167, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  34%|███▍      | 17/50 [32:32<1:17:07, 140.23s/it]

Finished trial 17: val AUQC: 0.7876 - with hyperparameters: {'lr': 5.6878403742658426e-05, 'weight_decay': 1.3470504177940684e-05, 'outcome_dropout': 0.36480687087620706, 'shared_dropout': 0.0946151027525708, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  36%|███▌      | 18/50 [34:43<1:13:16, 137.39s/it]

Finished trial 18: val AUQC: 0.8514 - with hyperparameters: {'lr': 0.00010229205949997265, 'weight_decay': 4.6986009640042224e-05, 'outcome_dropout': 0.42172794899720606, 'shared_dropout': 0.1663833857837087, 'outcome_hidden': 200, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  38%|███▊      | 19/50 [36:45<1:08:37, 132.82s/it]

Finished trial 19: val AUQC: 0.8341 - with hyperparameters: {'lr': 7.527846533896648e-05, 'weight_decay': 1.293171579335422e-05, 'outcome_dropout': 0.3238811905550985, 'shared_dropout': 0.07056309500064394, 'outcome_hidden': 50, 'shared_hidden': 300} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  40%|████      | 20/50 [39:12<1:08:33, 137.11s/it]

Finished trial 20: val AUQC: 0.8062 - with hyperparameters: {'lr': 0.00011207185489924076, 'weight_decay': 1.008699000260606e-05, 'outcome_dropout': 0.17374511489022731, 'shared_dropout': 0.19714160886555457, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  42%|████▏     | 21/50 [41:19<1:04:50, 134.15s/it]

Finished trial 21: val AUQC: 0.9031 - with hyperparameters: {'lr': 8.53170750784451e-05, 'weight_decay': 1.1937383620255627e-05, 'outcome_dropout': 0.38308464836915596, 'shared_dropout': 0.13944149590206834, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  44%|████▍     | 22/50 [44:34<1:11:00, 152.16s/it]

Finished trial 22: val AUQC: 0.9061 - with hyperparameters: {'lr': 0.00011458760794407338, 'weight_decay': 1.0088003948799745e-05, 'outcome_dropout': 0.35921659066559397, 'shared_dropout': 0.18325589393217098, 'outcome_hidden': 150, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  46%|████▌     | 23/50 [46:55<1:07:04, 149.07s/it]

Finished trial 23: val AUQC: 0.7810 - with hyperparameters: {'lr': 7.30055852718234e-05, 'weight_decay': 1.5736675137741756e-05, 'outcome_dropout': 0.4245169667939613, 'shared_dropout': 0.1315208605222573, 'outcome_hidden': 50, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  48%|████▊     | 24/50 [48:07<54:34, 125.92s/it]

Finished trial 24: val AUQC: 0.8991 - with hyperparameters: {'lr': 0.00024566330184380773, 'weight_decay': 1.7813454191117425e-05, 'outcome_dropout': 0.2823072587947361, 'shared_dropout': 0.2463076288787721, 'outcome_hidden': 100, 'shared_hidden': 300} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  50%|█████     | 25/50 [49:50<49:33, 118.93s/it]

Finished trial 25: val AUQC: 0.8805 - with hyperparameters: {'lr': 9.50229815344879e-05, 'weight_decay': 1.1947148343082212e-05, 'outcome_dropout': 0.3223058556072339, 'shared_dropout': 0.058616920402830626, 'outcome_hidden': 200, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  52%|█████▏    | 26/50 [51:52<47:57, 119.89s/it]

Finished trial 26: val AUQC: 0.8864 - with hyperparameters: {'lr': 0.00012965261208282405, 'weight_decay': 1.4056973819367146e-05, 'outcome_dropout': 0.3967104045457693, 'shared_dropout': 0.11090830556868848, 'outcome_hidden': 150, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  54%|█████▍    | 27/50 [54:00<46:50, 122.21s/it]

Finished trial 27: val AUQC: 0.8819 - with hyperparameters: {'lr': 0.00016438023923518645, 'weight_decay': 1.919992957394785e-05, 'outcome_dropout': 0.44260196290666043, 'shared_dropout': 0.2034956603672377, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  56%|█████▌    | 28/50 [55:35<41:50, 114.10s/it]

Finished trial 28: val AUQC: 0.9142 - with hyperparameters: {'lr': 0.0003411992888535142, 'weight_decay': 1.1851722495211894e-05, 'outcome_dropout': 0.34564294022228625, 'shared_dropout': 0.4250268349362198, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  58%|█████▊    | 29/50 [57:18<38:48, 110.89s/it]

Finished trial 29: val AUQC: 0.8621 - with hyperparameters: {'lr': 0.0003636601408226598, 'weight_decay': 2.6621244630730452e-05, 'outcome_dropout': 0.19652038656587903, 'shared_dropout': 0.4539646683857831, 'outcome_hidden': 250, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  60%|██████    | 30/50 [58:39<33:58, 101.93s/it]

Finished trial 30: val AUQC: 0.8731 - with hyperparameters: {'lr': 0.0004921527340132544, 'weight_decay': 2.0122105843703568e-05, 'outcome_dropout': 0.34617662912614877, 'shared_dropout': 0.4163617990284521, 'outcome_hidden': 50, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  62%|██████▏   | 31/50 [1:00:06<30:47, 97.23s/it]

Finished trial 31: val AUQC: 0.9104 - with hyperparameters: {'lr': 0.0003615161025973609, 'weight_decay': 1.1879294891927535e-05, 'outcome_dropout': 0.3860205686382393, 'shared_dropout': 0.26442487011465854, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  64%|██████▍   | 32/50 [1:01:36<28:33, 95.17s/it]

Finished trial 32: val AUQC: 0.9034 - with hyperparameters: {'lr': 0.0003575362995386862, 'weight_decay': 1.2838871171829057e-05, 'outcome_dropout': 0.29914271114107127, 'shared_dropout': 0.28428250211999556, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  66%|██████▌   | 33/50 [1:03:03<26:13, 92.58s/it]

Finished trial 33: val AUQC: 0.9056 - with hyperparameters: {'lr': 0.00025178523706596536, 'weight_decay': 1.5164996274346842e-05, 'outcome_dropout': 0.4470374181837296, 'shared_dropout': 0.40442092599934204, 'outcome_hidden': 150, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  68%|██████▊   | 34/50 [1:05:00<26:42, 100.16s/it]

Finished trial 34: val AUQC: 0.8807 - with hyperparameters: {'lr': 0.0004624999775153215, 'weight_decay': 1.1821177320734414e-05, 'outcome_dropout': 0.2558440677223021, 'shared_dropout': 0.3190053233217023, 'outcome_hidden': 50, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  70%|███████   | 35/50 [1:06:19<23:27, 93.80s/it]

Finished trial 35: val AUQC: 0.8493 - with hyperparameters: {'lr': 0.00041507851945883346, 'weight_decay': 4.006625426841009e-05, 'outcome_dropout': 0.2925908071074227, 'shared_dropout': 0.23515859354007415, 'outcome_hidden': 200, 'shared_hidden': 250} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  72%|███████▏  | 36/50 [1:07:35<20:35, 88.24s/it]

Finished trial 36: val AUQC: 0.9005 - with hyperparameters: {'lr': 0.0003249048709129517, 'weight_decay': 7.510135317444627e-05, 'outcome_dropout': 0.39820715583609545, 'shared_dropout': 0.2872913655110237, 'outcome_hidden': 100, 'shared_hidden': 300} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  74%|███████▍  | 37/50 [1:09:18<20:07, 92.86s/it]

Finished trial 37: val AUQC: 0.8816 - with hyperparameters: {'lr': 0.0002503436989251321, 'weight_decay': 1.4602464929254962e-05, 'outcome_dropout': 0.34806040796473925, 'shared_dropout': 0.3643727184252369, 'outcome_hidden': 150, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  76%|███████▌  | 38/50 [1:10:57<18:56, 94.75s/it]

Finished trial 38: val AUQC: 0.8618 - with hyperparameters: {'lr': 0.0003324993271284857, 'weight_decay': 1.1557251591029087e-05, 'outcome_dropout': 0.31063270749754285, 'shared_dropout': 0.4049105366371615, 'outcome_hidden': 300, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  78%|███████▊  | 39/50 [1:12:25<16:58, 92.62s/it]

Finished trial 39: val AUQC: 0.8623 - with hyperparameters: {'lr': 0.00043432321056543615, 'weight_decay': 1.717877697126825e-05, 'outcome_dropout': 0.2631118889329472, 'shared_dropout': 0.06005394801626099, 'outcome_hidden': 50, 'shared_hidden': 350} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  80%|████████  | 40/50 [1:13:40<14:32, 87.24s/it]

Finished trial 40: val AUQC: 0.8975 - with hyperparameters: {'lr': 0.00017096878678425203, 'weight_decay': 1.3738299689223219e-05, 'outcome_dropout': 0.3382776273713626, 'shared_dropout': 0.21867053703267347, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  82%|████████▏ | 41/50 [1:15:40<14:32, 96.99s/it]

Finished trial 41: val AUQC: 0.9080 - with hyperparameters: {'lr': 0.0001322141381122965, 'weight_decay': 1.1068072567741324e-05, 'outcome_dropout': 0.37189617973590416, 'shared_dropout': 0.16368518834399687, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 14 AUQC: 0.9176

Best trial: 14. Best value: 0.91764:  84%|████████▍ | 42/50 [1:17:55<14:27, 108.47s/it]

Finished trial 42: val AUQC: 0.9229 - with hyperparameters: {'lr': 0.0002738877660032207, 'weight_decay': 1.0002138762693344e-05, 'outcome_dropout': 0.3849899546103965, 'shared_dropout': 0.2632576796060926, 'outcome_hidden': 100, 'shared_hidden': 400} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902:  86%|████████▌ | 43/50 [1:19:36<12:23, 106.24s/it]

Finished trial 43: val AUQC: 0.8155 - with hyperparameters: {'lr': 0.00021639679372959485, 'weight_decay': 1.234386273676014e-05, 'outcome_dropout': 0.0015520377689057785, 'shared_dropout': 0.34221297086751173, 'outcome_hidden': 150, 'shared_hidden': 350} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902:  88%|████████▊ | 44/50 [1:21:10<10:15, 102.65s/it]

Finished trial 44: val AUQC: 0.9176 - with hyperparameters: {'lr': 0.0002733447449161375, 'weight_decay': 1.0233966501725324e-05, 'outcome_dropout': 0.4370206202339071, 'shared_dropout': 0.2692969758167973, 'outcome_hidden': 50, 'shared_hidden': 400} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902:  90%|█████████ | 45/50 [1:23:04<08:50, 106.12s/it]

Finished trial 45: val AUQC: 0.8891 - with hyperparameters: {'lr': 0.0002618647792571763, 'weight_decay': 1.0654051526962107e-05, 'outcome_dropout': 0.44190247924806797, 'shared_dropout': 0.3267165333882439, 'outcome_hidden': 50, 'shared_hidden': 300} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902:  92%|█████████▏| 46/50 [1:25:08<07:26, 111.53s/it]

Finished trial 46: val AUQC: 0.7025 - with hyperparameters: {'lr': 0.00027467528800843323, 'weight_decay': 1.4989847852443304e-05, 'outcome_dropout': 0.4163988771529205, 'shared_dropout': 0.48976995919283434, 'outcome_hidden': 50, 'shared_hidden': 100} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902:  94%|█████████▍| 47/50 [1:26:48<05:23, 107.95s/it]

Finished trial 47: val AUQC: 0.9179 - with hyperparameters: {'lr': 0.0003161445309397143, 'weight_decay': 1.0053206487523047e-05, 'outcome_dropout': 0.4580746734332538, 'shared_dropout': 0.11918840765344038, 'outcome_hidden': 50, 'shared_hidden': 400} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902:  96%|█████████▌| 48/50 [1:28:19<03:25, 102.91s/it]

Finished trial 48: val AUQC: 0.9091 - with hyperparameters: {'lr': 0.00019186231227141324, 'weight_decay': 1.0009995423403453e-05, 'outcome_dropout': 0.4713437511360169, 'shared_dropout': 0.029841657890615603, 'outcome_hidden': 50, 'shared_hidden': 400} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902:  98%|█████████▊| 49/50 [1:30:12<01:45, 105.86s/it]

Finished trial 49: val AUQC: 0.8923 - with hyperparameters: {'lr': 0.0003184539734126092, 'weight_decay': 2.136928997701466e-05, 'outcome_dropout': 0.4811778648384929, 'shared_dropout': 0.3121309461583228, 'outcome_hidden': 50, 'shared_hidden': 200} | best trial: 42 AUQC: 0.9229

Best trial: 42. Best value: 0.922902: 100%|██████████| 50/50 [1:32:30<00:00, 111.00s/it]

In [ ]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_Loss: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 42
Best mean_Val_AUQC: 0.922902
Best params: {'lr': 0.0002738877660032207, 'weight_decay': 1.0002138762693344e-05, 'outcome_dropout': 0.3849899546103965, 'shared_dropout': 0.2632576796060926, 'outcome_hidden': 100, 'shared_hidden': 400}

Best config table:

,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_Val_AUQC,std_Val_AUQC
0,0.000274,0.00001,400.0,100.0,0.263258,0.38499,0.922902,0.016049

Top 10 trials:

,trial,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_Val_AUQC,std_Val_AUQC
0,42,0.0003,0.0,400,100,0.263,0.385,0.922902,0.016049
1,47,0.0003,0.0,400,50,0.119,0.458,0.917928,0.021003
2,14,0.0003,0.0,400,100,0.071,0.383,0.917640,0.016629
3,44,0.0003,0.0,400,50,0.269,0.437,0.917585,0.018796
4,28,0.0003,0.0,400,100,0.425,0.346,0.914238,0.024730
5,15,0.0001,0.0,400,100,0.148,0.381,0.910481,0.019284
6,31,0.0004,0.0,400,100,0.264,0.386,0.910371,0.018326
7,48,0.0002,0.0,400,50,0.030,0.471,0.909107,0.014016
8,16,0.0001,0.0,400,100,0.175,0.374,0.909012,0.018227
9,41,0.0001,0.0,400,100,0.164,0.372,0.907971,0.021958

In [23]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_shared_hidden = int(best_cfg['shared_hidden'])
best_outcome_hidden = int(best_cfg['outcome_hidden'])
best_shared_dropout = float(best_cfg['shared_dropout'])
best_outcome_dropout = float(best_cfg['outcome_dropout'])

print("Evaluating on test with best validation config:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"  shared_hidden={best_shared_hidden}, outcome_hidden={best_outcome_hidden}")
print(f"  shared_dropout={best_shared_dropout:.3f}, outcome_dropout={best_outcome_dropout:.3f}")
print(f"Number of seeds: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=best_shared_hidden,
        outcome_hidden=best_outcome_hidden,
        outcome_dropout=best_outcome_dropout,
        shared_dropout=best_shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
    )

    tarnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'PER-SEED DETAILS (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'TEST SUMMARY (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Evaluating on test with best validation config:
  lr=2.7e-04, weight_decay=1.0e-05
  shared_hidden=400, outcome_hidden=100
  shared_dropout=0.263, outcome_dropout=0.385
Number of seeds: 5
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.15)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Loss: 2.8426 | Cls: 2.4967 | Reg: 0.3458 | mu_t: 0.0754 | sigma_t: 0.8002 | mu_c: 0.0289 | sigma_c: 0.7369 | Val Loss: 2.9936 | F1_c: 0.0000 | PR_AUC_c: 0.0072 | F1_t: 0.0000 | PR_AUC_t: 0.0111 | Val Qini: 0.6023 | EMA Qini: 0.6023 | Best EMA: 0.6023 ⭐ NEW BEST EMA
Epoch 2/150 | Loss: 2.8457 | Cls: 2.5280 | Reg: 0.3177 | mu_t: 0.0918 | sigma_t: 0.8342 | mu_c: 0.0389 | sigma_c: 0.7483 | Val Loss: 2.9630 | F1_c: 0.0000 | PR_AUC_c: 0.0076 | F1_t: 0.0370 | PR_AUC_t: 0.0241 | Val Qini: 0.6406 | EMA Qini: 0.6080 | Best EMA: 0.6080 ⭐ NEW BEST EMA
Epoch 3/150 | Loss: 3.0204 | Cls: 2.6431 | Reg: 0.3773 | mu_t: 0.1174 | sigma_t: 0.8867 | mu_c: 0.0527 | sigma_c: 0.7700 | Val Loss: 2.9191 | F1_c: 0.0000 | PR_AUC_c: 0.0075 | F1_t: 0.0370 | PR_AUC_t: 0.0295 | Val Qini: 0.6255 | EMA Qini: 0.6107 | Best EMA: 0.6107 ⭐ NEW BEST EMA
Epoch 4/150 | Loss: 2.7369 | Cls: 2.4676 | Reg: 0.2693 | mu_t: 0.1600 | sigma_t: 0.9724 | mu_c: 0.0728 | sigma_c: 0.8141 | Val Loss: 2.8577 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0370 | PR_AUC_t: 0.0305 | Val Qini: 0.6318 | EMA Qini: 0.6138 | Best EMA: 0.6138 ⭐ NEW BEST EMA
Epoch 5/150 | Loss: 3.3282 | Cls: 2.9930 | Reg: 0.3352 | mu_t: 0.2334 | sigma_t: 1.1239 | mu_c: 0.1112 | sigma_c: 0.8965 | Val Loss: 2.7897 | F1_c: 0.0000 | PR_AUC_c: 0.0077 | F1_t: 0.0370 | PR_AUC_t: 0.0290 | Val Qini: 0.6253 | EMA Qini: 0.6155 | Best EMA: 0.6155 ⭐ NEW BEST EMA
Epoch 6/150 | Loss: 2.5640 | Cls: 2.3673 | Reg: 0.1967 | mu_t: 0.3538 | sigma_t: 1.3488 | mu_c: 0.1761 | sigma_c: 1.0349 | Val Loss: 2.7278 | F1_c: 0.0000 | PR_AUC_c: 0.0081 | F1_t: 0.0370 | PR_AUC_t: 0.0278 | Val Qini: 0.6314 | EMA Qini: 0.6179 | Best EMA: 0.6179 ⭐ NEW BEST EMA
Epoch 7/150 | Loss: 2.4928 | Cls: 2.3360 | Reg: 0.1569 | mu_t: 0.4920 | sigma_t: 1.6496 | mu_c: 0.2891 | sigma_c: 1.2425 | Val Loss: 2.6908 | F1_c: 0.0000 | PR_AUC_c: 0.0086 | F1_t: 0.0370 | PR_AUC_t: 0.0274 | Val Qini: 0.6225 | EMA Qini: 0.6186 | Best EMA: 0.6186 ⭐ NEW BEST EMA
Epoch 8/150 | Loss: 2.4429 | Cls: 2.3022 | Reg: 0.1407 | mu_t: 0.6270 | sigma_t: 1.9085 | mu_c: 0.3992 | sigma_c: 1.4357 | Val Loss: 2.6714 | F1_c: 0.0000 | PR_AUC_c: 0.0097 | F1_t: 0.0370 | PR_AUC_t: 0.0280 | Val Qini: 0.6240 | EMA Qini: 0.6194 | Best EMA: 0.6194 ⭐ NEW BEST EMA
Epoch 9/150 | Loss: 2.3731 | Cls: 2.2536 | Reg: 0.1196 | mu_t: 0.7372 | sigma_t: 2.0799 | mu_c: 0.5029 | sigma_c: 1.5749 | Val Loss: 2.6584 | F1_c: 0.0000 | PR_AUC_c: 0.0099 | F1_t: 0.0370 | PR_AUC_t: 0.0291 | Val Qini: 0.6096 | EMA Qini: 0.6180 | Best EMA: 0.6194 (patience: 0/20)
Epoch 10/150 | Loss: 2.7725 | Cls: 2.6219 | Reg: 0.1507 | mu_t: 0.8265 | sigma_t: 2.1697 | mu_c: 0.5790 | sigma_c: 1.6592 | Val Loss: 2.6485 | F1_c: 0.0000 | PR_AUC_c: 0.0097 | F1_t: 0.0370 | PR_AUC_t: 0.0308 | Val Qini: 0.5914 | EMA Qini: 0.6140 | Best EMA: 0.6194 (patience: 0/20)
Epoch 11/150 | Loss: 2.5949 | Cls: 2.4495 | Reg: 0.1454 | mu_t: 0.8731 | sigma_t: 2.2195 | mu_c: 0.6594 | sigma_c: 1.7225 | Val Loss: 2.6391 | F1_c: 0.0000 | PR_AUC_c: 0.0085 | F1_t: 0.0370 | PR_AUC_t: 0.0315 | Val Qini: 0.5645 | EMA Qini: 0.6066 | Best EMA: 0.6194 (patience: 0/20)
Epoch 12/150 | Loss: 2.6671 | Cls: 2.5198 | Reg: 0.1473 | mu_t: 0.9595 | sigma_t: 2.3240 | mu_c: 0.7541 | sigma_c: 1.8562 | Val Loss: 2.6214 | F1_c: 0.0000 | PR_AUC_c: 0.0077 | F1_t: 0.0370 | PR_AUC_t: 0.0305 | Val Qini: 0.5383 | EMA Qini: 0.5963 | Best EMA: 0.6194 (patience: 0/20)
Epoch 13/150 | Loss: 2.5781 | Cls: 2.4500 | Reg: 0.1281 | mu_t: 1.0798 | sigma_t: 2.4376 | mu_c: 0.8516 | sigma_c: 1.9914 | Val Loss: 2.6038 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0370 | PR_AUC_t: 0.0310 | Val Qini: 0.5223 | EMA Qini: 0.5852 | Best EMA: 0.6194 (patience: 0/20)
Epoch 14/150 | Loss: 2.5752 | Cls: 2.4356 | Reg: 0.1397 | mu_t: 1.1318 | sigma_t: 2.4932 | mu_c: 0.9510 | sigma_c: 2.0883 | Val Loss: 2.5900 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0370 | PR_AUC_t: 0.0331 | Val Qini: 0.5392 | EMA Qini: 0.5783 | Best EMA: 0.6194 (patience: 0/20)
Epoch 15/150 | Loss: 2.8536 | Cls: 2.6933 | Reg: 0.1603 | mu_t: 1.1763 | sigma_t: 2.5820 | mu_c: 1.0649 | sigma_c: 2.2128 | Val Loss: 2.5830 | F1_c: 0.0000 | PR_AUC_c: 0.0069 | F1_t: 0.0370 | PR_AUC_t: 0.0333 | Val Qini: 0.5552 | EMA Qini: 0.5748 | Best EMA: 0.6194 (patience: 0/20)
Epoch 16/150 | Loss: 2.9755 | Cls: 2.8132 | Reg: 0.1624 | mu_t: 1.2386 | sigma_t: 2.6321 | mu_c: 1.1786 | sigma_c: 2.3258 | Val Loss: 2.5778 | F1_c: 0.0000 | PR_AUC_c: 0.0068 | F1_t: 0.0370 | PR_AUC_t: 0.0322 | Val Qini: 0.5747 | EMA Qini: 0.5748 | Best EMA: 0.6194 (patience: 0/20)
Epoch 17/150 | Loss: 2.8519 | Cls: 2.7129 | Reg: 0.1390 | mu_t: 1.2869 | sigma_t: 2.6839 | mu_c: 1.2481 | sigma_c: 2.3963 | Val Loss: 2.5743 | F1_c: 0.0000 | PR_AUC_c: 0.0068 | F1_t: 0.0370 | PR_AUC_t: 0.0327 | Val Qini: 0.5934 | EMA Qini: 0.5776 | Best EMA: 0.6194 (patience: 0/20)
Epoch 18/150 | Loss: 2.5833 | Cls: 2.4553 | Reg: 0.1280 | mu_t: 1.3316 | sigma_t: 2.6565 | mu_c: 1.2812 | sigma_c: 2.3744 | Val Loss: 2.5671 | F1_c: 0.0000 | PR_AUC_c: 0.0068 | F1_t: 0.0370 | PR_AUC_t: 0.0333 | Val Qini: 0.6255 | EMA Qini: 0.5848 | Best EMA: 0.6194 (patience: 0/20)
Epoch 19/150 | Loss: 2.7186 | Cls: 2.5924 | Reg: 0.1262 | mu_t: 1.3799 | sigma_t: 2.6280 | mu_c: 1.3124 | sigma_c: 2.3675 | Val Loss: 2.5653 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0370 | PR_AUC_t: 0.0342 | Val Qini: 0.6371 | EMA Qini: 0.5926 | Best EMA: 0.6194 (patience: 0/20)
Epoch 20/150 | Loss: 2.6793 | Cls: 2.5407 | Reg: 0.1386 | mu_t: 1.3831 | sigma_t: 2.5676 | mu_c: 1.3660 | sigma_c: 2.3926 | Val Loss: 2.5622 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0370 | PR_AUC_t: 0.0345 | Val Qini: 0.6475 | EMA Qini: 0.6009 | Best EMA: 0.6194 (patience: 0/20)
Epoch 21/150 | Loss: 2.5409 | Cls: 2.4136 | Reg: 0.1273 | mu_t: 1.4325 | sigma_t: 2.5831 | mu_c: 1.3595 | sigma_c: 2.3603 | Val Loss: 2.5619 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0370 | PR_AUC_t: 0.0337 | Val Qini: 0.6775 | EMA Qini: 0.6124 | Best EMA: 0.6194 (patience: 0/20)
Epoch 22/150 | Loss: 2.4719 | Cls: 2.3526 | Reg: 0.1193 | mu_t: 1.4608 | sigma_t: 2.5596 | mu_c: 1.4150 | sigma_c: 2.4089 | Val Loss: 2.5623 | F1_c: 0.0000 | PR_AUC_c: 0.0072 | F1_t: 0.0370 | PR_AUC_t: 0.0328 | Val Qini: 0.7114 | EMA Qini: 0.6272 | Best EMA: 0.6272 ⭐ NEW BEST EMA
Epoch 23/150 | Loss: 2.7687 | Cls: 2.6188 | Reg: 0.1499 | mu_t: 1.4790 | sigma_t: 2.5252 | mu_c: 1.4143 | sigma_c: 2.4035 | Val Loss: 2.5637 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0741 | PR_AUC_t: 0.0319 | Val Qini: 0.7228 | EMA Qini: 0.6415 | Best EMA: 0.6415 ⭐ NEW BEST EMA
Epoch 24/150 | Loss: 2.6831 | Cls: 2.5369 | Reg: 0.1463 | mu_t: 1.4679 | sigma_t: 2.4521 | mu_c: 1.4272 | sigma_c: 2.3730 | Val Loss: 2.5651 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0741 | PR_AUC_t: 0.0307 | Val Qini: 0.7432 | EMA Qini: 0.6568 | Best EMA: 0.6568 ⭐ NEW BEST EMA
Epoch 25/150 | Loss: 2.6517 | Cls: 2.5126 | Reg: 0.1391 | mu_t: 1.4928 | sigma_t: 2.4140 | mu_c: 1.3797 | sigma_c: 2.2978 | Val Loss: 2.5650 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0741 | PR_AUC_t: 0.0302 | Val Qini: 0.7693 | EMA Qini: 0.6737 | Best EMA: 0.6737 ⭐ NEW BEST EMA
Epoch 26/150 | Loss: 2.6521 | Cls: 2.5172 | Reg: 0.1349 | mu_t: 1.5087 | sigma_t: 2.3877 | mu_c: 1.4055 | sigma_c: 2.2907 | Val Loss: 2.5672 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0741 | PR_AUC_t: 0.0304 | Val Qini: 0.7905 | EMA Qini: 0.6912 | Best EMA: 0.6912 ⭐ NEW BEST EMA
Epoch 27/150 | Loss: 2.5441 | Cls: 2.4154 | Reg: 0.1287 | mu_t: 1.5400 | sigma_t: 2.3861 | mu_c: 1.4399 | sigma_c: 2.3212 | Val Loss: 2.5658 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0370 | PR_AUC_t: 0.0308 | Val Qini: 0.8315 | EMA Qini: 0.7122 | Best EMA: 0.7122 ⭐ NEW BEST EMA
Epoch 28/150 | Loss: 2.6042 | Cls: 2.4727 | Reg: 0.1315 | mu_t: 1.5870 | sigma_t: 2.3956 | mu_c: 1.5183 | sigma_c: 2.3902 | Val Loss: 2.5687 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0370 | PR_AUC_t: 0.0303 | Val Qini: 0.8685 | EMA Qini: 0.7357 | Best EMA: 0.7357 ⭐ NEW BEST EMA
Epoch 29/150 | Loss: 2.2972 | Cls: 2.1858 | Reg: 0.1115 | mu_t: 1.6128 | sigma_t: 2.3695 | mu_c: 1.5396 | sigma_c: 2.4052 | Val Loss: 2.5717 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0370 | PR_AUC_t: 0.0300 | Val Qini: 0.9390 | EMA Qini: 0.7662 | Best EMA: 0.7662 ⭐ NEW BEST EMA
Epoch 30/150 | Loss: 2.3331 | Cls: 2.2166 | Reg: 0.1165 | mu_t: 1.6423 | sigma_t: 2.3665 | mu_c: 1.5698 | sigma_c: 2.4414 | Val Loss: 2.5737 | F1_c: 0.0000 | PR_AUC_c: 0.0072 | F1_t: 0.0370 | PR_AUC_t: 0.0297 | Val Qini: 0.9633 | EMA Qini: 0.7957 | Best EMA: 0.7957 ⭐ NEW BEST EMA
Epoch 31/150 | Loss: 2.6404 | Cls: 2.5030 | Reg: 0.1374 | mu_t: 1.6841 | sigma_t: 2.3526 | mu_c: 1.6056 | sigma_c: 2.4710 | Val Loss: 2.5715 | F1_c: 0.0000 | PR_AUC_c: 0.0072 | F1_t: 0.0741 | PR_AUC_t: 0.0293 | Val Qini: 0.9735 | EMA Qini: 0.8224 | Best EMA: 0.8224 ⭐ NEW BEST EMA
Epoch 32/150 | Loss: 2.5922 | Cls: 2.4593 | Reg: 0.1328 | mu_t: 1.7274 | sigma_t: 2.3702 | mu_c: 1.6826 | sigma_c: 2.5146 | Val Loss: 2.5752 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0741 | PR_AUC_t: 0.0288 | Val Qini: 0.9697 | EMA Qini: 0.8445 | Best EMA: 0.8445 ⭐ NEW BEST EMA
Epoch 33/150 | Loss: 2.3931 | Cls: 2.2709 | Reg: 0.1222 | mu_t: 1.8061 | sigma_t: 2.4207 | mu_c: 1.7318 | sigma_c: 2.5436 | Val Loss: 2.5728 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0741 | PR_AUC_t: 0.0295 | Val Qini: 0.9680 | EMA Qini: 0.8630 | Best EMA: 0.8630 ⭐ NEW BEST EMA
Epoch 34/150 | Loss: 3.0032 | Cls: 2.8405 | Reg: 0.1627 | mu_t: 1.8626 | sigma_t: 2.4553 | mu_c: 1.8036 | sigma_c: 2.5845 | Val Loss: 2.5690 | F1_c: 0.0000 | PR_AUC_c: 0.0072 | F1_t: 0.0370 | PR_AUC_t: 0.0298 | Val Qini: 0.9670 | EMA Qini: 0.8786 | Best EMA: 0.8786 ⭐ NEW BEST EMA
Epoch 35/150 | Loss: 3.0253 | Cls: 2.8547 | Reg: 0.1707 | mu_t: 1.9268 | sigma_t: 2.4960 | mu_c: 1.8822 | sigma_c: 2.6258 | Val Loss: 2.5668 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0741 | PR_AUC_t: 0.0299 | Val Qini: 0.9773 | EMA Qini: 0.8934 | Best EMA: 0.8934 ⭐ NEW BEST EMA
Epoch 36/150 | Loss: 2.6728 | Cls: 2.5263 | Reg: 0.1466 | mu_t: 1.9364 | sigma_t: 2.4905 | mu_c: 1.8883 | sigma_c: 2.6235 | Val Loss: 2.5580 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0741 | PR_AUC_t: 0.0302 | Val Qini: 0.9715 | EMA Qini: 0.9051 | Best EMA: 0.9051 ⭐ NEW BEST EMA
Epoch 37/150 | Loss: 2.4417 | Cls: 2.3157 | Reg: 0.1260 | mu_t: 1.9209 | sigma_t: 2.4481 | mu_c: 1.8562 | sigma_c: 2.5346 | Val Loss: 2.5575 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0000 | PR_AUC_t: 0.0300 | Val Qini: 0.9657 | EMA Qini: 0.9142 | Best EMA: 0.9142 ⭐ NEW BEST EMA
Epoch 38/150 | Loss: 2.1900 | Cls: 2.0803 | Reg: 0.1097 | mu_t: 1.9364 | sigma_t: 2.4098 | mu_c: 1.8828 | sigma_c: 2.5392 | Val Loss: 2.5634 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0370 | PR_AUC_t: 0.0292 | Val Qini: 0.9720 | EMA Qini: 0.9229 | Best EMA: 0.9229 ⭐ NEW BEST EMA
Epoch 39/150 | Loss: 2.5297 | Cls: 2.3898 | Reg: 0.1399 | mu_t: 1.9455 | sigma_t: 2.3820 | mu_c: 1.8935 | sigma_c: 2.5400 | Val Loss: 2.5689 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0370 | PR_AUC_t: 0.0285 | Val Qini: 0.9700 | EMA Qini: 0.9300 | Best EMA: 0.9300 ⭐ NEW BEST EMA
Epoch 40/150 | Loss: 2.2763 | Cls: 2.1639 | Reg: 0.1124 | mu_t: 1.9379 | sigma_t: 2.3470 | mu_c: 1.8745 | sigma_c: 2.4947 | Val Loss: 2.5633 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0370 | PR_AUC_t: 0.0291 | Val Qini: 0.9611 | EMA Qini: 0.9346 | Best EMA: 0.9346 ⭐ NEW BEST EMA
Epoch 41/150 | Loss: 2.5508 | Cls: 2.4164 | Reg: 0.1344 | mu_t: 1.9321 | sigma_t: 2.3147 | mu_c: 1.8831 | sigma_c: 2.4972 | Val Loss: 2.5581 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0000 | PR_AUC_t: 0.0294 | Val Qini: 0.9467 | EMA Qini: 0.9364 | Best EMA: 0.9364 ⭐ NEW BEST EMA
Epoch 42/150 | Loss: 2.6866 | Cls: 2.5406 | Reg: 0.1460 | mu_t: 1.9485 | sigma_t: 2.3150 | mu_c: 1.8905 | sigma_c: 2.4920 | Val Loss: 2.5570 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0370 | PR_AUC_t: 0.0291 | Val Qini: 0.9327 | EMA Qini: 0.9359 | Best EMA: 0.9364 (patience: 1/20)
Epoch 43/150 | Loss: 2.3431 | Cls: 2.2295 | Reg: 0.1136 | mu_t: 1.9835 | sigma_t: 2.3262 | mu_c: 1.8761 | sigma_c: 2.4591 | Val Loss: 2.5493 | F1_c: 0.0000 | PR_AUC_c: 0.0070 | F1_t: 0.0000 | PR_AUC_t: 0.0295 | Val Qini: 0.9348 | EMA Qini: 0.9357 | Best EMA: 0.9364 (patience: 2/20)
Epoch 44/150 | Loss: 2.2627 | Cls: 2.1515 | Reg: 0.1112 | mu_t: 2.0367 | sigma_t: 2.3265 | mu_c: 1.9876 | sigma_c: 2.5462 | Val Loss: 2.5591 | F1_c: 0.0000 | PR_AUC_c: 0.0071 | F1_t: 0.0000 | PR_AUC_t: 0.0293 | Val Qini: 0.9270 | EMA Qini: 0.9344 | Best EMA: 0.9364 (patience: 3/20)
Epoch 45/150 | Loss: 2.5133 | Cls: 2.3790 | Reg: 0.1343 | mu_t: 2.1039 | sigma_t: 2.3637 | mu_c: 2.1077 | sigma_c: 2.6244 | Val Loss: 2.5744 | F1_c: 0.0000 | PR_AUC_c: 0.0072 | F1_t: 0.0370 | PR_AUC_t: 0.0290 | Val Qini: 0.9198 | EMA Qini: 0.9322 | Best EMA: 0.9364 (patience: 4/20)
Epoch 46/150 | Loss: 2.3832 | Cls: 2.2573 | Reg: 0.1259 | mu_t: 2.1464 | sigma_t: 2.3820 | mu_c: 2.1857 | sigma_c: 2.6690 | Val Loss: 2.5685 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0370 | PR_AUC_t: 0.0290 | Val Qini: 0.9139 | EMA Qini: 0.9295 | Best EMA: 0.9364 (patience: 5/20)
Epoch 47/150 | Loss: 2.3531 | Cls: 2.2386 | Reg: 0.1146 | mu_t: 2.1930 | sigma_t: 2.4003 | mu_c: 2.2003 | sigma_c: 2.6488 | Val Loss: 2.5696 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0370 | PR_AUC_t: 0.0294 | Val Qini: 0.9158 | EMA Qini: 0.9274 | Best EMA: 0.9364 (patience: 6/20)
Epoch 48/150 | Loss: 2.8279 | Cls: 2.6761 | Reg: 0.1518 | mu_t: 2.2166 | sigma_t: 2.4027 | mu_c: 2.2973 | sigma_c: 2.6726 | Val Loss: 2.5689 | F1_c: 0.0000 | PR_AUC_c: 0.0075 | F1_t: 0.0370 | PR_AUC_t: 0.0294 | Val Qini: 0.9212 | EMA Qini: 0.9265 | Best EMA: 0.9364 (patience: 7/20)
Epoch 49/150 | Loss: 2.4071 | Cls: 2.2895 | Reg: 0.1176 | mu_t: 2.2503 | sigma_t: 2.4131 | mu_c: 2.3520 | sigma_c: 2.6752 | Val Loss: 2.5601 | F1_c: 0.0000 | PR_AUC_c: 0.0075 | F1_t: 0.0370 | PR_AUC_t: 0.0303 | Val Qini: 0.9184 | EMA Qini: 0.9253 | Best EMA: 0.9364 (patience: 8/20)
Epoch 50/150 | Loss: 2.4292 | Cls: 2.3011 | Reg: 0.1281 | mu_t: 2.3263 | sigma_t: 2.4787 | mu_c: 2.3967 | sigma_c: 2.6792 | Val Loss: 2.5512 | F1_c: 0.0000 | PR_AUC_c: 0.0075 | F1_t: 0.0370 | PR_AUC_t: 0.0311 | Val Qini: 0.9249 | EMA Qini: 0.9252 | Best EMA: 0.9364 (patience: 9/20)
Epoch 51/150 | Loss: 2.3102 | Cls: 2.1966 | Reg: 0.1136 | mu_t: 2.2974 | sigma_t: 2.4318 | mu_c: 2.3821 | sigma_c: 2.6400 | Val Loss: 2.5479 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0370 | PR_AUC_t: 0.0318 | Val Qini: 0.9149 | EMA Qini: 0.9237 | Best EMA: 0.9364 (patience: 10/20)
Epoch 52/150 | Loss: 2.3203 | Cls: 2.1857 | Reg: 0.1346 | mu_t: 2.2891 | sigma_t: 2.3903 | mu_c: 2.4041 | sigma_c: 2.6296 | Val Loss: 2.5540 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0370 | PR_AUC_t: 0.0309 | Val Qini: 0.9114 | EMA Qini: 0.9218 | Best EMA: 0.9364 (patience: 11/20)
Epoch 53/150 | Loss: 2.5903 | Cls: 2.4485 | Reg: 0.1419 | mu_t: 2.3620 | sigma_t: 2.4113 | mu_c: 2.5544 | sigma_c: 2.7136 | Val Loss: 2.5890 | F1_c: 0.0000 | PR_AUC_c: 0.0074 | F1_t: 0.0370 | PR_AUC_t: 0.0302 | Val Qini: 0.9121 | EMA Qini: 0.9204 | Best EMA: 0.9364 (patience: 12/20)
Epoch 54/150 | Loss: 2.3945 | Cls: 2.2636 | Reg: 0.1309 | mu_t: 2.4567 | sigma_t: 2.4634 | mu_c: 2.6330 | sigma_c: 2.7435 | Val Loss: 2.5788 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0370 | PR_AUC_t: 0.0300 | Val Qini: 0.9093 | EMA Qini: 0.9187 | Best EMA: 0.9364 (patience: 13/20)
Epoch 55/150 | Loss: 2.4295 | Cls: 2.3070 | Reg: 0.1225 | mu_t: 2.5028 | sigma_t: 2.4736 | mu_c: 2.6005 | sigma_c: 2.7085 | Val Loss: 2.5606 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0370 | PR_AUC_t: 0.0302 | Val Qini: 0.9028 | EMA Qini: 0.9163 | Best EMA: 0.9364 (patience: 14/20)
Epoch 56/150 | Loss: 2.3756 | Cls: 2.2514 | Reg: 0.1242 | mu_t: 2.5367 | sigma_t: 2.4699 | mu_c: 2.6971 | sigma_c: 2.7565 | Val Loss: 2.5691 | F1_c: 0.0000 | PR_AUC_c: 0.0073 | F1_t: 0.0370 | PR_AUC_t: 0.0302 | Val Qini: 0.8964 | EMA Qini: 0.9133 | Best EMA: 0.9364 (patience: 15/20)
Epoch 57/150 | Loss: 2.6102 | Cls: 2.4738 | Reg: 0.1364 | mu_t: 2.5908 | sigma_t: 2.4679 | mu_c: 2.7244 | sigma_c: 2.7477 | Val Loss: 2.5738 | F1_c: 0.0000 | PR_AUC_c: 0.0075 | F1_t: 0.0370 | PR_AUC_t: 0.0293 | Val Qini: 0.8825 | EMA Qini: 0.9087 | Best EMA: 0.9364 (patience: 16/20)
Epoch 58/150 | Loss: 2.4913 | Cls: 2.3731 | Reg: 0.1182 | mu_t: 2.6222 | sigma_t: 2.4729 | mu_c: 2.7379 | sigma_c: 2.7018 | Val Loss: 2.5721 | F1_c: 0.0000 | PR_AUC_c: 0.0075 | F1_t: 0.0370 | PR_AUC_t: 0.0289 | Val Qini: 0.8584 | EMA Qini: 0.9012 | Best EMA: 0.9364 (patience: 17/20)
Epoch 59/150 | Loss: 2.2930 | Cls: 2.1832 | Reg: 0.1098 | mu_t: 2.6178 | sigma_t: 2.4333 | mu_c: 2.7868 | sigma_c: 2.7256 | Val Loss: 2.5764 | F1_c: 0.0000 | PR_AUC_c: 0.0077 | F1_t: 0.0370 | PR_AUC_t: 0.0283 | Val Qini: 0.8222 | EMA Qini: 0.8893 | Best EMA: 0.9364 (patience: 18/20)
Epoch 60/150 | Loss: 2.5806 | Cls: 2.4479 | Reg: 0.1327 | mu_t: 2.6536 | sigma_t: 2.4190 | mu_c: 2.9179 | sigma_c: 2.7934 | Val Loss: 2.5904 | F1_c: 0.0000 | PR_AUC_c: 0.0078 | F1_t: 0.0370 | PR_AUC_t: 0.0273 | Val Qini: 0.7373 | EMA Qini: 0.8665 | Best EMA: 0.9364 (patience: 19/20)
Epoch 61/150 | Loss: 2.2471 | Cls: 2.1331 | Reg: 0.1140 | mu_t: 2.6256 | sigma_t: 2.3827 | mu_c: 2.7969 | sigma_c: 2.6834 | Val Loss: 2.5749 | F1_c: 0.0000 | PR_AUC_c: 0.0076 | F1_t: 0.0741 | PR_AUC_t: 0.0282 | Val Qini: 0.7077 | EMA Qini: 0.8427 | Best EMA: 0.9364 (patience: 20/20)

🛑 Early stopping triggered at epoch 61!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 41
   Best EMA Qini: 0.9364
   Raw Qini at best EMA epoch: 0.9467
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.15)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Loss: 3.0138 | Cls: 2.5748 | Reg: 0.4390 | mu_t: 0.0217 | sigma_t: 0.7007 | mu_c: 0.0716 | sigma_c: 0.6674 | Val Loss: 3.0678 | F1_c: 0.0833 | PR_AUC_c: 0.0135 | F1_t: 0.0741 | PR_AUC_t: 0.0346 | Val Qini: 0.5101 | EMA Qini: 0.5101 | Best EMA: 0.5101 ⭐ NEW BEST EMA
Epoch 2/150 | Loss: 3.1206 | Cls: 2.6366 | Reg: 0.4840 | mu_t: 0.0407 | sigma_t: 0.7214 | mu_c: 0.0813 | sigma_c: 0.6788 | Val Loss: 3.0366 | F1_c: 0.0000 | PR_AUC_c: 0.0087 | F1_t: 0.0741 | PR_AUC_t: 0.0288 | Val Qini: 0.5558 | EMA Qini: 0.5169 | Best EMA: 0.5169 ⭐ NEW BEST EMA
Epoch 3/150 | Loss: 3.1645 | Cls: 2.7010 | Reg: 0.4635 | mu_t: 0.0761 | sigma_t: 0.7494 | mu_c: 0.0915 | sigma_c: 0.6955 | Val Loss: 2.9934 | F1_c: 0.0000 | PR_AUC_c: 0.0092 | F1_t: 0.0370 | PR_AUC_t: 0.0293 | Val Qini: 0.5862 | EMA Qini: 0.5273 | Best EMA: 0.5273 ⭐ NEW BEST EMA
Epoch 4/150 | Loss: 2.7407 | Cls: 2.4259 | Reg: 0.3147 | mu_t: 0.1457 | sigma_t: 0.7990 | mu_c: 0.1141 | sigma_c: 0.7219 | Val Loss: 2.9318 | F1_c: 0.0000 | PR_AUC_c: 0.0098 | F1_t: 0.0370 | PR_AUC_t: 0.0291 | Val Qini: 0.6036 | EMA Qini: 0.5388 | Best EMA: 0.5388 ⭐ NEW BEST EMA
Epoch 5/150 | Loss: 2.6299 | Cls: 2.3522 | Reg: 0.2777 | mu_t: 0.2618 | sigma_t: 0.8839 | mu_c: 0.1586 | sigma_c: 0.7657 | Val Loss: 2.8526 | F1_c: 0.0000 | PR_AUC_c: 0.0099 | F1_t: 0.0370 | PR_AUC_t: 0.0289 | Val Qini: 0.6184 | EMA Qini: 0.5507 | Best EMA: 0.5507 ⭐ NEW BEST EMA
Epoch 6/150 | Loss: 2.8207 | Cls: 2.5449 | Reg: 0.2758 | mu_t: 0.4583 | sigma_t: 1.0406 | mu_c: 0.2398 | sigma_c: 0.8454 | Val Loss: 2.7713 | F1_c: 0.0000 | PR_AUC_c: 0.0098 | F1_t: 0.0370 | PR_AUC_t: 0.0293 | Val Qini: 0.6236 | EMA Qini: 0.5616 | Best EMA: 0.5616 ⭐ NEW BEST EMA