In [19]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/RERUM")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
sys.path.append("..")
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [20]:
%time train_df = pd.read_csv(r"../dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"../dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"../dataset/Hillstrom/Men/val_men.csv")

CPU times: user 23.4 ms, sys: 6.03 ms, total: 29.4 ms
Wall time: 29 ms
CPU times: user 16.2 ms, sys: 1 ms, total: 17.2 ms
Wall time: 17.1 ms
CPU times: user 4.9 ms, sys: 0 ns, total: 4.9 ms
Wall time: 4.9 ms

In [21]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [22]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [23]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [24]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [25]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [26]:
epochs = 150
lr = 1e-3
wd = 1e-5
early_stop_metric = "ema_qini"
ema = True
ema_alpha = 0.25
patience = 20
shared_dropout = 0.0
outcome_dropout = 0
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
uplift_ranking = 0
response_ranking = 0
print (f" epochs = {epochs}")
print (f" learning rate = {lr}")
print (f" weight decay = {wd}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" shared hidden = {shared_hidden}")
print (f" outcome hidden = {outcome_hidden}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 learning rate = 0.001
 weight decay = 1e-05
 early stop = ema_qini
 use ema = True
 ema alpha = 0.25
 patience = 20
 shared hidden = 200
 outcome hidden = 100
 early stop start = 30

In [27]:
import pandas as pd
import numpy as np
import torch
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-4, log=True)
    grid_outcome_dropout = trial.suggest_float("outcome_dropout", 0.0, 0.5)
    grid_shared_dropout = trial.suggest_float("shared_dropout", 0.0, 0.5)
    grid_outcome_hidden = trial.suggest_int("outcome_hidden", 50, 400, step=50)
    grid_shared_hidden = trial.suggest_int("shared_hidden", 50, 400, step=50)

    val_scores = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=grid_shared_hidden,
            outcome_hidden=grid_outcome_hidden,
            outcome_dropout=grid_outcome_dropout,
            shared_dropout=grid_shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            uplift_ranking=uplift_ranking,
            response_ranking=response_ranking
        )

        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_val_device = x_men_val_t.to(device)
        y0_val_p, y1_val_p = tarnet.predict(x_val_device)
        uplift_val = (y1_val_p - y0_val_p).detach().cpu().numpy().flatten()
        y_val_true_np = y_men_val_t.detach().cpu().numpy().flatten()
        t_val_true_np = t_men_val_t.detach().cpu().numpy().flatten()

        current_val_auqc = auqc(y_val_true_np, t_val_true_np, uplift_val, bins=100, plot=False)
        val_scores.append(current_val_auqc)

    mean_val_auqc = float(np.mean(val_scores))
    std_val_auqc = float(np.std(val_scores, ddof=1)) if len(val_scores) > 1 else 0.0
    trial.set_user_attr("std_Val_AUQC", std_val_auqc)
    return mean_val_auqc

def print_trial_callback(study, trial):
    value = float(trial.value) if trial.value is not None else float("nan")
    best_trial = study.best_trial
    best_value = float(best_trial.value) if best_trial.value is not None else float("nan")
    print(
        f"Finished trial {trial.number}: val AUQC: {value:.4f} - "
        f"with hyperparameters: {trial.params} | "
        f"best trial: {best_trial.number} AUQC: {best_value:.4f}",
        flush=True
    )

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True, callbacks=[print_trial_callback])

trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": round(float(t.params["lr"]), 4),
        "weight_decay": round(float(t.params["weight_decay"]), 4),
        "shared_hidden": int(t.params["shared_hidden"]),
        "outcome_hidden": int(t.params["outcome_hidden"]),
        "shared_dropout": round(float(t.params["shared_dropout"]), 3),
        "outcome_dropout": round(float(t.params["outcome_dropout"]), 3),
        "mean_Val_AUQC": float(t.value),
        "std_Val_AUQC": float(t.user_attrs.get("std_Val_AUQC", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_Val_AUQC", ascending=False).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "shared_hidden": int(best_params["shared_hidden"]),
    "outcome_hidden": int(best_params["outcome_hidden"]),
    "shared_dropout": float(best_params["shared_dropout"]),
    "outcome_dropout": float(best_params["outcome_dropout"]),
    "mean_Val_AUQC": float(study.best_value),
    "std_Val_AUQC": float(study.best_trial.user_attrs.get("std_Val_AUQC", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Finished trial 0: val AUQC: 0.8242 - with hyperparameters: {'lr': 0.00015006912017686197, 'weight_decay': 2.3884552609633584e-05, 'outcome_dropout': 0.2041371296334657, 'shared_dropout': 0.2216925330468017, 'outcome_hidden': 250, 'shared_hidden': 350} | best trial: 0 AUQC: 0.8242

Best trial: 0. Best value: 0.824216:   2%|▏         | 1/50 [01:14<1:01:01, 74.72s/it]

Finished trial 1: val AUQC: 0.8309 - with hyperparameters: {'lr': 0.00043025465630583485, 'weight_decay': 9.52546685451366e-05, 'outcome_dropout': 0.29511631137958266, 'shared_dropout': 0.369412397917029, 'outcome_hidden': 350, 'shared_hidden': 150} | best trial: 1 AUQC: 0.8309

Best trial: 1. Best value: 0.830919:   4%|▍         | 2/50 [02:21<56:03, 70.07s/it]

Finished trial 2: val AUQC: 0.8185 - with hyperparameters: {'lr': 0.00013064516400914498, 'weight_decay': 1.4849237750214059e-05, 'outcome_dropout': 0.10786555667219, 'shared_dropout': 0.33395193641300147, 'outcome_hidden': 350, 'shared_hidden': 250} | best trial: 1 AUQC: 0.8309

Best trial: 1. Best value: 0.830919:   6%|▌         | 3/50 [03:54<1:03:01, 80.45s/it]

Finished trial 3: val AUQC: 0.8205 - with hyperparameters: {'lr': 0.00019247010007262055, 'weight_decay': 3.283818020859842e-05, 'outcome_dropout': 0.2613110440775303, 'shared_dropout': 0.299393430173892, 'outcome_hidden': 300, 'shared_hidden': 300} | best trial: 1 AUQC: 0.8309

Best trial: 1. Best value: 0.830919:   8%|▊         | 4/50 [05:17<1:02:27, 81.46s/it]

Finished trial 4: val AUQC: 0.8042 - with hyperparameters: {'lr': 0.0002973589597623869, 'weight_decay': 2.251587423515786e-05, 'outcome_dropout': 0.01370644680148092, 'shared_dropout': 0.35647536041824224, 'outcome_hidden': 350, 'shared_hidden': 100} | best trial: 1 AUQC: 0.8309

Best trial: 1. Best value: 0.830919:  10%|█         | 5/50 [06:25<57:28, 76.63s/it]

Finished trial 5: val AUQC: 0.8015 - with hyperparameters: {'lr': 0.00039113022808842586, 'weight_decay': 2.560408643824531e-05, 'outcome_dropout': 0.08545516508355222, 'shared_dropout': 0.14723337668580588, 'outcome_hidden': 250, 'shared_hidden': 350} | best trial: 1 AUQC: 0.8309

Best trial: 1. Best value: 0.830919:  12%|█▏        | 6/50 [07:32<53:53, 73.50s/it]

Finished trial 6: val AUQC: 0.8433 - with hyperparameters: {'lr': 0.00021838287274388984, 'weight_decay': 3.2001115759103645e-05, 'outcome_dropout': 0.3277017809120966, 'shared_dropout': 0.09709158836045251, 'outcome_hidden': 350, 'shared_hidden': 150} | best trial: 6 AUQC: 0.8433

Best trial: 6. Best value: 0.843289:  14%|█▍        | 7/50 [08:44<52:16, 72.94s/it]

Finished trial 7: val AUQC: 0.8292 - with hyperparameters: {'lr': 0.00014628116480793656, 'weight_decay': 8.973244662799929e-05, 'outcome_dropout': 0.22728212392032476, 'shared_dropout': 0.09606758791930864, 'outcome_hidden': 200, 'shared_hidden': 200} | best trial: 6 AUQC: 0.8433

Best trial: 6. Best value: 0.843289:  16%|█▌        | 8/50 [10:41<1:00:47, 86.85s/it]

Finished trial 8: val AUQC: 0.8361 - with hyperparameters: {'lr': 0.0001842312281105819, 'weight_decay': 3.196367765376636e-05, 'outcome_dropout': 0.11911251517980004, 'shared_dropout': 0.2576010310834246, 'outcome_hidden': 50, 'shared_hidden': 150} | best trial: 6 AUQC: 0.8433

Best trial: 6. Best value: 0.843289:  18%|█▊        | 9/50 [12:50<1:08:26, 100.15s/it]

Finished trial 9: val AUQC: 0.8339 - with hyperparameters: {'lr': 0.0002083346159867299, 'weight_decay': 2.2272741555350945e-05, 'outcome_dropout': 0.4646573494713398, 'shared_dropout': 0.005304115836440082, 'outcome_hidden': 100, 'shared_hidden': 200} | best trial: 6 AUQC: 0.8433

Best trial: 6. Best value: 0.843289:  20%|██        | 10/50 [14:31<1:06:49, 100.24s/it]

Finished trial 10: val AUQC: 0.6619 - with hyperparameters: {'lr': 6.188408010779227e-05, 'weight_decay': 5.2913444421251176e-05, 'outcome_dropout': 0.40283301825424445, 'shared_dropout': 0.4985212367923584, 'outcome_hidden': 400, 'shared_hidden': 50} | best trial: 6 AUQC: 0.8433

Best trial: 6. Best value: 0.843289:  22%|██▏       | 11/50 [16:55<1:13:51, 113.62s/it]

Finished trial 11: val AUQC: 0.6901 - with hyperparameters: {'lr': 8.574062318496978e-05, 'weight_decay': 4.339174564831305e-05, 'outcome_dropout': 0.3535626104645638, 'shared_dropout': 0.19466328667309124, 'outcome_hidden': 50, 'shared_hidden': 100} | best trial: 6 AUQC: 0.8433

Best trial: 6. Best value: 0.843289:  24%|██▍       | 12/50 [19:36<1:21:12, 128.24s/it]

Finished trial 12: val AUQC: 0.8415 - with hyperparameters: {'lr': 0.00025660753966430386, 'weight_decay': 1.040715373548348e-05, 'outcome_dropout': 0.1380510441146296, 'shared_dropout': 0.04019485524734376, 'outcome_hidden': 150, 'shared_hidden': 150} | best trial: 6 AUQC: 0.8433

Best trial: 6. Best value: 0.843289:  26%|██▌       | 13/50 [20:46<1:08:10, 110.55s/it]

Finished trial 13: val AUQC: 0.8485 - with hyperparameters: {'lr': 0.00027199123327569864, 'weight_decay': 1.0344142329583511e-05, 'outcome_dropout': 0.16894681325329847, 'shared_dropout': 0.0010046577968951947, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 13 AUQC: 0.8485

Best trial: 13. Best value: 0.848498:  28%|██▊       | 14/50 [22:53<1:09:13, 115.36s/it]

Finished trial 14: val AUQC: 0.8515 - with hyperparameters: {'lr': 0.00030389276917572967, 'weight_decay': 1.4930963399067105e-05, 'outcome_dropout': 0.33359444380102254, 'shared_dropout': 0.08962338507642582, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 14 AUQC: 0.8515

Best trial: 14. Best value: 0.851523:  30%|███       | 15/50 [24:59<1:09:15, 118.73s/it]

Finished trial 15: val AUQC: 0.8553 - with hyperparameters: {'lr': 0.00030905284586347684, 'weight_decay': 1.0375786631469545e-05, 'outcome_dropout': 0.19109924150979776, 'shared_dropout': 0.06175898611799606, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 15 AUQC: 0.8553

Best trial: 15. Best value: 0.855253:  32%|███▏      | 16/50 [27:06<1:08:36, 121.08s/it]

Finished trial 16: val AUQC: 0.8561 - with hyperparameters: {'lr': 0.0003317809365329913, 'weight_decay': 1.5046319370186031e-05, 'outcome_dropout': 0.40320998318951295, 'shared_dropout': 0.0921488359967757, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 16 AUQC: 0.8561

Best trial: 16. Best value: 0.856104:  34%|███▍      | 17/50 [29:17<1:08:21, 124.29s/it]

Finished trial 17: val AUQC: 0.8133 - with hyperparameters: {'lr': 0.00045497600718190855, 'weight_decay': 1.4904527557951798e-05, 'outcome_dropout': 0.46874458069085156, 'shared_dropout': 0.16482883020955863, 'outcome_hidden': 200, 'shared_hidden': 400} | best trial: 16 AUQC: 0.8561

Best trial: 16. Best value: 0.856104:  36%|███▌      | 18/50 [30:25<57:13, 107.30s/it]

Finished trial 18: val AUQC: 0.8370 - with hyperparameters: {'lr': 0.00037290051253743714, 'weight_decay': 1.287781966628652e-05, 'outcome_dropout': 0.4051492289935892, 'shared_dropout': 0.13685059682361495, 'outcome_hidden': 100, 'shared_hidden': 100} | best trial: 16 AUQC: 0.8561

Best trial: 16. Best value: 0.856104:  38%|███▊      | 19/50 [31:55<52:46, 102.16s/it]

Finished trial 19: val AUQC: 0.8583 - with hyperparameters: {'lr': 0.00048544926902417256, 'weight_decay': 1.7506823778329366e-05, 'outcome_dropout': 0.40367819120439496, 'shared_dropout': 0.05677241185532449, 'outcome_hidden': 100, 'shared_hidden': 50} | best trial: 19 AUQC: 0.8583

Best trial: 19. Best value: 0.858318:  40%|████      | 20/50 [33:45<52:09, 104.33s/it]

Finished trial 20: val AUQC: 0.8344 - with hyperparameters: {'lr': 0.0004797841603260072, 'weight_decay': 1.807881071743818e-05, 'outcome_dropout': 0.4059649351946118, 'shared_dropout': 0.45044943435382967, 'outcome_hidden': 100, 'shared_hidden': 250} | best trial: 19 AUQC: 0.8583

Best trial: 19. Best value: 0.858318:  42%|████▏     | 21/50 [35:01<46:21, 95.91s/it]

Finished trial 21: val AUQC: 0.8601 - with hyperparameters: {'lr': 0.00033690890324992355, 'weight_decay': 1.7994976886784733e-05, 'outcome_dropout': 0.48277037315831794, 'shared_dropout': 0.055499153029158824, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 21 AUQC: 0.8601

Best trial: 21. Best value: 0.860134:  44%|████▍     | 22/50 [37:08<49:06, 105.22s/it]

Finished trial 22: val AUQC: 0.8376 - with hyperparameters: {'lr': 0.00036012691498606755, 'weight_decay': 1.874527431846593e-05, 'outcome_dropout': 0.48173436220575216, 'shared_dropout': 0.03506111032710347, 'outcome_hidden': 100, 'shared_hidden': 100} | best trial: 21 AUQC: 0.8601

Best trial: 21. Best value: 0.860134:  46%|████▌     | 23/50 [38:48<46:41, 103.77s/it]

Finished trial 23: val AUQC: 0.8632 - with hyperparameters: {'lr': 0.00048750993040433665, 'weight_decay': 1.8543536095633704e-05, 'outcome_dropout': 0.4251250588247927, 'shared_dropout': 0.12029105300721837, 'outcome_hidden': 200, 'shared_hidden': 50} | best trial: 23 AUQC: 0.8632

Best trial: 23. Best value: 0.863219:  48%|████▊     | 24/50 [40:05<41:25, 95.61s/it]

Finished trial 24: val AUQC: 0.8378 - with hyperparameters: {'lr': 0.000497426706643504, 'weight_decay': 2.6211356809679784e-05, 'outcome_dropout': 0.4967091353358005, 'shared_dropout': 0.13542693983425014, 'outcome_hidden': 200, 'shared_hidden': 100} | best trial: 23 AUQC: 0.8632

Best trial: 23. Best value: 0.863219:  50%|█████     | 25/50 [41:24<37:50, 90.81s/it]

Finished trial 25: val AUQC: 0.8651 - with hyperparameters: {'lr': 0.0004232052725357424, 'weight_decay': 1.8099912864513507e-05, 'outcome_dropout': 0.4342142016230476, 'shared_dropout': 0.052596662188160725, 'outcome_hidden': 250, 'shared_hidden': 50} | best trial: 25 AUQC: 0.8651

Best trial: 25. Best value: 0.865121:  52%|█████▏    | 26/50 [43:07<37:42, 94.25s/it]

Finished trial 26: val AUQC: 0.7742 - with hyperparameters: {'lr': 0.00010472019518528508, 'weight_decay': 4.3070135496247624e-05, 'outcome_dropout': 0.44660577275974656, 'shared_dropout': 0.18912855256123307, 'outcome_hidden': 250, 'shared_hidden': 100} | best trial: 25 AUQC: 0.8651

Best trial: 25. Best value: 0.865121:  54%|█████▍    | 27/50 [46:07<46:03, 120.17s/it]

Finished trial 27: val AUQC: 0.8636 - with hyperparameters: {'lr': 0.00039731124914699055, 'weight_decay': 1.985840480974288e-05, 'outcome_dropout': 0.3638751538829594, 'shared_dropout': 0.12209160044339336, 'outcome_hidden': 300, 'shared_hidden': 50} | best trial: 25 AUQC: 0.8651

Best trial: 25. Best value: 0.865121:  56%|█████▌    | 28/50 [47:41<41:10, 112.28s/it]

Finished trial 28: val AUQC: 0.8285 - with hyperparameters: {'lr': 0.00024046697223659567, 'weight_decay': 1.2926914466548361e-05, 'outcome_dropout': 0.3760947830994961, 'shared_dropout': 0.1178360280380703, 'outcome_hidden': 300, 'shared_hidden': 200} | best trial: 25 AUQC: 0.8651

Best trial: 25. Best value: 0.865121:  58%|█████▊    | 29/50 [48:48<34:31, 98.66s/it]

Finished trial 29: val AUQC: 0.8348 - with hyperparameters: {'lr': 0.0004100891452290102, 'weight_decay': 2.1677447644178055e-05, 'outcome_dropout': 0.3035094770622676, 'shared_dropout': 0.22443505038800038, 'outcome_hidden': 300, 'shared_hidden': 150} | best trial: 25 AUQC: 0.8651

Best trial: 25. Best value: 0.865121:  60%|██████    | 30/50 [49:55<29:41, 89.09s/it]

Finished trial 30: val AUQC: 0.7009 - with hyperparameters: {'lr': 5.721220363426405e-05, 'weight_decay': 2.700564067987711e-05, 'outcome_dropout': 0.43608720415561153, 'shared_dropout': 0.2599622238287651, 'outcome_hidden': 250, 'shared_hidden': 100} | best trial: 25 AUQC: 0.8651

Best trial: 25. Best value: 0.865121:  62%|██████▏   | 31/50 [52:09<32:31, 102.70s/it]

Finished trial 31: val AUQC: 0.8663 - with hyperparameters: {'lr': 0.0003635915902646548, 'weight_decay': 1.9468060610916243e-05, 'outcome_dropout': 0.4451388769165732, 'shared_dropout': 0.0628487662892154, 'outcome_hidden': 200, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  64%|██████▍   | 32/50 [53:51<30:42, 102.38s/it]

Finished trial 32: val AUQC: 0.8624 - with hyperparameters: {'lr': 0.0004088452535514522, 'weight_decay': 2.0434844779931404e-05, 'outcome_dropout': 0.4363338983079625, 'shared_dropout': 0.17316694131153731, 'outcome_hidden': 250, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  66%|██████▌   | 33/50 [55:14<27:19, 96.45s/it]

Finished trial 33: val AUQC: 0.8597 - with hyperparameters: {'lr': 0.00041368234590810236, 'weight_decay': 1.2598477130164761e-05, 'outcome_dropout': 0.36624059980905244, 'shared_dropout': 0.022667112264128028, 'outcome_hidden': 300, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  68%|██████▊   | 34/50 [56:36<24:36, 92.30s/it]

Finished trial 34: val AUQC: 0.8300 - with hyperparameters: {'lr': 0.0003434379325814075, 'weight_decay': 1.640272549041437e-05, 'outcome_dropout': 0.26185036547994633, 'shared_dropout': 0.07054401076457559, 'outcome_hidden': 200, 'shared_hidden': 100} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  70%|███████   | 35/50 [57:47<21:27, 85.80s/it]

Finished trial 35: val AUQC: 0.8378 - with hyperparameters: {'lr': 0.00028318002547486046, 'weight_decay': 2.8416625942357852e-05, 'outcome_dropout': 0.4396331408770384, 'shared_dropout': 0.2149211891903684, 'outcome_hidden': 250, 'shared_hidden': 300} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  72%|███████▏  | 36/50 [58:52<18:34, 79.62s/it]

Finished trial 36: val AUQC: 0.8214 - with hyperparameters: {'lr': 0.00043414586141024124, 'weight_decay': 2.025173904828675e-05, 'outcome_dropout': 0.300590923299056, 'shared_dropout': 0.1182684714562772, 'outcome_hidden': 400, 'shared_hidden': 150} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  74%|███████▍  | 37/50 [59:57<16:18, 75.28s/it]

Finished trial 37: val AUQC: 0.8373 - with hyperparameters: {'lr': 0.0003844989198889893, 'weight_decay': 3.5887345771425635e-05, 'outcome_dropout': 0.37068627810719834, 'shared_dropout': 0.2977442257307777, 'outcome_hidden': 300, 'shared_hidden': 100} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  76%|███████▌  | 38/50 [1:01:11<14:56, 74.71s/it]

Finished trial 38: val AUQC: 0.8288 - with hyperparameters: {'lr': 0.0001679091175170577, 'weight_decay': 2.3591074887878554e-05, 'outcome_dropout': 0.33929284125067716, 'shared_dropout': 0.11731599268471035, 'outcome_hidden': 200, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  78%|███████▊  | 39/50 [1:03:23<16:52, 92.09s/it]

Finished trial 39: val AUQC: 0.8129 - with hyperparameters: {'lr': 0.000234050151444192, 'weight_decay': 1.2551864797555338e-05, 'outcome_dropout': 0.42983642629740165, 'shared_dropout': 0.16127368769256947, 'outcome_hidden': 350, 'shared_hidden': 100} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  80%|████████  | 40/50 [1:04:39<14:30, 87.06s/it]

Finished trial 40: val AUQC: 0.8214 - with hyperparameters: {'lr': 0.00011341244979856283, 'weight_decay': 2.0206261382541028e-05, 'outcome_dropout': 0.04701178376118087, 'shared_dropout': 0.08084137934978794, 'outcome_hidden': 250, 'shared_hidden': 300} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  82%|████████▏ | 41/50 [1:06:03<12:56, 86.25s/it]

Finished trial 41: val AUQC: 0.8660 - with hyperparameters: {'lr': 0.00042993272143802055, 'weight_decay': 2.392118863973529e-05, 'outcome_dropout': 0.4516684298049191, 'shared_dropout': 0.17008893697545477, 'outcome_hidden': 250, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  84%|████████▍ | 42/50 [1:07:28<11:27, 85.91s/it]

Finished trial 42: val AUQC: 0.8629 - with hyperparameters: {'lr': 0.000435926748227057, 'weight_decay': 2.4009291884749182e-05, 'outcome_dropout': 0.455881752545563, 'shared_dropout': 0.1199157815955072, 'outcome_hidden': 300, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  86%|████████▌ | 43/50 [1:08:50<09:53, 84.75s/it]

Finished trial 43: val AUQC: 0.8658 - with hyperparameters: {'lr': 0.0003722992765683683, 'weight_decay': 1.657374593907707e-05, 'outcome_dropout': 0.499386169597348, 'shared_dropout': 0.025361931927710878, 'outcome_hidden': 200, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  88%|████████▊ | 44/50 [1:10:28<08:51, 88.64s/it]

Finished trial 44: val AUQC: 0.8626 - with hyperparameters: {'lr': 0.00031629118767708737, 'weight_decay': 8.312103642191608e-05, 'outcome_dropout': 0.49505402789591846, 'shared_dropout': 0.02179297905257463, 'outcome_hidden': 250, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  90%|█████████ | 45/50 [1:12:06<07:37, 91.57s/it]

Finished trial 45: val AUQC: 0.7998 - with hyperparameters: {'lr': 0.00036597893572022666, 'weight_decay': 2.9916892846558944e-05, 'outcome_dropout': 0.47060770782486094, 'shared_dropout': 0.045599901804690285, 'outcome_hidden': 350, 'shared_hidden': 100} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  92%|█████████▏| 46/50 [1:13:10<05:33, 83.36s/it]

Finished trial 46: val AUQC: 0.8486 - with hyperparameters: {'lr': 0.0002694699994368087, 'weight_decay': 1.6301442262067008e-05, 'outcome_dropout': 0.388620523565628, 'shared_dropout': 0.02392035904034817, 'outcome_hidden': 200, 'shared_hidden': 150} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  94%|█████████▍| 47/50 [1:14:19<03:56, 78.99s/it]

Finished trial 47: val AUQC: 0.7924 - with hyperparameters: {'lr': 7.555578962874053e-05, 'weight_decay': 3.430699056005272e-05, 'outcome_dropout': 0.4596847424970998, 'shared_dropout': 0.0012756500127275167, 'outcome_hidden': 300, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  96%|█████████▌| 48/50 [1:15:49<02:44, 82.12s/it]

Finished trial 48: val AUQC: 0.8169 - with hyperparameters: {'lr': 0.0002043965761083333, 'weight_decay': 2.311711419222019e-05, 'outcome_dropout': 0.4172155439359637, 'shared_dropout': 0.10411150590551496, 'outcome_hidden': 250, 'shared_hidden': 100} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332:  98%|█████████▊| 49/50 [1:18:04<01:37, 97.95s/it]

Finished trial 49: val AUQC: 0.8615 - with hyperparameters: {'lr': 0.0002916575602312138, 'weight_decay': 1.3701395084929704e-05, 'outcome_dropout': 0.27671260838008455, 'shared_dropout': 0.07750747582917489, 'outcome_hidden': 200, 'shared_hidden': 50} | best trial: 31 AUQC: 0.8663

Best trial: 31. Best value: 0.866332: 100%|██████████| 50/50 [1:19:29<00:00, 95.39s/it]

In [28]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 31
Best mean_Val_AUQC: 0.866332
Best params: {'lr': 0.0003635915902646548, 'weight_decay': 1.9468060610916243e-05, 'outcome_dropout': 0.4451388769165732, 'shared_dropout': 0.0628487662892154, 'outcome_hidden': 200, 'shared_hidden': 50}

Best config table:

,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_Val_AUQC,std_Val_AUQC
0,0.000364,0.000019,50.0,200.0,0.062849,0.445139,0.866332,0.014456

Top 10 trials:

,trial,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_Val_AUQC,std_Val_AUQC
0,31,0.0004,0.0000,50,200,0.063,0.445,0.866332,0.014456
1,41,0.0004,0.0000,50,250,0.170,0.452,0.865961,0.021785
2,43,0.0004,0.0000,50,200,0.025,0.499,0.865770,0.019914
3,25,0.0004,0.0000,50,250,0.053,0.434,0.865121,0.015514
4,27,0.0004,0.0000,50,300,0.122,0.364,0.863606,0.019744
5,23,0.0005,0.0000,50,200,0.120,0.425,0.863219,0.013597
6,42,0.0004,0.0000,50,300,0.120,0.456,0.862949,0.022557
7,44,0.0003,0.0001,50,250,0.022,0.495,0.862638,0.023609
8,32,0.0004,0.0000,50,250,0.173,0.436,0.862417,0.026124
9,49,0.0003,0.0000,50,200,0.078,0.277,0.861516,0.019319

In [29]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_shared_hidden = int(best_cfg['shared_hidden'])
best_outcome_hidden = int(best_cfg['outcome_hidden'])
best_shared_dropout = float(best_cfg['shared_dropout'])
best_outcome_dropout = float(best_cfg['outcome_dropout'])

print("Evaluating on test with best validation config:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"  shared_hidden={best_shared_hidden}, outcome_hidden={best_outcome_hidden}")
print(f"  shared_dropout={best_shared_dropout:.3f}, outcome_dropout={best_outcome_dropout:.3f}")
print(f"Number of seeds: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=best_shared_hidden,
        outcome_hidden=best_outcome_hidden,
        outcome_dropout=best_outcome_dropout,
        shared_dropout=best_shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
    )

    tarnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'PER-SEED DETAILS (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'TEST SUMMARY (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Evaluating on test with best validation config:
  lr=3.6e-04, weight_decay=1.9e-05
  shared_hidden=50, outcome_hidden=200
  shared_dropout=0.063, outcome_dropout=0.445
Number of seeds: 5
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 396.7755 | Total Loss: 396.7755 | Val Loss: 498.6939 | Val Qini: 0.3341 | EMA Qini: 0.3341 | Best EMA: 0.3341 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 439.0504 | Total Loss: 439.0504 | Val Loss: 498.4614 | Val Qini: 0.5462 | EMA Qini: 0.3871 | Best EMA: 0.3871 ⭐ NEW BEST EMA
Epoch 3/150 | Base Loss: 487.4245 | Total Loss: 487.4245 | Val Loss: 498.2247 | Val Qini: 0.6248 | EMA Qini: 0.4465 | Best EMA: 0.4465 ⭐ NEW BEST EMA
Epoch 4/150 | Base Loss: 480.0308 | Total Loss: 480.0308 | Val Loss: 497.9692 | Val Qini: 0.6984 | EMA Qini: 0.5095 | Best EMA: 0.5095 ⭐ NEW BEST EMA
Epoch 5/150 | Base Loss: 495.3330 | Total Loss: 495.3330 | Val Loss: 497.6889 | Val Qini: 0.7490 | EMA Qini: 0.5694 | Best EMA: 0.5694 ⭐ NEW BEST EMA
Epoch 6/150 | Base Loss: 224.1360 | Total Loss: 224.1360 | Val Loss: 497.3741 | Val Qini: 0.8327 | EMA Qini: 0.6352 | Best EMA: 0.6352 ⭐ NEW BEST EMA
Epoch 7/150 | Base Loss: 543.3034 | Total Loss: 543.3034 | Val Loss: 497.0267 | Val Qini: 0.8622 | EMA Qini: 0.6920 | Best EMA: 0.6920 ⭐ NEW BEST EMA
Epoch 8/150 | Base Loss: 533.9315 | Total Loss: 533.9315 | Val Loss: 496.6581 | Val Qini: 0.8476 | EMA Qini: 0.7309 | Best EMA: 0.7309 ⭐ NEW BEST EMA
Epoch 9/150 | Base Loss: 490.4246 | Total Loss: 490.4246 | Val Loss: 496.3117 | Val Qini: 0.8426 | EMA Qini: 0.7588 | Best EMA: 0.7588 ⭐ NEW BEST EMA
Epoch 10/150 | Base Loss: 452.0934 | Total Loss: 452.0934 | Val Loss: 496.0440 | Val Qini: 0.8287 | EMA Qini: 0.7763 | Best EMA: 0.7763 ⭐ NEW BEST EMA
Epoch 11/150 | Base Loss: 567.4387 | Total Loss: 567.4387 | Val Loss: 495.8969 | Val Qini: 0.8184 | EMA Qini: 0.7868 | Best EMA: 0.7868 ⭐ NEW BEST EMA
Epoch 12/150 | Base Loss: 353.7434 | Total Loss: 353.7434 | Val Loss: 495.8234 | Val Qini: 0.8152 | EMA Qini: 0.7939 | Best EMA: 0.7939 ⭐ NEW BEST EMA
Epoch 13/150 | Base Loss: 391.5319 | Total Loss: 391.5319 | Val Loss: 495.7997 | Val Qini: 0.8180 | EMA Qini: 0.7999 | Best EMA: 0.7999 ⭐ NEW BEST EMA
Epoch 14/150 | Base Loss: 533.9969 | Total Loss: 533.9969 | Val Loss: 495.7837 | Val Qini: 0.8212 | EMA Qini: 0.8052 | Best EMA: 0.8052 ⭐ NEW BEST EMA
Epoch 15/150 | Base Loss: 487.9153 | Total Loss: 487.9153 | Val Loss: 495.7764 | Val Qini: 0.8243 | EMA Qini: 0.8100 | Best EMA: 0.8100 ⭐ NEW BEST EMA
Epoch 16/150 | Base Loss: 293.4514 | Total Loss: 293.4514 | Val Loss: 495.7664 | Val Qini: 0.8302 | EMA Qini: 0.8151 | Best EMA: 0.8151 ⭐ NEW BEST EMA
Epoch 17/150 | Base Loss: 479.2119 | Total Loss: 479.2119 | Val Loss: 495.7545 | Val Qini: 0.8322 | EMA Qini: 0.8193 | Best EMA: 0.8193 ⭐ NEW BEST EMA
Epoch 18/150 | Base Loss: 347.7354 | Total Loss: 347.7354 | Val Loss: 495.7495 | Val Qini: 0.8405 | EMA Qini: 0.8246 | Best EMA: 0.8246 ⭐ NEW BEST EMA
Epoch 19/150 | Base Loss: 314.6588 | Total Loss: 314.6588 | Val Loss: 495.7448 | Val Qini: 0.8471 | EMA Qini: 0.8303 | Best EMA: 0.8303 ⭐ NEW BEST EMA
Epoch 20/150 | Base Loss: 467.4453 | Total Loss: 467.4453 | Val Loss: 495.7396 | Val Qini: 0.8525 | EMA Qini: 0.8358 | Best EMA: 0.8358 ⭐ NEW BEST EMA
Epoch 21/150 | Base Loss: 280.4725 | Total Loss: 280.4725 | Val Loss: 495.7363 | Val Qini: 0.8544 | EMA Qini: 0.8405 | Best EMA: 0.8405 ⭐ NEW BEST EMA
Epoch 22/150 | Base Loss: 439.2262 | Total Loss: 439.2262 | Val Loss: 495.7260 | Val Qini: 0.8547 | EMA Qini: 0.8440 | Best EMA: 0.8440 ⭐ NEW BEST EMA
Epoch 23/150 | Base Loss: 320.4221 | Total Loss: 320.4221 | Val Loss: 495.7114 | Val Qini: 0.8540 | EMA Qini: 0.8465 | Best EMA: 0.8465 ⭐ NEW BEST EMA
Epoch 24/150 | Base Loss: 658.9832 | Total Loss: 658.9832 | Val Loss: 495.7081 | Val Qini: 0.8551 | EMA Qini: 0.8487 | Best EMA: 0.8487 ⭐ NEW BEST EMA
Epoch 25/150 | Base Loss: 310.0756 | Total Loss: 310.0756 | Val Loss: 495.6995 | Val Qini: 0.8554 | EMA Qini: 0.8504 | Best EMA: 0.8504 ⭐ NEW BEST EMA
Epoch 26/150 | Base Loss: 478.0094 | Total Loss: 478.0094 | Val Loss: 495.6916 | Val Qini: 0.8551 | EMA Qini: 0.8515 | Best EMA: 0.8515 ⭐ NEW BEST EMA
Epoch 27/150 | Base Loss: 363.0919 | Total Loss: 363.0919 | Val Loss: 495.6828 | Val Qini: 0.8576 | EMA Qini: 0.8531 | Best EMA: 0.8531 ⭐ NEW BEST EMA
Epoch 28/150 | Base Loss: 388.4211 | Total Loss: 388.4211 | Val Loss: 495.6726 | Val Qini: 0.8574 | EMA Qini: 0.8541 | Best EMA: 0.8541 ⭐ NEW BEST EMA
Epoch 29/150 | Base Loss: 286.3284 | Total Loss: 286.3284 | Val Loss: 495.6659 | Val Qini: 0.8585 | EMA Qini: 0.8552 | Best EMA: 0.8552 ⭐ NEW BEST EMA
Epoch 30/150 | Base Loss: 524.7697 | Total Loss: 524.7697 | Val Loss: 495.6604 | Val Qini: 0.8583 | EMA Qini: 0.8560 | Best EMA: 0.8560 ⭐ NEW BEST EMA
Epoch 31/150 | Base Loss: 340.6198 | Total Loss: 340.6198 | Val Loss: 495.6532 | Val Qini: 0.8568 | EMA Qini: 0.8562 | Best EMA: 0.8562 ⭐ NEW BEST EMA
Epoch 32/150 | Base Loss: 485.2819 | Total Loss: 485.2819 | Val Loss: 495.6475 | Val Qini: 0.8561 | EMA Qini: 0.8562 | Best EMA: 0.8562 (patience: 1/20)
Epoch 33/150 | Base Loss: 363.9002 | Total Loss: 363.9002 | Val Loss: 495.6403 | Val Qini: 0.8559 | EMA Qini: 0.8561 | Best EMA: 0.8562 (patience: 2/20)
Epoch 34/150 | Base Loss: 566.9860 | Total Loss: 566.9860 | Val Loss: 495.6353 | Val Qini: 0.8563 | EMA Qini: 0.8561 | Best EMA: 0.8562 (patience: 3/20)
Epoch 35/150 | Base Loss: 544.1860 | Total Loss: 544.1860 | Val Loss: 495.6315 | Val Qini: 0.8555 | EMA Qini: 0.8560 | Best EMA: 0.8562 (patience: 4/20)
Epoch 36/150 | Base Loss: 502.6882 | Total Loss: 502.6882 | Val Loss: 495.6288 | Val Qini: 0.8581 | EMA Qini: 0.8565 | Best EMA: 0.8565 ⭐ NEW BEST EMA
Epoch 37/150 | Base Loss: 515.6381 | Total Loss: 515.6381 | Val Loss: 495.6238 | Val Qini: 0.8584 | EMA Qini: 0.8570 | Best EMA: 0.8570 ⭐ NEW BEST EMA
Epoch 38/150 | Base Loss: 581.5466 | Total Loss: 581.5466 | Val Loss: 495.6210 | Val Qini: 0.8583 | EMA Qini: 0.8573 | Best EMA: 0.8573 ⭐ NEW BEST EMA
Epoch 39/150 | Base Loss: 538.7133 | Total Loss: 538.7133 | Val Loss: 495.6183 | Val Qini: 0.8617 | EMA Qini: 0.8584 | Best EMA: 0.8584 ⭐ NEW BEST EMA
Epoch 40/150 | Base Loss: 545.0704 | Total Loss: 545.0704 | Val Loss: 495.6140 | Val Qini: 0.8630 | EMA Qini: 0.8595 | Best EMA: 0.8595 ⭐ NEW BEST EMA
Epoch 41/150 | Base Loss: 432.7976 | Total Loss: 432.7976 | Val Loss: 495.6122 | Val Qini: 0.8625 | EMA Qini: 0.8603 | Best EMA: 0.8603 ⭐ NEW BEST EMA
Epoch 42/150 | Base Loss: 408.1058 | Total Loss: 408.1058 | Val Loss: 495.6089 | Val Qini: 0.8633 | EMA Qini: 0.8611 | Best EMA: 0.8611 ⭐ NEW BEST EMA
Epoch 43/150 | Base Loss: 377.6827 | Total Loss: 377.6827 | Val Loss: 495.6047 | Val Qini: 0.8624 | EMA Qini: 0.8614 | Best EMA: 0.8614 ⭐ NEW BEST EMA
Epoch 44/150 | Base Loss: 465.2538 | Total Loss: 465.2538 | Val Loss: 495.6031 | Val Qini: 0.8638 | EMA Qini: 0.8620 | Best EMA: 0.8620 ⭐ NEW BEST EMA
Epoch 45/150 | Base Loss: 426.7314 | Total Loss: 426.7314 | Val Loss: 495.6013 | Val Qini: 0.8637 | EMA Qini: 0.8624 | Best EMA: 0.8624 ⭐ NEW BEST EMA
Epoch 46/150 | Base Loss: 471.3488 | Total Loss: 471.3488 | Val Loss: 495.6001 | Val Qini: 0.8638 | EMA Qini: 0.8628 | Best EMA: 0.8628 ⭐ NEW BEST EMA
Epoch 47/150 | Base Loss: 352.5073 | Total Loss: 352.5073 | Val Loss: 495.5993 | Val Qini: 0.8643 | EMA Qini: 0.8632 | Best EMA: 0.8632 ⭐ NEW BEST EMA
Epoch 48/150 | Base Loss: 437.1755 | Total Loss: 437.1755 | Val Loss: 495.5987 | Val Qini: 0.8642 | EMA Qini: 0.8634 | Best EMA: 0.8634 ⭐ NEW BEST EMA
Epoch 49/150 | Base Loss: 566.0372 | Total Loss: 566.0372 | Val Loss: 495.5988 | Val Qini: 0.8650 | EMA Qini: 0.8638 | Best EMA: 0.8638 ⭐ NEW BEST EMA
Epoch 50/150 | Base Loss: 518.4736 | Total Loss: 518.4736 | Val Loss: 495.5992 | Val Qini: 0.8646 | EMA Qini: 0.8640 | Best EMA: 0.8640 ⭐ NEW BEST EMA
Epoch 51/150 | Base Loss: 504.9501 | Total Loss: 504.9501 | Val Loss: 495.5994 | Val Qini: 0.8647 | EMA Qini: 0.8642 | Best EMA: 0.8642 ⭐ NEW BEST EMA
Epoch 52/150 | Base Loss: 539.2609 | Total Loss: 539.2609 | Val Loss: 495.5981 | Val Qini: 0.8661 | EMA Qini: 0.8647 | Best EMA: 0.8647 ⭐ NEW BEST EMA
Epoch 53/150 | Base Loss: 384.8116 | Total Loss: 384.8116 | Val Loss: 495.5959 | Val Qini: 0.8662 | EMA Qini: 0.8651 | Best EMA: 0.8651 ⭐ NEW BEST EMA
Epoch 54/150 | Base Loss: 338.1342 | Total Loss: 338.1342 | Val Loss: 495.5948 | Val Qini: 0.8648 | EMA Qini: 0.8650 | Best EMA: 0.8651 (patience: 1/20)
Epoch 55/150 | Base Loss: 535.5151 | Total Loss: 535.5151 | Val Loss: 495.5932 | Val Qini: 0.8644 | EMA Qini: 0.8648 | Best EMA: 0.8651 (patience: 2/20)
Epoch 56/150 | Base Loss: 456.3892 | Total Loss: 456.3892 | Val Loss: 495.5915 | Val Qini: 0.8648 | EMA Qini: 0.8648 | Best EMA: 0.8651 (patience: 3/20)
Epoch 57/150 | Base Loss: 527.2423 | Total Loss: 527.2423 | Val Loss: 495.5907 | Val Qini: 0.8647 | EMA Qini: 0.8648 | Best EMA: 0.8651 (patience: 4/20)
Epoch 58/150 | Base Loss: 386.3932 | Total Loss: 386.3932 | Val Loss: 495.5900 | Val Qini: 0.8647 | EMA Qini: 0.8648 | Best EMA: 0.8651 (patience: 5/20)
Epoch 59/150 | Base Loss: 438.1498 | Total Loss: 438.1498 | Val Loss: 495.5888 | Val Qini: 0.8657 | EMA Qini: 0.8650 | Best EMA: 0.8651 (patience: 6/20)
Epoch 60/150 | Base Loss: 435.9119 | Total Loss: 435.9119 | Val Loss: 495.5877 | Val Qini: 0.8655 | EMA Qini: 0.8651 | Best EMA: 0.8651 ⭐ NEW BEST EMA
Epoch 61/150 | Base Loss: 559.4684 | Total Loss: 559.4684 | Val Loss: 495.5869 | Val Qini: 0.8655 | EMA Qini: 0.8652 | Best EMA: 0.8652 ⭐ NEW BEST EMA
Epoch 62/150 | Base Loss: 664.4054 | Total Loss: 664.4054 | Val Loss: 495.5858 | Val Qini: 0.8655 | EMA Qini: 0.8653 | Best EMA: 0.8653 ⭐ NEW BEST EMA
Epoch 63/150 | Base Loss: 383.9333 | Total Loss: 383.9333 | Val Loss: 495.5845 | Val Qini: 0.8655 | EMA Qini: 0.8654 | Best EMA: 0.8654 ⭐ NEW BEST EMA
Epoch 64/150 | Base Loss: 418.2821 | Total Loss: 418.2821 | Val Loss: 495.5832 | Val Qini: 0.8655 | EMA Qini: 0.8654 | Best EMA: 0.8654 ⭐ NEW BEST EMA
Epoch 65/150 | Base Loss: 695.4417 | Total Loss: 695.4417 | Val Loss: 495.5826 | Val Qini: 0.8658 | EMA Qini: 0.8655 | Best EMA: 0.8655 ⭐ NEW BEST EMA
Epoch 66/150 | Base Loss: 395.0364 | Total Loss: 395.0364 | Val Loss: 495.5818 | Val Qini: 0.8664 | EMA Qini: 0.8657 | Best EMA: 0.8657 ⭐ NEW BEST EMA
Epoch 67/150 | Base Loss: 608.6605 | Total Loss: 608.6605 | Val Loss: 495.5809 | Val Qini: 0.8664 | EMA Qini: 0.8659 | Best EMA: 0.8659 ⭐ NEW BEST EMA
Epoch 68/150 | Base Loss: 424.2422 | Total Loss: 424.2422 | Val Loss: 495.5806 | Val Qini: 0.8664 | EMA Qini: 0.8660 | Best EMA: 0.8660 ⭐ NEW BEST EMA
Epoch 69/150 | Base Loss: 553.7011 | Total Loss: 553.7011 | Val Loss: 495.5802 | Val Qini: 0.8671 | EMA Qini: 0.8663 | Best EMA: 0.8663 ⭐ NEW BEST EMA
Epoch 70/150 | Base Loss: 472.9070 | Total Loss: 472.9070 | Val Loss: 495.5799 | Val Qini: 0.8672 | EMA Qini: 0.8665 | Best EMA: 0.8665 ⭐ NEW BEST EMA
Epoch 71/150 | Base Loss: 493.8568 | Total Loss: 493.8568 | Val Loss: 495.5798 | Val Qini: 0.8670 | EMA Qini: 0.8666 | Best EMA: 0.8666 ⭐ NEW BEST EMA
Epoch 72/150 | Base Loss: 561.8025 | Total Loss: 561.8025 | Val Loss: 495.5796 | Val Qini: 0.8670 | EMA Qini: 0.8667 | Best EMA: 0.8667 ⭐ NEW BEST EMA
Epoch 73/150 | Base Loss: 541.2338 | Total Loss: 541.2338 | Val Loss: 495.5794 | Val Qini: 0.8670 | EMA Qini: 0.8668 | Best EMA: 0.8668 ⭐ NEW BEST EMA
Epoch 74/150 | Base Loss: 546.4956 | Total Loss: 546.4956 | Val Loss: 495.5789 | Val Qini: 0.8670 | EMA Qini: 0.8668 | Best EMA: 0.8668 ⭐ NEW BEST EMA
Epoch 75/150 | Base Loss: 482.0541 | Total Loss: 482.0541 | Val Loss: 495.5786 | Val Qini: 0.8670 | EMA Qini: 0.8669 | Best EMA: 0.8669 ⭐ NEW BEST EMA
Epoch 76/150 | Base Loss: 304.1984 | Total Loss: 304.1984 | Val Loss: 495.5779 | Val Qini: 0.8670 | EMA Qini: 0.8669 | Best EMA: 0.8669 ⭐ NEW BEST EMA
Epoch 77/150 | Base Loss: 485.2396 | Total Loss: 485.2396 | Val Loss: 495.5772 | Val Qini: 0.8670 | EMA Qini: 0.8669 | Best EMA: 0.8669 ⭐ NEW BEST EMA
Epoch 78/150 | Base Loss: 293.9622 | Total Loss: 293.9622 | Val Loss: 495.5765 | Val Qini: 0.8670 | EMA Qini: 0.8669 | Best EMA: 0.8669 ⭐ NEW BEST EMA
Epoch 79/150 | Base Loss: 370.6159 | Total Loss: 370.6159 | Val Loss: 495.5763 | Val Qini: 0.8670 | EMA Qini: 0.8670 | Best EMA: 0.8670 ⭐ NEW BEST EMA
Epoch 80/150 | Base Loss: 646.3056 | Total Loss: 646.3056 | Val Loss: 495.5761 | Val Qini: 0.8670 | EMA Qini: 0.8670 | Best EMA: 0.8670 ⭐ NEW BEST EMA
Epoch 81/150 | Base Loss: 651.1103 | Total Loss: 651.1103 | Val Loss: 495.5758 | Val Qini: 0.8670 | EMA Qini: 0.8670 | Best EMA: 0.8670 ⭐ NEW BEST EMA
Epoch 82/150 | Base Loss: 395.7747 | Total Loss: 395.7747 | Val Loss: 495.5757 | Val Qini: 0.8670 | EMA Qini: 0.8670 | Best EMA: 0.8670 ⭐ NEW BEST EMA
Epoch 83/150 | Base Loss: 533.4355 | Total Loss: 533.4355 | Val Loss: 495.5755 | Val Qini: 0.8670 | EMA Qini: 0.8670 | Best EMA: 0.8670 ⭐ NEW BEST EMA
Epoch 84/150 | Base Loss: 436.0603 | Total Loss: 436.0603 | Val Loss: 495.5753 | Val Qini: 0.8670 | EMA Qini: 0.8670 | Best EMA: 0.8670 (patience: 1/20)
Epoch 85/150 | Base Loss: 567.5741 | Total Loss: 567.5741 | Val Loss: 495.5752 | Val Qini: 0.8670 | EMA Qini: 0.8670 | Best EMA: 0.8670 (patience: 2/20)
Epoch 86/150 | Base Loss: 448.4622 | Total Loss: 448.4622 | Val Loss: 495.5750 | Val Qini: 0.8672 | EMA Qini: 0.8670 | Best EMA: 0.8670 ⭐ NEW BEST EMA
Epoch 87/150 | Base Loss: 566.6281 | Total Loss: 566.6281 | Val Loss: 495.5749 | Val Qini: 0.8672 | EMA Qini: 0.8671 | Best EMA: 0.8671 ⭐ NEW BEST EMA
Epoch 88/150 | Base Loss: 419.1392 | Total Loss: 419.1392 | Val Loss: 495.5748 | Val Qini: 0.8672 | EMA Qini: 0.8671 | Best EMA: 0.8671 ⭐ NEW BEST EMA
Epoch 89/150 | Base Loss: 586.8487 | Total Loss: 586.8487 | Val Loss: 495.5745 | Val Qini: 0.8672 | EMA Qini: 0.8671 | Best EMA: 0.8671 ⭐ NEW BEST EMA
Epoch 90/150 | Base Loss: 388.4617 | Total Loss: 388.4617 | Val Loss: 495.5744 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8672 ⭐ NEW BEST EMA
Epoch 91/150 | Base Loss: 557.2221 | Total Loss: 557.2221 | Val Loss: 495.5743 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8672 ⭐ NEW BEST EMA
Epoch 92/150 | Base Loss: 801.7048 | Total Loss: 801.7048 | Val Loss: 495.5742 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8672 ⭐ NEW BEST EMA
Epoch 93/150 | Base Loss: 416.9167 | Total Loss: 416.9167 | Val Loss: 495.5742 | Val Qini: 0.8668 | EMA Qini: 0.8671 | Best EMA: 0.8672 (patience: 1/20)
Epoch 94/150 | Base Loss: 323.8066 | Total Loss: 323.8066 | Val Loss: 495.5740 | Val Qini: 0.8674 | EMA Qini: 0.8672 | Best EMA: 0.8672 (patience: 2/20)
Epoch 95/150 | Base Loss: 483.0452 | Total Loss: 483.0452 | Val Loss: 495.5740 | Val Qini: 0.8674 | EMA Qini: 0.8672 | Best EMA: 0.8672 ⭐ NEW BEST EMA
Epoch 96/150 | Base Loss: 431.4394 | Total Loss: 431.4394 | Val Loss: 495.5739 | Val Qini: 0.8674 | EMA Qini: 0.8673 | Best EMA: 0.8673 ⭐ NEW BEST EMA
Epoch 97/150 | Base Loss: 640.3198 | Total Loss: 640.3198 | Val Loss: 495.5739 | Val Qini: 0.8674 | EMA Qini: 0.8673 | Best EMA: 0.8673 ⭐ NEW BEST EMA
Epoch 98/150 | Base Loss: 426.1648 | Total Loss: 426.1648 | Val Loss: 495.5739 | Val Qini: 0.8670 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 1/20)
Epoch 99/150 | Base Loss: 175.8143 | Total Loss: 175.8143 | Val Loss: 495.5738 | Val Qini: 0.8669 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 2/20)
Epoch 100/150 | Base Loss: 397.6521 | Total Loss: 397.6521 | Val Loss: 495.5738 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 3/20)
Epoch 101/150 | Base Loss: 386.3293 | Total Loss: 386.3293 | Val Loss: 495.5737 | Val Qini: 0.8676 | EMA Qini: 0.8673 | Best EMA: 0.8673 (patience: 4/20)
Epoch 102/150 | Base Loss: 406.2401 | Total Loss: 406.2401 | Val Loss: 495.5737 | Val Qini: 0.8675 | EMA Qini: 0.8673 | Best EMA: 0.8673 ⭐ NEW BEST EMA
Epoch 103/150 | Base Loss: 453.3914 | Total Loss: 453.3914 | Val Loss: 495.5737 | Val Qini: 0.8670 | EMA Qini: 0.8673 | Best EMA: 0.8673 (patience: 1/20)
Epoch 104/150 | Base Loss: 626.5278 | Total Loss: 626.5278 | Val Loss: 495.5737 | Val Qini: 0.8671 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 2/20)
Epoch 105/150 | Base Loss: 590.2474 | Total Loss: 590.2474 | Val Loss: 495.5737 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 3/20)
Epoch 106/150 | Base Loss: 374.2328 | Total Loss: 374.2328 | Val Loss: 495.5737 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 4/20)
Epoch 107/150 | Base Loss: 589.0876 | Total Loss: 589.0876 | Val Loss: 495.5737 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 5/20)
Epoch 108/150 | Base Loss: 322.4961 | Total Loss: 322.4961 | Val Loss: 495.5736 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 6/20)
Epoch 109/150 | Base Loss: 658.0599 | Total Loss: 658.0599 | Val Loss: 495.5735 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 7/20)
Epoch 110/150 | Base Loss: 323.5468 | Total Loss: 323.5468 | Val Loss: 495.5735 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 8/20)
Epoch 111/150 | Base Loss: 511.6271 | Total Loss: 511.6271 | Val Loss: 495.5734 | Val Qini: 0.8672 | EMA Qini: 0.8672 | Best EMA: 0.8673 (patience: 9/20)
Epoch 112/150 | Base Loss: 515.6110 | Total Loss: 515.6110 | Val Loss: 495.5733 | Val Qini: 0.8676 | EMA Qini: 0.8673 | Best EMA: 0.8673 (patience: 10/20)
Epoch 113/150 | Base Loss: 544.2056 | Total Loss: 544.2056 | Val Loss: 495.5732 | Val Qini: 0.8676 | EMA Qini: 0.8674 | Best EMA: 0.8674 ⭐ NEW BEST EMA
Epoch 114/150 | Base Loss: 471.2465 | Total Loss: 471.2465 | Val Loss: 495.5731 | Val Qini: 0.8676 | EMA Qini: 0.8674 | Best EMA: 0.8674 ⭐ NEW BEST EMA
Epoch 115/150 | Base Loss: 447.3680 | Total Loss: 447.3680 | Val Loss: 495.5731 | Val Qini: 0.8676 | EMA Qini: 0.8675 | Best EMA: 0.8675 ⭐ NEW BEST EMA
Epoch 116/150 | Base Loss: 286.0988 | Total Loss: 286.0988 | Val Loss: 495.5731 | Val Qini: 0.8676 | EMA Qini: 0.8675 | Best EMA: 0.8675 ⭐ NEW BEST EMA
Epoch 117/150 | Base Loss: 303.8440 | Total Loss: 303.8440 | Val Loss: 495.5730 | Val Qini: 0.8676 | EMA Qini: 0.8675 | Best EMA: 0.8675 ⭐ NEW BEST EMA
Epoch 118/150 | Base Loss: 510.2763 | Total Loss: 510.2763 | Val Loss: 495.5730 | Val Qini: 0.8676 | EMA Qini: 0.8676 | Best EMA: 0.8676 ⭐ NEW BEST EMA
Epoch 119/150 | Base Loss: 392.7905 | Total Loss: 392.7905 | Val Loss: 495.5729 | Val Qini: 0.8676 | EMA Qini: 0.8676 | Best EMA: 0.8676 ⭐ NEW BEST EMA
Epoch 120/150 | Base Loss: 526.4083 | Total Loss: 526.4083 | Val Loss: 495.5729 | Val Qini: 0.8675 | EMA Qini: 0.8676 | Best EMA: 0.8676 (patience: 1/20)
Epoch 121/150 | Base Loss: 385.1176 | Total Loss: 385.1176 | Val Loss: 495.5728 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 2/20)
Epoch 122/150 | Base Loss: 506.1865 | Total Loss: 506.1865 | Val Loss: 495.5728 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 3/20)
Epoch 123/150 | Base Loss: 594.8682 | Total Loss: 594.8682 | Val Loss: 495.5728 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 4/20)
Epoch 124/150 | Base Loss: 472.4596 | Total Loss: 472.4596 | Val Loss: 495.5728 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 5/20)
Epoch 125/150 | Base Loss: 385.9241 | Total Loss: 385.9241 | Val Loss: 495.5727 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 6/20)
Epoch 126/150 | Base Loss: 479.9388 | Total Loss: 479.9388 | Val Loss: 495.5727 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 7/20)
Epoch 127/150 | Base Loss: 445.1023 | Total Loss: 445.1023 | Val Loss: 495.5727 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 8/20)
Epoch 128/150 | Base Loss: 487.6923 | Total Loss: 487.6923 | Val Loss: 495.5726 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 9/20)
Epoch 129/150 | Base Loss: 472.5231 | Total Loss: 472.5231 | Val Loss: 495.5725 | Val Qini: 0.8675 | EMA Qini: 0.8675 | Best EMA: 0.8676 (patience: 10/20)