In [1]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/RERUM")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
sys.path.append("..")
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [2]:
%time train_df = pd.read_csv(r"../dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"../dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"../dataset/Hillstrom/Men/val_men.csv")

CPU times: user 25.5 ms, sys: 4.05 ms, total: 29.5 ms
Wall time: 29 ms
CPU times: user 11 ms, sys: 5 ms, total: 16 ms
Wall time: 16 ms
CPU times: user 5.46 ms, sys: 938 μs, total: 6.4 ms
Wall time: 6.4 ms

In [3]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [4]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [5]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [6]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [7]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [8]:
epochs = 150
early_stop_metric = "loss"
ema = True
ema_alpha = 0.25
patience = 20
shared_dropout = 0.0
outcome_dropout = 0
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
uplift_ranking = 0
response_ranking = 0
print (f" epochs = {epochs}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 early stop = loss
 use ema = True
 ema alpha = 0.25
 patience = 20
 early stop start = 30

In [ ]:
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 1e-5, 3e-4, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-2, log=True)
    grid_outcome_dropout = trial.suggest_float("outcome_dropout", 0.0, 0.5)
    grid_shared_dropout = trial.suggest_float("shared_dropout", 0.0, 0.5)
    grid_outcome_hidden = trial.suggest_int("outcome_hidden", 50, 400, step=50)
    grid_shared_hidden = trial.suggest_int("shared_hidden", 50, 400, step=50)

    val_auqc_list = []
    val_ate_err_list = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=grid_shared_hidden,
            outcome_hidden=grid_outcome_hidden,
            outcome_dropout=grid_outcome_dropout,
            shared_dropout=grid_shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
        )

        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_men_test_t_on_device = x_men_test_t.to(device)
        y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

        uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
        y_true = y_men_test_t.detach().cpu().numpy().flatten()
        t_true = t_men_test_t.detach().cpu().numpy().flatten()
        
        current_val_auqc = auqc(y_true, t_true, uplift_pred, bins=100, plot=False)
        ate_pred = uplift_pred.mean()
        ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
        current_val_ate_err = abs(ate_pred - ate_true)

        val_auqc_list.append(current_val_auqc)
        val_ate_err_list.append(current_val_ate_err)

    # Calculate aggregated metrics across the 5 validation seeds
    mean_auqc = float(np.mean(val_auqc_list))
    std_auqc = float(np.std(val_auqc_list))
    mean_ate_err = float(np.mean(val_ate_err_list))

    # Apply penalty for instability and miscalibration
    penalty_std = std_auqc * 1.0
    penalty_ate = mean_ate_err * 0.05

    final_score = mean_auqc - penalty_std - penalty_ate

    trial.set_user_attr("mean_val_auqc", mean_auqc)
    trial.set_user_attr("std_Val_auqc", std_auqc)
    trial.set_user_attr("mean_val_ate_err", mean_ate_err)
    trial.set_user_attr("final_score", final_score)
    return final_score

def print_trial_callback(study, trial):
    value = float(trial.value) if trial.value is not None else float("nan")
    best_trial = study.best_trial
    best_value = float(best_trial.value) if best_trial.value is not None else float("nan")
    print(
        f"Finished trial {trial.number}: val loss: {value:.4f} - "
        f"with hyperparameters: {trial.params} | "
        f"best trial: {best_trial.number} loss: {best_value:.4f}",
        flush=True
    )

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True, callbacks=[print_trial_callback])

trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": round(float(t.params["lr"]), 4),
        "weight_decay": round(float(t.params["weight_decay"]), 4),
        "shared_hidden": int(t.params["shared_hidden"]),
        "outcome_hidden": int(t.params["outcome_hidden"]),
        "shared_dropout": round(float(t.params["shared_dropout"]), 3),
        "outcome_dropout": round(float(t.params["outcome_dropout"]), 3),
        "mean_val_auqc": float(t.value),
        "std_Val_auqc": float(t.user_attrs.get("std_Val_auqc", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_val_auqc", ascending=True).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "shared_hidden": int(best_params["shared_hidden"]),
    "outcome_hidden": int(best_params["outcome_hidden"]),
    "shared_dropout": float(best_params["shared_dropout"]),
    "outcome_dropout": float(best_params["outcome_dropout"]),
    "mean_Val_auqc": float(study.best_value),
    "std_Val_auqc": float(study.best_trial.user_attrs.get("std_Val_auqc", np.nan))
})``

/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
  0%|          | 0/50 [00:00<?, ?it/s]

Finished trial 0: val Loss: 494.907507 - with hyperparameters: {'lr': 0.00015006912017686197, 'weight_decay': 2.3884552609633584e-05, 'outcome_dropout': 0.2041371296334657, 'shared_dropout': 0.2216925330468017, 'outcome_hidden': 250, 'shared_hidden': 350} | best trial: 0 Loss: 494.907507

Best trial: 0. Best value: 494.908:   2%|▏         | 1/50 [01:18<1:03:45, 78.06s/it]

Finished trial 1: val Loss: 495.168927 - with hyperparameters: {'lr': 0.00043025465630583485, 'weight_decay': 9.52546685451366e-05, 'outcome_dropout': 0.29511631137958266, 'shared_dropout': 0.369412397917029, 'outcome_hidden': 350, 'shared_hidden': 150} | best trial: 0 Loss: 494.907507

Best trial: 0. Best value: 494.908:   4%|▍         | 2/50 [02:30<59:36, 74.52s/it]

Finished trial 2: val Loss: 495.035461 - with hyperparameters: {'lr': 0.00013064516400914498, 'weight_decay': 1.4849237750214059e-05, 'outcome_dropout': 0.10786555667219, 'shared_dropout': 0.33395193641300147, 'outcome_hidden': 350, 'shared_hidden': 250} | best trial: 0 Loss: 494.907507

Best trial: 0. Best value: 494.908:   6%|▌         | 3/50 [04:13<1:08:52, 87.92s/it]

Finished trial 3: val Loss: 494.918964 - with hyperparameters: {'lr': 0.00019247010007262055, 'weight_decay': 3.283818020859842e-05, 'outcome_dropout': 0.2613110440775303, 'shared_dropout': 0.299393430173892, 'outcome_hidden': 300, 'shared_hidden': 300} | best trial: 0 Loss: 494.907507

Best trial: 0. Best value: 494.908:   8%|▊         | 4/50 [05:36<1:05:51, 85.91s/it]

Finished trial 4: val Loss: 495.339917 - with hyperparameters: {'lr': 0.0002973589597623869, 'weight_decay': 2.251587423515786e-05, 'outcome_dropout': 0.01370644680148092, 'shared_dropout': 0.35647536041824224, 'outcome_hidden': 350, 'shared_hidden': 100} | best trial: 0 Loss: 494.907507

Best trial: 0. Best value: 494.908:  10%|█         | 5/50 [07:04<1:04:55, 86.56s/it]

Finished trial 5: val Loss: 494.805261 - with hyperparameters: {'lr': 0.00039113022808842586, 'weight_decay': 2.560408643824531e-05, 'outcome_dropout': 0.08545516508355222, 'shared_dropout': 0.14723337668580588, 'outcome_hidden': 250, 'shared_hidden': 350} | best trial: 5 Loss: 494.805261

Best trial: 5. Best value: 494.805:  12%|█▏        | 6/50 [07:55<54:37, 74.49s/it]

Finished trial 6: val Loss: 494.868036 - with hyperparameters: {'lr': 0.00021838287274388984, 'weight_decay': 3.2001115759103645e-05, 'outcome_dropout': 0.3277017809120966, 'shared_dropout': 0.09709158836045251, 'outcome_hidden': 350, 'shared_hidden': 150} | best trial: 5 Loss: 494.805261

Best trial: 5. Best value: 494.805:  14%|█▍        | 7/50 [09:10<53:28, 74.62s/it]

Finished trial 7: val Loss: 494.998450 - with hyperparameters: {'lr': 0.00014628116480793656, 'weight_decay': 8.973244662799929e-05, 'outcome_dropout': 0.22728212392032476, 'shared_dropout': 0.09606758791930864, 'outcome_hidden': 200, 'shared_hidden': 200} | best trial: 5 Loss: 494.805261

Best trial: 5. Best value: 494.805:  16%|█▌        | 8/50 [10:46<56:57, 81.38s/it]

Finished trial 8: val Loss: 494.896631 - with hyperparameters: {'lr': 0.0001842312281105819, 'weight_decay': 3.196367765376636e-05, 'outcome_dropout': 0.11911251517980004, 'shared_dropout': 0.2576010310834246, 'outcome_hidden': 50, 'shared_hidden': 150} | best trial: 5 Loss: 494.805261

Best trial: 5. Best value: 494.805:  18%|█▊        | 9/50 [13:11<1:09:08, 101.19s/it]

Finished trial 9: val Loss: 494.862067 - with hyperparameters: {'lr': 0.0002083346159867299, 'weight_decay': 2.2272741555350945e-05, 'outcome_dropout': 0.4646573494713398, 'shared_dropout': 0.005304115836440082, 'outcome_hidden': 100, 'shared_hidden': 200} | best trial: 5 Loss: 494.805261

Best trial: 5. Best value: 494.805:  20%|██        | 10/50 [14:39<1:04:47, 97.19s/it]

Finished trial 10: val Loss: 495.169934 - with hyperparameters: {'lr': 6.917138866786096e-05, 'weight_decay': 5.531580515619867e-05, 'outcome_dropout': 0.004457084708398867, 'shared_dropout': 0.4985212367923584, 'outcome_hidden': 150, 'shared_hidden': 400} | best trial: 5 Loss: 494.805261

Best trial: 5. Best value: 494.805:  22%|██▏       | 11/50 [17:34<1:18:44, 121.13s/it]

Finished trial 11: val Loss: 494.846094 - with hyperparameters: {'lr': 0.00048667727442250396, 'weight_decay': 1.12723208960615e-05, 'outcome_dropout': 0.40948472869292696, 'shared_dropout': 0.028589144343436224, 'outcome_hidden': 100, 'shared_hidden': 250} | best trial: 5 Loss: 494.805261

Best trial: 5. Best value: 494.805:  24%|██▍       | 12/50 [18:34<1:04:53, 102.46s/it]

Finished trial 12: val Loss: 494.737305 - with hyperparameters: {'lr': 0.0004486199459067608, 'weight_decay': 1.0046751242303395e-05, 'outcome_dropout': 0.449976915058382, 'shared_dropout': 0.1355787633459325, 'outcome_hidden': 200, 'shared_hidden': 300} | best trial: 12 Loss: 494.737305

Best trial: 12. Best value: 494.737:  26%|██▌       | 13/50 [19:33<54:59, 89.18s/it]

Finished trial 13: val Loss: 494.763397 - with hyperparameters: {'lr': 0.00033114830366596235, 'weight_decay': 1.0344142329583511e-05, 'outcome_dropout': 0.3757596872572938, 'shared_dropout': 0.1625984668535295, 'outcome_hidden': 250, 'shared_hidden': 400} | best trial: 12 Loss: 494.737305

Best trial: 12. Best value: 494.737:  28%|██▊       | 14/50 [20:29<47:33, 79.25s/it]

Finished trial 14: val Loss: 494.774762 - with hyperparameters: {'lr': 0.00029992804929702906, 'weight_decay': 1.0387994619621553e-05, 'outcome_dropout': 0.3872108878944739, 'shared_dropout': 0.18427796139429847, 'outcome_hidden': 200, 'shared_hidden': 400} | best trial: 12 Loss: 494.737305

Best trial: 12. Best value: 494.737:  30%|███       | 15/50 [21:38<44:24, 76.12s/it]

Finished trial 15: val Loss: 494.793353 - with hyperparameters: {'lr': 0.00030502212495572687, 'weight_decay': 1.5361518399117304e-05, 'outcome_dropout': 0.4692114127984072, 'shared_dropout': 0.12049052105863989, 'outcome_hidden': 150, 'shared_hidden': 300} | best trial: 12 Loss: 494.737305

Best trial: 12. Best value: 494.737:  32%|███▏      | 16/50 [22:50<42:25, 74.88s/it]

Finished trial 16: val Loss: 494.908124 - with hyperparameters: {'lr': 9.695733473867912e-05, 'weight_decay': 1.5046319370186031e-05, 'outcome_dropout': 0.37430767635874457, 'shared_dropout': 0.19250314726713652, 'outcome_hidden': 300, 'shared_hidden': 350} | best trial: 12 Loss: 494.737305

Best trial: 12. Best value: 494.737:  34%|███▍      | 17/50 [24:48<48:20, 87.90s/it]

Finished trial 17: val Loss: 494.774554 - with hyperparameters: {'lr': 0.0003640110584901956, 'weight_decay': 1.249500439725999e-05, 'outcome_dropout': 0.4850168107678875, 'shared_dropout': 0.05842026680686985, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 12 Loss: 494.737305

Best trial: 12. Best value: 494.737:  36%|███▌      | 18/50 [25:41<41:20, 77.52s/it]

Finished trial 18: val Loss: 494.923846 - with hyperparameters: {'lr': 0.00026083121035526033, 'weight_decay': 4.6986009640042224e-05, 'outcome_dropout': 0.4223176284612274, 'shared_dropout': 0.15372311193829838, 'outcome_hidden': 150, 'shared_hidden': 50} | best trial: 12 Loss: 494.737305

Best trial: 12. Best value: 494.737:  38%|███▊      | 19/50 [27:55<48:44, 94.35s/it]

Finished trial 19: val Loss: 494.721100 - with hyperparameters: {'lr': 0.00048544926902417256, 'weight_decay': 1.724346466803098e-05, 'outcome_dropout': 0.336584283967607, 'shared_dropout': 0.2546804270667028, 'outcome_hidden': 250, 'shared_hidden': 400} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  40%|████      | 20/50 [28:47<40:51, 81.71s/it]

Finished trial 20: val Loss: 494.912299 - with hyperparameters: {'lr': 0.0004797841603260072, 'weight_decay': 1.8018049362713494e-05, 'outcome_dropout': 0.3397647449264437, 'shared_dropout': 0.4465148822509617, 'outcome_hidden': 200, 'shared_hidden': 350} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  42%|████▏     | 21/50 [29:55<37:31, 77.65s/it]

Finished trial 21: val Loss: 494.780743 - with hyperparameters: {'lr': 0.0003640304012397745, 'weight_decay': 1.2968187917192546e-05, 'outcome_dropout': 0.3510664826999657, 'shared_dropout': 0.2580977081869006, 'outcome_hidden': 250, 'shared_hidden': 400} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  44%|████▍     | 22/50 [30:56<33:49, 72.48s/it]

Finished trial 22: val Loss: 494.817950 - with hyperparameters: {'lr': 0.0004995602843802623, 'weight_decay': 1.0036255724934674e-05, 'outcome_dropout': 0.43115552392407613, 'shared_dropout': 0.21079187309096803, 'outcome_hidden': 300, 'shared_hidden': 400} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  46%|████▌     | 23/50 [31:46<29:35, 65.75s/it]

Finished trial 23: val Loss: 494.794690 - with hyperparameters: {'lr': 0.00035899654617035156, 'weight_decay': 1.8355446844916625e-05, 'outcome_dropout': 0.3134360140224296, 'shared_dropout': 0.27178327450201567, 'outcome_hidden': 250, 'shared_hidden': 300} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  48%|████▊     | 24/50 [32:46<27:49, 64.23s/it]

Finished trial 24: val Loss: 494.783551 - with hyperparameters: {'lr': 0.0002691527351738739, 'weight_decay': 1.7759468675476396e-05, 'outcome_dropout': 0.2742846949579582, 'shared_dropout': 0.1575718131414474, 'outcome_hidden': 200, 'shared_hidden': 350} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  50%|█████     | 25/50 [33:54<27:10, 65.24s/it]

Finished trial 25: val Loss: 494.833392 - with hyperparameters: {'lr': 0.0004232052725357424, 'weight_decay': 1.3061587793320518e-05, 'outcome_dropout': 0.18866594694291697, 'shared_dropout': 0.06851235101603499, 'outcome_hidden': 300, 'shared_hidden': 400} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  52%|█████▏    | 26/50 [34:45<24:21, 60.90s/it]

Finished trial 26: val Loss: 494.965527 - with hyperparameters: {'lr': 0.00024447267655644376, 'weight_decay': 1.001916024104725e-05, 'outcome_dropout': 0.43875643496333944, 'shared_dropout': 0.30645322865251, 'outcome_hidden': 250, 'shared_hidden': 250} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  54%|█████▍    | 27/50 [36:03<25:16, 65.94s/it]

Finished trial 27: val Loss: 494.878339 - with hyperparameters: {'lr': 0.0003220744531427523, 'weight_decay': 1.1968801930681456e-05, 'outcome_dropout': 0.37141135314399465, 'shared_dropout': 0.4031280273850107, 'outcome_hidden': 200, 'shared_hidden': 350} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  56%|█████▌    | 28/50 [37:17<25:10, 68.65s/it]

Finished trial 28: val Loss: 494.785944 - with hyperparameters: {'lr': 0.0004168313028066064, 'weight_decay': 1.5281477243112774e-05, 'outcome_dropout': 0.4960458204014826, 'shared_dropout': 0.22656042607332777, 'outcome_hidden': 150, 'shared_hidden': 400} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  58%|█████▊    | 29/50 [38:21<23:28, 67.05s/it]

Finished trial 29: val Loss: 495.023743 - with hyperparameters: {'lr': 5.276874242725332e-05, 'weight_decay': 2.6847465364730386e-05, 'outcome_dropout': 0.19187721299888, 'shared_dropout': 0.22336213099443147, 'outcome_hidden': 250, 'shared_hidden': 300} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  60%|██████    | 30/50 [41:13<32:51, 98.57s/it]

Finished trial 30: val Loss: 494.941864 - with hyperparameters: {'lr': 0.00011545197789092311, 'weight_decay': 2.0566301832360496e-05, 'outcome_dropout': 0.4069208755461437, 'shared_dropout': 0.1205899594583972, 'outcome_hidden': 100, 'shared_hidden': 350} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  62%|██████▏   | 31/50 [42:57<31:46, 100.34s/it]

Finished trial 31: val Loss: 494.899017 - with hyperparameters: {'lr': 0.0003564360108656374, 'weight_decay': 1.2586287525791161e-05, 'outcome_dropout': 0.4963004434006122, 'shared_dropout': 0.04877888947331577, 'outcome_hidden': 400, 'shared_hidden': 250} | best trial: 19 Loss: 494.721100

Best trial: 19. Best value: 494.721:  64%|██████▍   | 32/50 [43:52<26:01, 86.76s/it]

Finished trial 32: val Loss: 494.719159 - with hyperparameters: {'lr': 0.00042391566537017565, 'weight_decay': 1.3627921855902366e-05, 'outcome_dropout': 0.4620581239328808, 'shared_dropout': 0.06791495656000361, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 32 Loss: 494.719159

Best trial: 32. Best value: 494.719:  66%|██████▌   | 33/50 [44:44<21:34, 76.16s/it]

Finished trial 33: val Loss: 494.823035 - with hyperparameters: {'lr': 0.00045133818361226295, 'weight_decay': 1.402655361855731e-05, 'outcome_dropout': 0.45074718872286235, 'shared_dropout': 0.17074006282076015, 'outcome_hidden': 300, 'shared_hidden': 350} | best trial: 32 Loss: 494.719159

Best trial: 32. Best value: 494.719:  68%|██████▊   | 34/50 [45:36<18:21, 68.86s/it]

Finished trial 34: val Loss: 494.701733 - with hyperparameters: {'lr': 0.0004170365149024803, 'weight_decay': 1.1251435954901905e-05, 'outcome_dropout': 0.3053645492986671, 'shared_dropout': 0.12051685797898237, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  70%|███████   | 35/50 [46:27<15:54, 63.66s/it]

Finished trial 35: val Loss: 494.902924 - with hyperparameters: {'lr': 0.00042207105090153347, 'weight_decay': 1.6751511986837582e-05, 'outcome_dropout': 0.2904422220730426, 'shared_dropout': 0.09151940997587531, 'outcome_hidden': 400, 'shared_hidden': 250} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  72%|███████▏  | 36/50 [47:20<14:04, 60.30s/it]

Finished trial 36: val Loss: 494.916986 - with hyperparameters: {'lr': 0.0004127283601505267, 'weight_decay': 1.1581712437741627e-05, 'outcome_dropout': 0.2225796646893276, 'shared_dropout': 0.1281622161879684, 'outcome_hidden': 350, 'shared_hidden': 200} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  74%|███████▍  | 37/50 [48:15<12:46, 58.92s/it]

Finished trial 37: val Loss: 494.897717 - with hyperparameters: {'lr': 0.0002707485795555576, 'weight_decay': 2.0216215802130415e-05, 'outcome_dropout': 0.31545952813357225, 'shared_dropout': 0.00017584728592121013, 'outcome_hidden': 350, 'shared_hidden': 300} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  76%|███████▌  | 38/50 [49:14<11:44, 58.68s/it]

Finished trial 38: val Loss: 494.712720 - with hyperparameters: {'lr': 0.00038504625371476794, 'weight_decay': 1.3660464778879767e-05, 'outcome_dropout': 0.234664269754397, 'shared_dropout': 0.07889875217110764, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  78%|███████▊  | 39/50 [50:05<10:22, 56.56s/it]

Finished trial 39: val Loss: 494.906146 - with hyperparameters: {'lr': 0.00017435087924993085, 'weight_decay': 2.5074375215255548e-05, 'outcome_dropout': 0.15491246202322267, 'shared_dropout': 0.08042864122393972, 'outcome_hidden': 400, 'shared_hidden': 250} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  80%|████████  | 40/50 [51:10<09:51, 59.16s/it]

Finished trial 40: val Loss: 494.827649 - with hyperparameters: {'lr': 0.0002267309889942603, 'weight_decay': 3.687191651632296e-05, 'outcome_dropout': 0.24418760925312236, 'shared_dropout': 0.03029010694525134, 'outcome_hidden': 350, 'shared_hidden': 150} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  82%|████████▏ | 41/50 [52:23<09:29, 63.28s/it]

Finished trial 41: val Loss: 494.716968 - with hyperparameters: {'lr': 0.00039103278058723377, 'weight_decay': 1.4061454878189945e-05, 'outcome_dropout': 0.2638148807937676, 'shared_dropout': 0.10912756861599239, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  84%|████████▍ | 42/50 [53:15<07:57, 59.71s/it]

Finished trial 42: val Loss: 494.704480 - with hyperparameters: {'lr': 0.00039274542643235433, 'weight_decay': 1.4428575962875556e-05, 'outcome_dropout': 0.24634286479847473, 'shared_dropout': 0.11222801457868728, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 34 Loss: 494.701733

Best trial: 34. Best value: 494.702:  86%|████████▌ | 43/50 [54:06<06:40, 57.22s/it]

Finished trial 43: val Loss: 494.698334 - with hyperparameters: {'lr': 0.00037878866852455317, 'weight_decay': 1.3850258905166982e-05, 'outcome_dropout': 0.16527671894777804, 'shared_dropout': 0.10391547088159996, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 43 Loss: 494.698334

Best trial: 43. Best value: 494.698:  88%|████████▊ | 44/50 [54:58<05:33, 55.51s/it]

Finished trial 44: val Loss: 494.723718 - with hyperparameters: {'lr': 0.00033601361602417256, 'weight_decay': 8.312103642191608e-05, 'outcome_dropout': 0.056874484651850965, 'shared_dropout': 0.10353606571242553, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 43 Loss: 494.698334

Best trial: 43. Best value: 494.698:  90%|█████████ | 45/50 [55:49<04:31, 54.36s/it]

Finished trial 45: val Loss: 494.896570 - with hyperparameters: {'lr': 0.0003794449471043194, 'weight_decay': 1.5891128323092296e-05, 'outcome_dropout': 0.15583232399526886, 'shared_dropout': 0.03538533093786235, 'outcome_hidden': 350, 'shared_hidden': 200} | best trial: 43 Loss: 494.698334

Best trial: 43. Best value: 494.698:  92%|█████████▏| 46/50 [56:45<03:38, 54.74s/it]

Finished trial 46: val Loss: 494.880304 - with hyperparameters: {'lr': 0.0002878958205587079, 'weight_decay': 1.4141616342357408e-05, 'outcome_dropout': 0.2532053911828105, 'shared_dropout': 0.10999285937564038, 'outcome_hidden': 400, 'shared_hidden': 250} | best trial: 43 Loss: 494.698334

Best trial: 43. Best value: 494.698:  94%|█████████▍| 47/50 [57:43<02:47, 55.77s/it]

Finished trial 47: val Loss: 494.813824 - with hyperparameters: {'lr': 0.00038763085874560764, 'weight_decay': 1.12257034055663e-05, 'outcome_dropout': 0.2163109659925067, 'shared_dropout': 0.13736264742322313, 'outcome_hidden': 350, 'shared_hidden': 250} | best trial: 43 Loss: 494.698334

Best trial: 43. Best value: 494.698:  96%|█████████▌| 48/50 [58:37<01:50, 55.24s/it]

Finished trial 48: val Loss: 494.741046 - with hyperparameters: {'lr': 0.00033486722569447226, 'weight_decay': 2.0521931649936402e-05, 'outcome_dropout': 0.14922678674345613, 'shared_dropout': 0.08377976312326844, 'outcome_hidden': 400, 'shared_hidden': 300} | best trial: 43 Loss: 494.698334

Best trial: 43. Best value: 494.698:  98%|█████████▊| 49/50 [59:29<00:54, 54.35s/it]

Finished trial 49: val Loss: 494.875012 - with hyperparameters: {'lr': 0.00023905511123024548, 'weight_decay': 2.85756928309422e-05, 'outcome_dropout': 0.2737781094511875, 'shared_dropout': 0.19239398721958978, 'outcome_hidden': 350, 'shared_hidden': 350} | best trial: 43 Loss: 494.698334

Best trial: 43. Best value: 494.698: 100%|██████████| 50/50 [1:00:37<00:00, 72.75s/it]

In [10]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_Loss: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 43
Best mean_Val_Loss: 494.698334
Best params: {'lr': 0.00037878866852455317, 'weight_decay': 1.3850258905166982e-05, 'outcome_dropout': 0.16527671894777804, 'shared_dropout': 0.10391547088159996, 'outcome_hidden': 400, 'shared_hidden': 300}

Best config table:

,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_Val_Loss,std_Val_Loss
0,0.000379,0.000014,300.0,400.0,0.103915,0.165277,494.698334,0.133874

Top 10 trials:

,trial,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_Val_Loss,std_Val_Loss
0,43,0.0004,0.0000,300,400,0.104,0.165,494.698334,0.133874
1,34,0.0004,0.0000,300,400,0.121,0.305,494.701733,0.138271
2,42,0.0004,0.0000,300,400,0.112,0.246,494.704480,0.140657
3,38,0.0004,0.0000,300,400,0.079,0.235,494.712720,0.145845
4,41,0.0004,0.0000,300,400,0.109,0.264,494.716968,0.135407
5,32,0.0004,0.0000,300,400,0.068,0.462,494.719159,0.109425
6,19,0.0005,0.0000,400,250,0.255,0.337,494.721100,0.086293
7,44,0.0003,0.0001,300,400,0.104,0.057,494.723718,0.144786
8,12,0.0004,0.0000,300,200,0.136,0.450,494.737305,0.104401
9,48,0.0003,0.0000,300,400,0.084,0.149,494.741046,0.123472

In [11]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_shared_hidden = int(best_cfg['shared_hidden'])
best_outcome_hidden = int(best_cfg['outcome_hidden'])
best_shared_dropout = float(best_cfg['shared_dropout'])
best_outcome_dropout = float(best_cfg['outcome_dropout'])

print("Evaluating on test with best validation config:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"  shared_hidden={best_shared_hidden}, outcome_hidden={best_outcome_hidden}")
print(f"  shared_dropout={best_shared_dropout:.3f}, outcome_dropout={best_outcome_dropout:.3f}")
print(f"Number of seeds: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=best_shared_hidden,
        outcome_hidden=best_outcome_hidden,
        outcome_dropout=best_outcome_dropout,
        shared_dropout=best_shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
    )

    tarnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'PER-SEED DETAILS (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'TEST SUMMARY (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Evaluating on test with best validation config:
  lr=3.8e-04, weight_decay=1.4e-05
  shared_hidden=300, outcome_hidden=400
  shared_dropout=0.104, outcome_dropout=0.165
Number of seeds: 5
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: LOSS
📊 Early Stop Start Epoch: 31
📊 Strategy: Train for 150 epochs, select model with lowest validation loss
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 507.9962 | Total Loss: 507.9962 | Val Loss: 498.2501 | Val Qini: 0.7195 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 2/150 | Base Loss: 624.3326 | Total Loss: 624.3326 | Val Loss: 496.7626 | Val Qini: 0.6951 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 3/150 | Base Loss: 575.4592 | Total Loss: 575.4592 | Val Loss: 495.6756 | Val Qini: 0.7214 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 4/150 | Base Loss: 451.7173 | Total Loss: 451.7173 | Val Loss: 495.7808 | Val Qini: 0.7361 (patience: 1/20) | LR: 0.0004
Epoch 5/150 | Base Loss: 616.0840 | Total Loss: 616.0840 | Val Loss: 495.4454 | Val Qini: 0.7627 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 6/150 | Base Loss: 535.3669 | Total Loss: 535.3669 | Val Loss: 495.5921 | Val Qini: 0.7828 (patience: 1/20) | LR: 0.0004
Epoch 7/150 | Base Loss: 498.9780 | Total Loss: 498.9780 | Val Loss: 495.4664 | Val Qini: 0.7871 (patience: 2/20) | LR: 0.0004
Epoch 8/150 | Base Loss: 429.3102 | Total Loss: 429.3102 | Val Loss: 495.2408 | Val Qini: 0.8015 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 9/150 | Base Loss: 580.5121 | Total Loss: 580.5121 | Val Loss: 495.1561 | Val Qini: 0.8040 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 10/150 | Base Loss: 371.6933 | Total Loss: 371.6933 | Val Loss: 495.1223 | Val Qini: 0.7983 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 11/150 | Base Loss: 523.6966 | Total Loss: 523.6966 | Val Loss: 495.1225 | Val Qini: 0.7919 (patience: 1/20) | LR: 0.0004
Epoch 12/150 | Base Loss: 384.1993 | Total Loss: 384.1993 | Val Loss: 495.0848 | Val Qini: 0.7532 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 13/150 | Base Loss: 496.4108 | Total Loss: 496.4108 | Val Loss: 495.1058 | Val Qini: 0.7226 (patience: 1/20) | LR: 0.0004
Epoch 14/150 | Base Loss: 495.8520 | Total Loss: 495.8520 | Val Loss: 494.9899 | Val Qini: 0.7131 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 15/150 | Base Loss: 541.0000 | Total Loss: 541.0000 | Val Loss: 494.9328 | Val Qini: 0.6953 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 16/150 | Base Loss: 469.6680 | Total Loss: 469.6680 | Val Loss: 494.9906 | Val Qini: 0.6725 (patience: 1/20) | LR: 0.0004
Epoch 17/150 | Base Loss: 594.1093 | Total Loss: 594.1093 | Val Loss: 495.1293 | Val Qini: 0.6625 (patience: 2/20) | LR: 0.0004
Epoch 18/150 | Base Loss: 343.3646 | Total Loss: 343.3646 | Val Loss: 495.1890 | Val Qini: 0.6000 (patience: 3/20) | LR: 0.0004
Epoch 19/150 | Base Loss: 298.0708 | Total Loss: 298.0708 | Val Loss: 495.1247 | Val Qini: 0.6656 (patience: 4/20) | LR: 0.0004
Epoch 20/150 | Base Loss: 360.3771 | Total Loss: 360.3771 | Val Loss: 495.2294 | Val Qini: 0.6279 (patience: 5/20) | LR: 0.0004
Epoch 21/150 | Base Loss: 428.3725 | Total Loss: 428.3725 | Val Loss: 495.4857 | Val Qini: 0.5737 (patience: 6/20) | LR: 0.0004
Epoch 22/150 | Base Loss: 480.2865 | Total Loss: 480.2865 | Val Loss: 495.3951 | Val Qini: 0.5769 (patience: 7/20) | LR: 0.0004
Epoch 23/150 | Base Loss: 431.3710 | Total Loss: 431.3710 | Val Loss: 495.4274 | Val Qini: 0.5915 (patience: 8/20) | LR: 0.0004
Epoch 24/150 | Base Loss: 401.2981 | Total Loss: 401.2981 | Val Loss: 495.7027 | Val Qini: 0.5779 (patience: 9/20) | LR: 0.0004
Epoch 25/150 | Base Loss: 445.2104 | Total Loss: 445.2104 | Val Loss: 495.7100 | Val Qini: 0.5839 (patience: 10/20) | LR: 0.0004
Epoch 26/150 | Base Loss: 398.8345 | Total Loss: 398.8345 | Val Loss: 495.5632 | Val Qini: 0.6059 (patience: 11/20) | LR: 0.0002
Epoch 27/150 | Base Loss: 459.3925 | Total Loss: 459.3925 | Val Loss: 495.6486 | Val Qini: 0.6026 (patience: 12/20) | LR: 0.0002
Epoch 28/150 | Base Loss: 305.0598 | Total Loss: 305.0598 | Val Loss: 495.6673 | Val Qini: 0.6064 (patience: 13/20) | LR: 0.0002
Epoch 29/150 | Base Loss: 598.7051 | Total Loss: 598.7051 | Val Loss: 495.7126 | Val Qini: 0.6111 (patience: 14/20) | LR: 0.0002
Epoch 30/150 | Base Loss: 587.8943 | Total Loss: 587.8943 | Val Loss: 495.7423 | Val Qini: 0.6156 (patience: 15/20) | LR: 0.0002
Epoch 31/150 | Base Loss: 399.5139 | Total Loss: 399.5139 | Val Loss: 495.8298 | Val Qini: 0.6116 (patience: 16/20) | LR: 0.0002
Epoch 32/150 | Base Loss: 312.5322 | Total Loss: 312.5322 | Val Loss: 495.8842 | Val Qini: 0.6117 (patience: 17/20) | LR: 0.0002
Epoch 33/150 | Base Loss: 368.3817 | Total Loss: 368.3817 | Val Loss: 495.8962 | Val Qini: 0.6153 (patience: 18/20) | LR: 0.0002
Epoch 34/150 | Base Loss: 329.2834 | Total Loss: 329.2834 | Val Loss: 495.8344 | Val Qini: 0.6242 (patience: 19/20) | LR: 0.0002
Epoch 35/150 | Base Loss: 545.3356 | Total Loss: 545.3356 | Val Loss: 495.8618 | Val Qini: 0.6260 (patience: 20/20) | LR: 0.0002

🛑 Early stopping triggered at epoch 35!
   No improvement in validation loss for 20 epochs

✅ Training completed! Restored model to epoch 15
   Best Val Loss: 494.9328
   Qini at best epoch: 0.6953
  Done Seed 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: LOSS
📊 Early Stop Start Epoch: 31
📊 Strategy: Train for 150 epochs, select model with lowest validation loss
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 736.3218 | Total Loss: 736.3218 | Val Loss: 498.2376 | Val Qini: 0.5792 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 2/150 | Base Loss: 522.5616 | Total Loss: 522.5616 | Val Loss: 496.9324 | Val Qini: 0.6236 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 3/150 | Base Loss: 410.2177 | Total Loss: 410.2177 | Val Loss: 495.9556 | Val Qini: 0.6663 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 4/150 | Base Loss: 631.6168 | Total Loss: 631.6168 | Val Loss: 495.9012 | Val Qini: 0.7181 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 5/150 | Base Loss: 494.5718 | Total Loss: 494.5718 | Val Loss: 495.4763 | Val Qini: 0.7620 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 6/150 | Base Loss: 502.2293 | Total Loss: 502.2293 | Val Loss: 495.6318 | Val Qini: 0.7784 (patience: 1/20) | LR: 0.0004
Epoch 7/150 | Base Loss: 347.3402 | Total Loss: 347.3402 | Val Loss: 495.3351 | Val Qini: 0.7906 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 8/150 | Base Loss: 455.7661 | Total Loss: 455.7661 | Val Loss: 495.1155 | Val Qini: 0.7990 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 9/150 | Base Loss: 487.6523 | Total Loss: 487.6523 | Val Loss: 495.0363 | Val Qini: 0.7923 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 10/150 | Base Loss: 536.7570 | Total Loss: 536.7570 | Val Loss: 495.0487 | Val Qini: 0.7847 (patience: 1/20) | LR: 0.0004
Epoch 11/150 | Base Loss: 613.9574 | Total Loss: 613.9574 | Val Loss: 494.9710 | Val Qini: 0.7821 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 12/150 | Base Loss: 610.5383 | Total Loss: 610.5383 | Val Loss: 494.7888 | Val Qini: 0.7845 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 13/150 | Base Loss: 712.0472 | Total Loss: 712.0472 | Val Loss: 494.6174 | Val Qini: 0.7883 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 14/150 | Base Loss: 538.5445 | Total Loss: 538.5445 | Val Loss: 494.6722 | Val Qini: 0.7514 (patience: 1/20) | LR: 0.0004
Epoch 15/150 | Base Loss: 314.3682 | Total Loss: 314.3682 | Val Loss: 494.7313 | Val Qini: 0.7032 (patience: 2/20) | LR: 0.0004
Epoch 16/150 | Base Loss: 578.0541 | Total Loss: 578.0541 | Val Loss: 494.8521 | Val Qini: 0.6546 (patience: 3/20) | LR: 0.0004
Epoch 17/150 | Base Loss: 463.5523 | Total Loss: 463.5523 | Val Loss: 494.9844 | Val Qini: 0.5681 (patience: 4/20) | LR: 0.0004
Epoch 18/150 | Base Loss: 464.0149 | Total Loss: 464.0149 | Val Loss: 494.9716 | Val Qini: 0.5532 (patience: 5/20) | LR: 0.0004
Epoch 19/150 | Base Loss: 320.0310 | Total Loss: 320.0310 | Val Loss: 495.0470 | Val Qini: 0.5454 (patience: 6/20) | LR: 0.0004
Epoch 20/150 | Base Loss: 312.8434 | Total Loss: 312.8434 | Val Loss: 495.1338 | Val Qini: 0.5311 (patience: 7/20) | LR: 0.0004
Epoch 21/150 | Base Loss: 385.1919 | Total Loss: 385.1919 | Val Loss: 495.1783 | Val Qini: 0.5275 (patience: 8/20) | LR: 0.0004
Epoch 22/150 | Base Loss: 428.1429 | Total Loss: 428.1429 | Val Loss: 495.3365 | Val Qini: 0.4818 (patience: 9/20) | LR: 0.0004
Epoch 23/150 | Base Loss: 652.2698 | Total Loss: 652.2698 | Val Loss: 495.2330 | Val Qini: 0.5303 (patience: 10/20) | LR: 0.0004
Epoch 24/150 | Base Loss: 344.8846 | Total Loss: 344.8846 | Val Loss: 495.2081 | Val Qini: 0.5541 (patience: 11/20) | LR: 0.0002
Epoch 25/150 | Base Loss: 395.5124 | Total Loss: 395.5124 | Val Loss: 495.1243 | Val Qini: 0.5749 (patience: 12/20) | LR: 0.0002
Epoch 26/150 | Base Loss: 549.5793 | Total Loss: 549.5793 | Val Loss: 495.1877 | Val Qini: 0.5617 (patience: 13/20) | LR: 0.0002
Epoch 27/150 | Base Loss: 314.6188 | Total Loss: 314.6188 | Val Loss: 495.2514 | Val Qini: 0.5593 (patience: 14/20) | LR: 0.0002
Epoch 28/150 | Base Loss: 408.4052 | Total Loss: 408.4052 | Val Loss: 495.2649 | Val Qini: 0.5641 (patience: 15/20) | LR: 0.0002
Epoch 29/150 | Base Loss: 546.2125 | Total Loss: 546.2125 | Val Loss: 495.2740 | Val Qini: 0.5758 (patience: 16/20) | LR: 0.0002
Epoch 30/150 | Base Loss: 521.8295 | Total Loss: 521.8295 | Val Loss: 495.2072 | Val Qini: 0.5895 (patience: 17/20) | LR: 0.0002
Epoch 31/150 | Base Loss: 208.2949 | Total Loss: 208.2949 | Val Loss: 495.1103 | Val Qini: 0.6171 (patience: 18/20) | LR: 0.0002
Epoch 32/150 | Base Loss: 602.8354 | Total Loss: 602.8354 | Val Loss: 495.0603 | Val Qini: 0.6255 (patience: 19/20) | LR: 0.0002
Epoch 33/150 | Base Loss: 373.2515 | Total Loss: 373.2515 | Val Loss: 495.1783 | Val Qini: 0.6100 (patience: 20/20) | LR: 0.0002

🛑 Early stopping triggered at epoch 33!
   No improvement in validation loss for 20 epochs

✅ Training completed! Restored model to epoch 13
   Best Val Loss: 494.6174
   Qini at best epoch: 0.7883
  Done Seed 42
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: LOSS
📊 Early Stop Start Epoch: 31
📊 Strategy: Train for 150 epochs, select model with lowest validation loss
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 444.5845 | Total Loss: 444.5845 | Val Loss: 498.1604 | Val Qini: 0.6500 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 2/150 | Base Loss: 330.5581 | Total Loss: 330.5581 | Val Loss: 496.9784 | Val Qini: 0.6653 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 3/150 | Base Loss: 542.5127 | Total Loss: 542.5127 | Val Loss: 496.0025 | Val Qini: 0.7208 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 4/150 | Base Loss: 420.2945 | Total Loss: 420.2945 | Val Loss: 495.9456 | Val Qini: 0.7576 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 5/150 | Base Loss: 472.2656 | Total Loss: 472.2656 | Val Loss: 495.4585 | Val Qini: 0.7895 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 6/150 | Base Loss: 314.4034 | Total Loss: 314.4034 | Val Loss: 495.5304 | Val Qini: 0.8110 (patience: 1/20) | LR: 0.0004
Epoch 7/150 | Base Loss: 469.4760 | Total Loss: 469.4760 | Val Loss: 495.6865 | Val Qini: 0.8190 (patience: 2/20) | LR: 0.0004
Epoch 8/150 | Base Loss: 510.9827 | Total Loss: 510.9827 | Val Loss: 495.3224 | Val Qini: 0.8340 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 9/150 | Base Loss: 455.8288 | Total Loss: 455.8288 | Val Loss: 494.9771 | Val Qini: 0.8468 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 10/150 | Base Loss: 438.3353 | Total Loss: 438.3353 | Val Loss: 494.8965 | Val Qini: 0.8427 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 11/150 | Base Loss: 468.0714 | Total Loss: 468.0714 | Val Loss: 494.8280 | Val Qini: 0.8420 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 12/150 | Base Loss: 321.9235 | Total Loss: 321.9235 | Val Loss: 494.8282 | Val Qini: 0.8316 (patience: 1/20) | LR: 0.0004
Epoch 13/150 | Base Loss: 467.7014 | Total Loss: 467.7014 | Val Loss: 494.9050 | Val Qini: 0.8141 (patience: 2/20) | LR: 0.0004
Epoch 14/150 | Base Loss: 352.6411 | Total Loss: 352.6411 | Val Loss: 494.7592 | Val Qini: 0.7931 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 15/150 | Base Loss: 559.6575 | Total Loss: 559.6575 | Val Loss: 494.6080 | Val Qini: 0.7950 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 16/150 | Base Loss: 566.6220 | Total Loss: 566.6220 | Val Loss: 494.6352 | Val Qini: 0.7620 (patience: 1/20) | LR: 0.0004
Epoch 17/150 | Base Loss: 699.3326 | Total Loss: 699.3326 | Val Loss: 494.8038 | Val Qini: 0.6981 (patience: 2/20) | LR: 0.0004
Epoch 18/150 | Base Loss: 233.7412 | Total Loss: 233.7412 | Val Loss: 494.7174 | Val Qini: 0.6931 (patience: 3/20) | LR: 0.0004
Epoch 19/150 | Base Loss: 515.1019 | Total Loss: 515.1019 | Val Loss: 494.8413 | Val Qini: 0.6721 (patience: 4/20) | LR: 0.0004
Epoch 20/150 | Base Loss: 313.8542 | Total Loss: 313.8542 | Val Loss: 494.9409 | Val Qini: 0.6424 (patience: 5/20) | LR: 0.0004
Epoch 21/150 | Base Loss: 423.1669 | Total Loss: 423.1669 | Val Loss: 495.0477 | Val Qini: 0.6055 (patience: 6/20) | LR: 0.0004
Epoch 22/150 | Base Loss: 433.1024 | Total Loss: 433.1024 | Val Loss: 495.2612 | Val Qini: 0.5818 (patience: 7/20) | LR: 0.0004
Epoch 23/150 | Base Loss: 661.9010 | Total Loss: 661.9010 | Val Loss: 495.2637 | Val Qini: 0.5641 (patience: 8/20) | LR: 0.0004
Epoch 24/150 | Base Loss: 242.3910 | Total Loss: 242.3910 | Val Loss: 495.3700 | Val Qini: 0.5386 (patience: 9/20) | LR: 0.0004
Epoch 25/150 | Base Loss: 291.4767 | Total Loss: 291.4767 | Val Loss: 495.5219 | Val Qini: 0.5333 (patience: 10/20) | LR: 0.0004
Epoch 26/150 | Base Loss: 396.4240 | Total Loss: 396.4240 | Val Loss: 495.4865 | Val Qini: 0.5624 (patience: 11/20) | LR: 0.0002
Epoch 27/150 | Base Loss: 363.8730 | Total Loss: 363.8730 | Val Loss: 495.4554 | Val Qini: 0.5791 (patience: 12/20) | LR: 0.0002
Epoch 28/150 | Base Loss: 454.5915 | Total Loss: 454.5915 | Val Loss: 495.4807 | Val Qini: 0.5855 (patience: 13/20) | LR: 0.0002
Epoch 29/150 | Base Loss: 439.5979 | Total Loss: 439.5979 | Val Loss: 495.5381 | Val Qini: 0.5912 (patience: 14/20) | LR: 0.0002
Epoch 30/150 | Base Loss: 531.9053 | Total Loss: 531.9053 | Val Loss: 495.5028 | Val Qini: 0.6063 (patience: 15/20) | LR: 0.0002
Epoch 31/150 | Base Loss: 288.5593 | Total Loss: 288.5593 | Val Loss: 495.5333 | Val Qini: 0.6090 (patience: 16/20) | LR: 0.0002
Epoch 32/150 | Base Loss: 481.7079 | Total Loss: 481.7079 | Val Loss: 495.5507 | Val Qini: 0.6100 (patience: 17/20) | LR: 0.0002
Epoch 33/150 | Base Loss: 364.6115 | Total Loss: 364.6115 | Val Loss: 495.5900 | Val Qini: 0.6119 (patience: 18/20) | LR: 0.0002
Epoch 34/150 | Base Loss: 340.2141 | Total Loss: 340.2141 | Val Loss: 495.5432 | Val Qini: 0.6197 (patience: 19/20) | LR: 0.0002
Epoch 35/150 | Base Loss: 533.8331 | Total Loss: 533.8331 | Val Loss: 495.5216 | Val Qini: 0.6257 (patience: 20/20) | LR: 0.0002

🛑 Early stopping triggered at epoch 35!
   No improvement in validation loss for 20 epochs

✅ Training completed! Restored model to epoch 15
   Best Val Loss: 494.6080
   Qini at best epoch: 0.7950
  Done Seed 1874
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: LOSS
📊 Early Stop Start Epoch: 31
📊 Strategy: Train for 150 epochs, select model with lowest validation loss
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 354.0581 | Total Loss: 354.0581 | Val Loss: 498.3103 | Val Qini: 0.4769 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 2/150 | Base Loss: 391.2195 | Total Loss: 391.2195 | Val Loss: 497.1463 | Val Qini: 0.6360 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 3/150 | Base Loss: 608.5820 | Total Loss: 608.5820 | Val Loss: 495.9256 | Val Qini: 0.7381 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 4/150 | Base Loss: 443.1642 | Total Loss: 443.1642 | Val Loss: 495.5544 | Val Qini: 0.7924 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 5/150 | Base Loss: 369.4157 | Total Loss: 369.4157 | Val Loss: 495.3189 | Val Qini: 0.8478 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 6/150 | Base Loss: 524.4588 | Total Loss: 524.4588 | Val Loss: 495.4577 | Val Qini: 0.8554 (patience: 1/20) | LR: 0.0004
Epoch 7/150 | Base Loss: 424.1113 | Total Loss: 424.1113 | Val Loss: 495.5221 | Val Qini: 0.8469 (patience: 2/20) | LR: 0.0004
Epoch 8/150 | Base Loss: 525.2399 | Total Loss: 525.2399 | Val Loss: 495.4381 | Val Qini: 0.8252 (patience: 3/20) | LR: 0.0004
Epoch 9/150 | Base Loss: 452.2179 | Total Loss: 452.2179 | Val Loss: 495.2424 | Val Qini: 0.8143 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 10/150 | Base Loss: 456.6314 | Total Loss: 456.6314 | Val Loss: 495.1446 | Val Qini: 0.8022 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 11/150 | Base Loss: 288.3777 | Total Loss: 288.3777 | Val Loss: 495.0240 | Val Qini: 0.7907 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 12/150 | Base Loss: 397.4687 | Total Loss: 397.4687 | Val Loss: 494.9776 | Val Qini: 0.7683 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 13/150 | Base Loss: 351.9827 | Total Loss: 351.9827 | Val Loss: 494.9211 | Val Qini: 0.7660 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 14/150 | Base Loss: 407.5179 | Total Loss: 407.5179 | Val Loss: 494.7862 | Val Qini: 0.7129 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 15/150 | Base Loss: 364.6829 | Total Loss: 364.6829 | Val Loss: 494.7393 | Val Qini: 0.6542 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 16/150 | Base Loss: 484.1917 | Total Loss: 484.1917 | Val Loss: 494.6638 | Val Qini: 0.6298 ⭐ NEW BEST (lowest loss) | LR: 0.0004
Epoch 17/150 | Base Loss: 433.9131 | Total Loss: 433.9131 | Val Loss: 494.7278 | Val Qini: 0.5818 (patience: 1/20) | LR: 0.0004
Epoch 18/150 | Base Loss: 415.6519 | Total Loss: 415.6519 | Val Loss: 494.9026 | Val Qini: 0.5310 (patience: 2/20) | LR: 0.0004
Epoch 19/150 | Base Loss: 443.4586 | Total Loss: 443.4586 | Val Loss: 495.1110 | Val Qini: 0.5008 (patience: 3/20) | LR: 0.0004
Epoch 20/150 | Base Loss: 234.3125 | Total Loss: 234.3125 | Val Loss: 495.1604 | Val Qini: 0.5113 (patience: 4/20) | LR: 0.0004
Epoch 21/150 | Base Loss: 391.5766 | Total Loss: 391.5766 | Val Loss: 495.1692 | Val Qini: 0.5213 (patience: 5/20) | LR: 0.0004
Epoch 22/150 | Base Loss: 457.4489 | Total Loss: 457.4489 | Val Loss: 495.2358 | Val Qini: 0.5162 (patience: 6/20) | LR: 0.0004
Epoch 23/150 | Base Loss: 525.8373 | Total Loss: 525.8373 | Val Loss: 495.3510 | Val Qini: 0.5113 (patience: 7/20) | LR: 0.0004
Epoch 24/150 | Base Loss: 299.3776 | Total Loss: 299.3776 | Val Loss: 495.4366 | Val Qini: 0.5088 (patience: 8/20) | LR: 0.0004
Epoch 25/150 | Base Loss: 565.6383 | Total Loss: 565.6383 | Val Loss: 495.5775 | Val Qini: 0.5028 (patience: 9/20) | LR: 0.0004
Epoch 26/150 | Base Loss: 548.6276 | Total Loss: 548.6276 | Val Loss: 495.3476 | Val Qini: 0.5671 (patience: 10/20) | LR: 0.0004
Epoch 27/150 | Base Loss: 571.8559 | Total Loss: 571.8559 | Val Loss: 495.7470 | Val Qini: 0.4888 (patience: 11/20) | LR: 0.0002
Epoch 28/150 | Base Loss: 362.7538 | Total Loss: 362.7538 | Val Loss: 495.7203 | Val Qini: 0.4947 (patience: 12/20) | LR: 0.0002
Epoch 29/150 | Base Loss: 445.9315 | Total Loss: 445.9315 | Val Loss: 495.5273 | Val Qini: 0.5432 (patience: 13/20) | LR: 0.0002
Epoch 30/150 | Base Loss: 524.1310 | Total Loss: 524.1310 | Val Loss: 495.5189 | Val Qini: 0.5637 (patience: 14/20) | LR: 0.0002
Epoch 31/150 | Base Loss: 491.1539 | Total Loss: 491.1539 | Val Loss: 495.5464 | Val Qini: 0.5596 (patience: 15/20) | LR: 0.0002
Epoch 32/150 | Base Loss: 388.1724 | Total Loss: 388.1724 | Val Loss: 495.6092 | Val Qini: 0.5590 (patience: 16/20) | LR: 0.0002
Epoch 33/150 | Base Loss: 368.4974 | Total Loss: 368.4974 | Val Loss: 495.7613 | Val Qini: 0.5572 (patience: 17/20) | LR: 0.0002
Epoch 34/150 | Base Loss: 374.2365 | Total Loss: 374.2365 | Val Loss: 495.9958 | Val Qini: 0.5538 (patience: 18/20) | LR: 0.0002
Epoch 35/150 | Base Loss: 511.3988 | Total Loss: 511.3988 | Val Loss: 495.9602 | Val Qini: 0.5685 (patience: 19/20) | LR: 0.0002
Epoch 36/150 | Base Loss: 241.1949 | Total Loss: 241.1949 | Val Loss: 495.8513 | Val Qini: 0.6032 (patience: 20/20) | LR: 0.0002

🛑 Early stopping triggered at epoch 36!
   No improvement in validation loss for 20 epochs

✅ Training completed! Restored model to epoch 16
   Best Val Loss: 494.6638
   Qini at best epoch: 0.6298
  Done Seed 902745
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: LOSS