In [31]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/RERUM")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
sys.path.append("..")
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [32]:
%time train_df = pd.read_csv(r"../dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"../dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"../dataset/Hillstrom/Men/val_men.csv")

CPU times: user 27.4 ms, sys: 5 ms, total: 32.5 ms
Wall time: 31.9 ms
CPU times: user 11.4 ms, sys: 5 ms, total: 16.4 ms
Wall time: 16.3 ms
CPU times: user 4.09 ms, sys: 1 ms, total: 5.09 ms
Wall time: 5.06 ms

In [33]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [34]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [35]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [36]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [37]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [38]:
epochs = 150
early_stop_metric = "ema_qini"
ema = True
ema_alpha = 0.25
patience = 20
shared_dropout = 0.0
outcome_dropout = 0
shared_hidden = 200
outcome_hidden = 100
early_stop_start = 30
uplift_ranking = 0
response_ranking = 0
print (f" epochs = {epochs}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 early stop = ema_qini
 use ema = True
 ema alpha = 0.25
 patience = 20
 early stop start = 30

In [ ]:
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 5e-5, 5e-3, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-6, 1e-2, log=True)
    grid_outcome_dropout = trial.suggest_float("outcome_dropout", 0.1, 0.5)
    grid_shared_dropout = trial.suggest_float("shared_dropout", 0.0, 0.4)
    grid_shared_hidden = trial.suggest_categorical("shared_hidden", [128, 256, 384, 512])
    grid_outcome_hidden = trial.suggest_categorical("outcome_hidden", [64, 128, 256])

    val_auqc_list = []
    val_ate_err_list = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=grid_shared_hidden,
            outcome_hidden=grid_outcome_hidden,
            outcome_dropout=grid_outcome_dropout,
            shared_dropout=grid_shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
        )

        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_men_val_t_on_device = x_men_val_t.to(device)
        y0_pred, y1_pred = tarnet.predict(x_men_val_t_on_device)

        uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
        y_true = y_men_val_t.detach().cpu().numpy().flatten()
        t_true = t_men_val_t.detach().cpu().numpy().flatten()
        
        current_val_auqc = auqc(y_true, t_true, uplift_pred, bins=100, plot=False)
        ate_pred = uplift_pred.mean()
        ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
        current_val_ate_err = abs(ate_pred - ate_true)

        val_auqc_list.append(current_val_auqc)
        val_ate_err_list.append(current_val_ate_err)

    # Calculate aggregated metrics across the 5 validation seeds
    mean_auqc = float(np.mean(val_auqc_list))
    std_auqc = float(np.std(val_auqc_list))
    mean_ate_err = float(np.mean(val_ate_err_list))

    # Apply penalty for instability and miscalibration
    penalty_std = std_auqc * 2.0

    final_score = mean_auqc - penalty_std

    trial.set_user_attr("mean_val_auqc", mean_auqc)
    trial.set_user_attr("std_Val_auqc", std_auqc)
    trial.set_user_attr("mean_val_ate_err", mean_ate_err)
    trial.set_user_attr("final_score", final_score) 
    return final_score

def print_trial_callback(study, trial):
    value = float(trial.value) if trial.value is not None else float("nan")
    best_trial = study.best_trial
    best_value = float(best_trial.value) if best_trial.value is not None else float("nan")
    print(
        f"Finished trial {trial.number}: val loss: {value:.4f} - "
        f"with hyperparameters: {trial.params} | "
        f"best trial: {best_trial.number} loss: {best_value:.4f}",
        flush=True
    )

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True, callbacks=[print_trial_callback])

trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": round(float(t.params["lr"]), 4),
        "weight_decay": round(float(t.params["weight_decay"]), 4),
        "shared_hidden": int(t.params["shared_hidden"]),
        "outcome_hidden": int(t.params["outcome_hidden"]),
        "shared_dropout": round(float(t.params["shared_dropout"]), 3),
        "outcome_dropout": round(float(t.params["outcome_dropout"]), 3),
        "mean_val_auqc": float(t.value),
        "std_Val_auqc": float(t.user_attrs.get("std_Val_auqc", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_val_auqc", ascending=True).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "shared_hidden": int(best_params["shared_hidden"]),
    "outcome_hidden": int(best_params["outcome_hidden"]),
    "shared_dropout": float(best_params["shared_dropout"]),
    "outcome_dropout": float(best_params["outcome_dropout"]),
    "mean_Val_auqc": float(study.best_value),
    "std_Val_auqc": float(study.best_trial.user_attrs.get("std_Val_auqc", np.nan))
})

  0%|          | 0/50 [00:00<?, ?it/s]

Finished trial 0: val loss: 0.7420 - with hyperparameters: {'lr': 0.00045041481661314923, 'weight_decay': 3.2543813547868006e-05, 'outcome_dropout': 0.26330970370677254, 'shared_dropout': 0.17735402643744136, 'shared_hidden': 512, 'outcome_hidden': 256} | best trial: 0 loss: 0.7420

Best trial: 0. Best value: 0.742028:   2%|▏         | 1/50 [01:12<59:21, 72.69s/it]

Finished trial 1: val loss: 0.7852 - with hyperparameters: {'lr': 0.00020955060428245223, 'weight_decay': 4.661152760287686e-05, 'outcome_dropout': 0.16868166430648263, 'shared_dropout': 0.086292445337752, 'shared_hidden': 256, 'outcome_hidden': 256} | best trial: 1 loss: 0.7852

Best trial: 1. Best value: 0.785203:   4%|▍         | 2/50 [02:24<57:39, 72.08s/it]

Finished trial 2: val loss: 0.8211 - with hyperparameters: {'lr': 0.0012489058658324021, 'weight_decay': 0.0006574118870559875, 'outcome_dropout': 0.40972440979250113, 'shared_dropout': 0.14099552567852208, 'shared_hidden': 384, 'outcome_hidden': 64} | best trial: 2 loss: 0.8211

Best trial: 2. Best value: 0.821056:   6%|▌         | 3/50 [03:36<56:32, 72.18s/it]

Finished trial 3: val loss: 0.7591 - with hyperparameters: {'lr': 0.00019404547112084804, 'weight_decay': 0.00029219423947572713, 'outcome_dropout': 0.42335536081431857, 'shared_dropout': 0.25609942813417735, 'shared_hidden': 512, 'outcome_hidden': 256} | best trial: 2 loss: 0.8211

Best trial: 2. Best value: 0.821056:   8%|▊         | 4/50 [04:47<54:52, 71.57s/it]

Finished trial 4: val loss: 0.7397 - with hyperparameters: {'lr': 0.00040560051710911247, 'weight_decay': 5.868683700687444e-06, 'outcome_dropout': 0.2707168665538623, 'shared_dropout': 0.1703254591420071, 'shared_hidden': 128, 'outcome_hidden': 256} | best trial: 2 loss: 0.8211

Best trial: 2. Best value: 0.821056:  10%|█         | 5/50 [05:59<53:43, 71.64s/it]

Finished trial 5: val loss: 0.7939 - with hyperparameters: {'lr': 0.0002480375081957283, 'weight_decay': 0.005215053832155927, 'outcome_dropout': 0.10424329266915207, 'shared_dropout': 0.06575156778834486, 'shared_hidden': 256, 'outcome_hidden': 128} | best trial: 2 loss: 0.8211

Best trial: 2. Best value: 0.821056:  12%|█▏        | 6/50 [07:27<56:47, 77.44s/it]

Finished trial 6: val loss: 0.7586 - with hyperparameters: {'lr': 0.0003316369685998863, 'weight_decay': 0.0012969566974162193, 'outcome_dropout': 0.2094142783085165, 'shared_dropout': 0.30570695974415385, 'shared_hidden': 384, 'outcome_hidden': 256} | best trial: 2 loss: 0.8211

Best trial: 2. Best value: 0.821056:  14%|█▍        | 7/50 [08:39<54:14, 75.69s/it]

Finished trial 7: val loss: 0.8443 - with hyperparameters: {'lr': 0.0010264731264242133, 'weight_decay': 0.0099817413472071, 'outcome_dropout': 0.3051585898258632, 'shared_dropout': 0.04879368503318604, 'shared_hidden': 512, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  16%|█▌        | 8/50 [09:50<51:55, 74.17s/it]

Finished trial 8: val loss: 0.7519 - with hyperparameters: {'lr': 0.0034021597135420753, 'weight_decay': 5.390789624128435e-05, 'outcome_dropout': 0.32130153875258916, 'shared_dropout': 0.2806137161508955, 'shared_hidden': 512, 'outcome_hidden': 256} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  18%|█▊        | 9/50 [11:02<50:09, 73.40s/it]

Finished trial 9: val loss: 0.7634 - with hyperparameters: {'lr': 0.004823047987252311, 'weight_decay': 7.905030616880524e-05, 'outcome_dropout': 0.2806750576038549, 'shared_dropout': 0.18124623879008525, 'shared_hidden': 384, 'outcome_hidden': 256} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  20%|██        | 10/50 [12:11<48:05, 72.15s/it]

Finished trial 10: val loss: 0.3735 - with hyperparameters: {'lr': 7.862745948027409e-05, 'weight_decay': 0.009980143580923594, 'outcome_dropout': 0.47633602469882985, 'shared_dropout': 0.3988169894338867, 'shared_hidden': 128, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  22%|██▏       | 11/50 [14:05<55:13, 84.97s/it]

Finished trial 11: val loss: 0.7855 - with hyperparameters: {'lr': 0.0013596184781214501, 'weight_decay': 0.0008664707738831034, 'outcome_dropout': 0.3827527799543919, 'shared_dropout': 0.02623519204882757, 'shared_hidden': 384, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  24%|██▍       | 12/50 [15:16<51:06, 80.70s/it]

Finished trial 12: val loss: 0.7986 - with hyperparameters: {'lr': 0.0012414625968014228, 'weight_decay': 0.0018866555110011445, 'outcome_dropout': 0.36064335299471567, 'shared_dropout': 0.11402073216119998, 'shared_hidden': 384, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  26%|██▌       | 13/50 [16:27<47:59, 77.82s/it]

Finished trial 13: val loss: 0.7633 - with hyperparameters: {'lr': 0.001153173993098941, 'weight_decay': 1.1449274036061599e-06, 'outcome_dropout': 0.4886788692347885, 'shared_dropout': 0.0009425308713729638, 'shared_hidden': 512, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  28%|██▊       | 14/50 [17:40<45:40, 76.13s/it]

Finished trial 14: val loss: 0.7498 - with hyperparameters: {'lr': 0.0021831679769738904, 'weight_decay': 0.0002727180441047947, 'outcome_dropout': 0.42434375717108364, 'shared_dropout': 0.1365732097954779, 'shared_hidden': 512, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  30%|███       | 15/50 [18:51<43:29, 74.56s/it]

Finished trial 15: val loss: 0.8109 - with hyperparameters: {'lr': 0.0008187434193194586, 'weight_decay': 0.0030088454439389086, 'outcome_dropout': 0.3388981571210378, 'shared_dropout': 0.05381563783209653, 'shared_hidden': 384, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  32%|███▏      | 16/50 [20:02<41:38, 73.49s/it]

Finished trial 16: val loss: 0.7536 - with hyperparameters: {'lr': 0.0006909081601518651, 'weight_decay': 0.00038955408926474503, 'outcome_dropout': 0.41339446713446965, 'shared_dropout': 0.241169338129463, 'shared_hidden': 128, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  34%|███▍      | 17/50 [21:15<40:21, 73.38s/it]

Finished trial 17: val loss: 0.8434 - with hyperparameters: {'lr': 0.002256113015235798, 'weight_decay': 0.009765808627986896, 'outcome_dropout': 0.3790540056333685, 'shared_dropout': 0.11576262146654089, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  36%|███▌      | 18/50 [22:25<38:40, 72.52s/it]

Finished trial 18: val loss: 0.8152 - with hyperparameters: {'lr': 0.0028079016347088877, 'weight_decay': 0.00810911963415144, 'outcome_dropout': 0.20469793757383037, 'shared_dropout': 0.09532672523175867, 'shared_hidden': 256, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  38%|███▊      | 19/50 [23:35<37:01, 71.65s/it]

Finished trial 19: val loss: 0.7249 - with hyperparameters: {'lr': 9.784000365607456e-05, 'weight_decay': 0.003015875160241605, 'outcome_dropout': 0.3104706854077668, 'shared_dropout': 0.023024807168535492, 'shared_hidden': 256, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  40%|████      | 20/50 [26:25<50:32, 101.08s/it]

Finished trial 20: val loss: 0.7650 - with hyperparameters: {'lr': 0.002087288796992326, 'weight_decay': 1.5992065739752653e-05, 'outcome_dropout': 0.23899609191218188, 'shared_dropout': 0.2295981416564684, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  42%|████▏     | 21/50 [27:34<44:17, 91.64s/it]

Finished trial 21: val loss: 0.8033 - with hyperparameters: {'lr': 0.0007414672803270677, 'weight_decay': 0.000715341445532045, 'outcome_dropout': 0.38085318615997266, 'shared_dropout': 0.138775708357322, 'shared_hidden': 384, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  44%|████▍     | 22/50 [28:45<39:48, 85.31s/it]

Finished trial 22: val loss: 0.8334 - with hyperparameters: {'lr': 0.0017628146284992578, 'weight_decay': 0.004821719358785853, 'outcome_dropout': 0.45091206424701913, 'shared_dropout': 0.13326759581436676, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  46%|████▌     | 23/50 [29:56<36:26, 80.97s/it]

Finished trial 23: val loss: 0.8296 - with hyperparameters: {'lr': 0.0018616884812864827, 'weight_decay': 0.004690311864869577, 'outcome_dropout': 0.4555370939970363, 'shared_dropout': 0.062406283886521675, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  48%|████▊     | 24/50 [31:06<33:45, 77.89s/it]

Finished trial 24: val loss: 0.8160 - with hyperparameters: {'lr': 0.004954031080858436, 'weight_decay': 0.0024732329125487567, 'outcome_dropout': 0.3505078986736551, 'shared_dropout': 0.11055649706079851, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  50%|█████     | 25/50 [32:17<31:32, 75.69s/it]

Finished trial 25: val loss: 0.8275 - with hyperparameters: {'lr': 0.0030220278656566003, 'weight_decay': 0.008614319486536248, 'outcome_dropout': 0.44993384928686797, 'shared_dropout': 0.04339864480686998, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  52%|█████▏    | 26/50 [33:28<29:44, 74.33s/it]

Finished trial 26: val loss: 0.7892 - with hyperparameters: {'lr': 0.0009125932954756418, 'weight_decay': 0.003854625987547505, 'outcome_dropout': 0.38386662162991897, 'shared_dropout': 0.0834890207039318, 'shared_hidden': 512, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  54%|█████▍    | 27/50 [34:39<28:08, 73.43s/it]

Finished trial 27: val loss: 0.7941 - with hyperparameters: {'lr': 0.0016971961273571862, 'weight_decay': 0.0017487945661401366, 'outcome_dropout': 0.4981523344147602, 'shared_dropout': 0.15346300869989166, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  56%|█████▌    | 28/50 [35:50<26:37, 72.62s/it]

Finished trial 28: val loss: 0.7918 - with hyperparameters: {'lr': 0.0033770629523206456, 'weight_decay': 0.005123855630675949, 'outcome_dropout': 0.29261147816322336, 'shared_dropout': 0.20552203574689556, 'shared_hidden': 256, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  58%|█████▊    | 29/50 [37:00<25:07, 71.77s/it]

Finished trial 29: val loss: 0.7313 - with hyperparameters: {'lr': 0.001623438809975363, 'weight_decay': 0.00015595213397553314, 'outcome_dropout': 0.4525085749721313, 'shared_dropout': 0.18880888766770046, 'shared_hidden': 512, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  60%|██████    | 30/50 [38:11<23:53, 71.65s/it]

Finished trial 30: val loss: 0.7702 - with hyperparameters: {'lr': 0.0010046190388481176, 'weight_decay': 0.0012321390317113594, 'outcome_dropout': 0.3300119501392261, 'shared_dropout': 0.11356632738294063, 'shared_hidden': 512, 'outcome_hidden': 128} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  62%|██████▏   | 31/50 [39:23<22:41, 71.66s/it]

Finished trial 31: val loss: 0.8059 - with hyperparameters: {'lr': 0.000559203538894898, 'weight_decay': 0.005547521819259597, 'outcome_dropout': 0.4666546944844114, 'shared_dropout': 0.05957492366601899, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 7 loss: 0.8443

Best trial: 7. Best value: 0.844293:  64%|██████▍   | 32/50 [40:47<22:39, 75.54s/it]

Finished trial 32: val loss: 0.8464 - with hyperparameters: {'lr': 0.001985751856002372, 'weight_decay': 0.009911495981946378, 'outcome_dropout': 0.44246896501380684, 'shared_dropout': 0.08689243866140463, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 32 loss: 0.8464

Best trial: 32. Best value: 0.846415:  66%|██████▌   | 33/50 [41:57<20:52, 73.66s/it]

Finished trial 33: val loss: 0.8462 - with hyperparameters: {'lr': 0.002703384723146364, 'weight_decay': 0.009664863966167284, 'outcome_dropout': 0.3969471707680537, 'shared_dropout': 0.08955426681472192, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 32 loss: 0.8464

Best trial: 32. Best value: 0.846415:  68%|██████▊   | 34/50 [43:08<19:25, 72.83s/it]

Finished trial 34: val loss: 0.8477 - with hyperparameters: {'lr': 0.0023466281055962448, 'weight_decay': 0.008823140898160494, 'outcome_dropout': 0.3894592778283563, 'shared_dropout': 0.0871028952795896, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  70%|███████   | 35/50 [44:19<18:04, 72.27s/it]

Finished trial 35: val loss: 0.8282 - with hyperparameters: {'lr': 0.003818760362720721, 'weight_decay': 0.0026107094196360747, 'outcome_dropout': 0.4304026877336124, 'shared_dropout': 0.0845043528289784, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  72%|███████▏  | 36/50 [45:30<16:49, 72.14s/it]

Finished trial 36: val loss: 0.7860 - with hyperparameters: {'lr': 0.002327830856268346, 'weight_decay': 1.923002774573273e-05, 'outcome_dropout': 0.40117542013641116, 'shared_dropout': 0.0008435317975268447, 'shared_hidden': 128, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  74%|███████▍  | 37/50 [46:41<15:31, 71.66s/it]

Finished trial 37: val loss: 0.7860 - with hyperparameters: {'lr': 0.0005528899990709164, 'weight_decay': 0.006363983552893717, 'outcome_dropout': 0.24439345201778329, 'shared_dropout': 0.082260419502363, 'shared_hidden': 256, 'outcome_hidden': 256} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  76%|███████▌  | 38/50 [47:51<14:14, 71.19s/it]

Finished trial 38: val loss: 0.7684 - with hyperparameters: {'lr': 0.002573872583951668, 'weight_decay': 0.00046200202321288917, 'outcome_dropout': 0.35849527471884757, 'shared_dropout': 0.03986695792771383, 'shared_hidden': 512, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  78%|███████▊  | 39/50 [49:02<13:01, 71.05s/it]

Finished trial 39: val loss: 0.7985 - with hyperparameters: {'lr': 0.004070184326121258, 'weight_decay': 0.0015226200127220213, 'outcome_dropout': 0.3091682131987368, 'shared_dropout': 0.015189369534083369, 'shared_hidden': 256, 'outcome_hidden': 256} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  80%|████████  | 40/50 [50:12<11:47, 70.71s/it]

Finished trial 40: val loss: 0.7154 - with hyperparameters: {'lr': 0.001335677419323542, 'weight_decay': 3.562311916067329e-06, 'outcome_dropout': 0.12440998076210191, 'shared_dropout': 0.1626322501984715, 'shared_hidden': 128, 'outcome_hidden': 128} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  82%|████████▏ | 41/50 [51:21<10:33, 70.36s/it]

Finished trial 41: val loss: 0.8382 - with hyperparameters: {'lr': 0.0024363063055029715, 'weight_decay': 0.009665572663651029, 'outcome_dropout': 0.396997690924435, 'shared_dropout': 0.0713106879154188, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  84%|████████▍ | 42/50 [52:31<09:21, 70.15s/it]

Finished trial 42: val loss: 0.8277 - with hyperparameters: {'lr': 0.0016450051721593063, 'weight_decay': 0.0066822928724664015, 'outcome_dropout': 0.42978592841080765, 'shared_dropout': 0.10648152369452217, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  86%|████████▌ | 43/50 [53:41<08:10, 70.00s/it]

Finished trial 43: val loss: 0.8290 - with hyperparameters: {'lr': 0.002966882487133083, 'weight_decay': 0.009411941414540468, 'outcome_dropout': 0.3702091204086629, 'shared_dropout': 0.03870296491888091, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  88%|████████▊ | 44/50 [54:50<06:59, 69.91s/it]

Finished trial 44: val loss: 0.8053 - with hyperparameters: {'lr': 0.001059653372503556, 'weight_decay': 0.003604309537283567, 'outcome_dropout': 0.4049360965070097, 'shared_dropout': 0.3615692107157102, 'shared_hidden': 256, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  90%|█████████ | 45/50 [56:00<05:49, 69.83s/it]

Finished trial 45: val loss: 0.7490 - with hyperparameters: {'lr': 0.00039852148036619673, 'weight_decay': 0.0009679741243601743, 'outcome_dropout': 0.27004448828338573, 'shared_dropout': 0.12793253358549053, 'shared_hidden': 512, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  92%|█████████▏| 46/50 [57:11<04:40, 70.12s/it]

Finished trial 46: val loss: 0.6423 - with hyperparameters: {'lr': 5.1499152186188133e-05, 'weight_decay': 0.002333852887155655, 'outcome_dropout': 0.33898985262164266, 'shared_dropout': 0.09130433994852201, 'shared_hidden': 256, 'outcome_hidden': 256} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  94%|█████████▍| 47/50 [1:00:29<05:25, 108.43s/it]

Finished trial 47: val loss: 0.8289 - with hyperparameters: {'lr': 0.0014513900984366845, 'weight_decay': 0.00396061753426713, 'outcome_dropout': 0.3914592837310862, 'shared_dropout': 0.15480818699681456, 'shared_hidden': 512, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  96%|█████████▌| 48/50 [1:01:40<03:14, 97.46s/it]

Finished trial 48: val loss: 0.8303 - with hyperparameters: {'lr': 0.0039621853619127975, 'weight_decay': 0.006795005588244638, 'outcome_dropout': 0.4366735206563256, 'shared_dropout': 0.06684578006272696, 'shared_hidden': 256, 'outcome_hidden': 128} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736:  98%|█████████▊| 49/50 [1:02:52<01:29, 89.73s/it]

Finished trial 49: val loss: 0.7526 - with hyperparameters: {'lr': 0.0021111473966806474, 'weight_decay': 0.0001505514189704889, 'outcome_dropout': 0.3707931034233204, 'shared_dropout': 0.09916001631081445, 'shared_hidden': 128, 'outcome_hidden': 64} | best trial: 34 loss: 0.8477

Best trial: 34. Best value: 0.847736: 100%|██████████| 50/50 [1:04:03<00:00, 76.87s/it]

In [40]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 34
Best mean_Val_AUQC: 0.847736
Best params: {'lr': 0.0023466281055962448, 'weight_decay': 0.008823140898160494, 'outcome_dropout': 0.3894592778283563, 'shared_dropout': 0.0871028952795896, 'shared_hidden': 256, 'outcome_hidden': 64}

Best config table:

,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_Val_auqc,std_Val_auqc
0,0.002347,0.008823,256.0,64.0,0.087103,0.389459,0.847736,0.008134

Top 10 trials:

,trial,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,mean_val_auqc,std_Val_auqc
0,10,0.0001,0.0100,128,128,0.399,0.476,0.373470,0.147158
1,46,0.0001,0.0023,256,256,0.091,0.339,0.642288,0.051849
2,40,0.0013,0.0000,128,128,0.163,0.124,0.715431,0.045464
3,19,0.0001,0.0030,256,128,0.023,0.310,0.724902,0.032864
4,29,0.0016,0.0002,512,64,0.189,0.453,0.731309,0.026666
5,4,0.0004,0.0000,128,256,0.170,0.271,0.739707,0.035660
6,0,0.0005,0.0000,512,256,0.177,0.263,0.742028,0.023437
7,45,0.0004,0.0010,512,64,0.128,0.270,0.748977,0.022385
8,14,0.0022,0.0003,512,64,0.137,0.424,0.749836,0.024850
9,8,0.0034,0.0001,512,256,0.281,0.321,0.751908,0.022459

Per-seed test results:

     Seed      AUUC      AUQC      Lift      KRCC   ATE_Err
0  412312  0.606361  0.604859  1.195012  0.000862  0.151801
1      42  0.575012  0.572734  0.595819  0.038140  0.190205
2    1874  0.534799  0.532669  0.136236  0.035423  0.189581
3  902745  0.747138  0.746663  1.154948  0.164809  0.105935
4       1  0.617501  0.614011  0.931758  0.053076  0.035142

Test metrics mean ± std:

          AUUC      AUQC      Lift      KRCC   ATE_Err
mean  0.616162  0.614187  0.802755  0.058462  0.134533
std   0.079947  0.080623  0.442046  0.062450  0.065430

In [41]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_shared_hidden = int(best_cfg['shared_hidden'])
best_outcome_hidden = int(best_cfg['outcome_hidden'])
best_shared_dropout = float(best_cfg['shared_dropout'])
best_outcome_dropout = float(best_cfg['outcome_dropout'])

print("Evaluating on test with best validation config:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"  shared_hidden={best_shared_hidden}, outcome_hidden={best_outcome_hidden}")
print(f"  shared_dropout={best_shared_dropout:.3f}, outcome_dropout={best_outcome_dropout:.3f}")
print(f"Number of seeds: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=best_shared_hidden,
        outcome_hidden=best_outcome_hidden,
        outcome_dropout=best_outcome_dropout,
        shared_dropout=best_shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
    )

    tarnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'PER-SEED DETAILS (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'TEST SUMMARY (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Evaluating on test with best validation config:
  lr=2.3e-03, weight_decay=8.8e-03
  shared_hidden=256, outcome_hidden=64
  shared_dropout=0.087, outcome_dropout=0.389
Number of seeds: 5
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 267.1193 | Total Loss: 267.1193 | Val Loss: 497.5274 | Val Qini: 0.7114 | EMA Qini: 0.7114 | Best EMA: 0.7114 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 370.7234 | Total Loss: 370.7234 | Val Loss: 495.6738 | Val Qini: 0.7842 | EMA Qini: 0.7296 | Best EMA: 0.7296 ⭐ NEW BEST EMA
Epoch 3/150 | Base Loss: 355.9018 | Total Loss: 355.9018 | Val Loss: 495.6649 | Val Qini: 0.8588 | EMA Qini: 0.7619 | Best EMA: 0.7619 ⭐ NEW BEST EMA
Epoch 4/150 | Base Loss: 435.6848 | Total Loss: 435.6848 | Val Loss: 495.9754 | Val Qini: 0.8415 | EMA Qini: 0.7818 | Best EMA: 0.7818 ⭐ NEW BEST EMA
Epoch 5/150 | Base Loss: 755.4652 | Total Loss: 755.4652 | Val Loss: 495.4227 | Val Qini: 0.8654 | EMA Qini: 0.8027 | Best EMA: 0.8027 ⭐ NEW BEST EMA
Epoch 6/150 | Base Loss: 447.3485 | Total Loss: 447.3485 | Val Loss: 495.0997 | Val Qini: 0.8617 | EMA Qini: 0.8174 | Best EMA: 0.8174 ⭐ NEW BEST EMA
Epoch 7/150 | Base Loss: 383.2293 | Total Loss: 383.2293 | Val Loss: 495.2146 | Val Qini: 0.8772 | EMA Qini: 0.8324 | Best EMA: 0.8324 ⭐ NEW BEST EMA
Epoch 8/150 | Base Loss: 593.0986 | Total Loss: 593.0986 | Val Loss: 495.5711 | Val Qini: 0.8581 | EMA Qini: 0.8388 | Best EMA: 0.8388 ⭐ NEW BEST EMA
Epoch 9/150 | Base Loss: 430.2507 | Total Loss: 430.2507 | Val Loss: 495.2194 | Val Qini: 0.8543 | EMA Qini: 0.8427 | Best EMA: 0.8427 ⭐ NEW BEST EMA
Epoch 10/150 | Base Loss: 500.9844 | Total Loss: 500.9844 | Val Loss: 495.1001 | Val Qini: 0.8611 | EMA Qini: 0.8473 | Best EMA: 0.8473 ⭐ NEW BEST EMA
Epoch 11/150 | Base Loss: 324.0915 | Total Loss: 324.0915 | Val Loss: 494.9178 | Val Qini: 0.8815 | EMA Qini: 0.8558 | Best EMA: 0.8558 ⭐ NEW BEST EMA
Epoch 12/150 | Base Loss: 390.3157 | Total Loss: 390.3157 | Val Loss: 495.2403 | Val Qini: 0.8697 | EMA Qini: 0.8593 | Best EMA: 0.8593 ⭐ NEW BEST EMA
Epoch 13/150 | Base Loss: 571.5881 | Total Loss: 571.5881 | Val Loss: 494.9087 | Val Qini: 0.8774 | EMA Qini: 0.8638 | Best EMA: 0.8638 ⭐ NEW BEST EMA
Epoch 14/150 | Base Loss: 516.7568 | Total Loss: 516.7568 | Val Loss: 494.7867 | Val Qini: 0.8750 | EMA Qini: 0.8666 | Best EMA: 0.8666 ⭐ NEW BEST EMA
Epoch 15/150 | Base Loss: 436.1209 | Total Loss: 436.1209 | Val Loss: 494.8172 | Val Qini: 0.8658 | EMA Qini: 0.8664 | Best EMA: 0.8666 (patience: 0/20)
Epoch 16/150 | Base Loss: 238.3964 | Total Loss: 238.3964 | Val Loss: 494.9202 | Val Qini: 0.8602 | EMA Qini: 0.8649 | Best EMA: 0.8666 (patience: 0/20)
Epoch 17/150 | Base Loss: 488.2355 | Total Loss: 488.2355 | Val Loss: 495.0538 | Val Qini: 0.8601 | EMA Qini: 0.8637 | Best EMA: 0.8666 (patience: 0/20)
Epoch 18/150 | Base Loss: 587.3911 | Total Loss: 587.3911 | Val Loss: 494.8843 | Val Qini: 0.8669 | EMA Qini: 0.8645 | Best EMA: 0.8666 (patience: 0/20)
Epoch 19/150 | Base Loss: 370.6762 | Total Loss: 370.6762 | Val Loss: 494.6687 | Val Qini: 0.8739 | EMA Qini: 0.8668 | Best EMA: 0.8668 ⭐ NEW BEST EMA
Epoch 20/150 | Base Loss: 454.9255 | Total Loss: 454.9255 | Val Loss: 494.7918 | Val Qini: 0.8548 | EMA Qini: 0.8638 | Best EMA: 0.8668 (patience: 0/20)
Epoch 21/150 | Base Loss: 469.2957 | Total Loss: 469.2957 | Val Loss: 494.9841 | Val Qini: 0.8486 | EMA Qini: 0.8600 | Best EMA: 0.8668 (patience: 0/20)
Epoch 22/150 | Base Loss: 534.1953 | Total Loss: 534.1953 | Val Loss: 494.8293 | Val Qini: 0.8734 | EMA Qini: 0.8634 | Best EMA: 0.8668 (patience: 0/20)
Epoch 23/150 | Base Loss: 397.4098 | Total Loss: 397.4098 | Val Loss: 494.5806 | Val Qini: 0.8769 | EMA Qini: 0.8668 | Best EMA: 0.8668 (patience: 0/20)
Epoch 24/150 | Base Loss: 373.6872 | Total Loss: 373.6872 | Val Loss: 494.6145 | Val Qini: 0.8683 | EMA Qini: 0.8672 | Best EMA: 0.8672 ⭐ NEW BEST EMA
Epoch 25/150 | Base Loss: 578.4146 | Total Loss: 578.4146 | Val Loss: 494.7747 | Val Qini: 0.8467 | EMA Qini: 0.8620 | Best EMA: 0.8672 (patience: 0/20)
Epoch 26/150 | Base Loss: 397.2883 | Total Loss: 397.2883 | Val Loss: 494.8462 | Val Qini: 0.8329 | EMA Qini: 0.8548 | Best EMA: 0.8672 (patience: 0/20)
Epoch 27/150 | Base Loss: 403.3307 | Total Loss: 403.3307 | Val Loss: 494.8894 | Val Qini: 0.8299 | EMA Qini: 0.8486 | Best EMA: 0.8672 (patience: 0/20)
Epoch 28/150 | Base Loss: 304.9447 | Total Loss: 304.9447 | Val Loss: 494.8459 | Val Qini: 0.8320 | EMA Qini: 0.8444 | Best EMA: 0.8672 (patience: 0/20)
Epoch 29/150 | Base Loss: 414.2311 | Total Loss: 414.2311 | Val Loss: 494.7671 | Val Qini: 0.8435 | EMA Qini: 0.8442 | Best EMA: 0.8672 (patience: 0/20)
Epoch 30/150 | Base Loss: 229.8893 | Total Loss: 229.8893 | Val Loss: 494.6992 | Val Qini: 0.8457 | EMA Qini: 0.8446 | Best EMA: 0.8672 (patience: 0/20)
Epoch 31/150 | Base Loss: 348.9942 | Total Loss: 348.9942 | Val Loss: 494.7748 | Val Qini: 0.8436 | EMA Qini: 0.8443 | Best EMA: 0.8672 (patience: 1/20)
Epoch 32/150 | Base Loss: 535.8773 | Total Loss: 535.8773 | Val Loss: 494.9092 | Val Qini: 0.8281 | EMA Qini: 0.8403 | Best EMA: 0.8672 (patience: 2/20)
Epoch 33/150 | Base Loss: 375.2560 | Total Loss: 375.2560 | Val Loss: 494.8478 | Val Qini: 0.8343 | EMA Qini: 0.8388 | Best EMA: 0.8672 (patience: 3/20)
Epoch 34/150 | Base Loss: 348.7830 | Total Loss: 348.7830 | Val Loss: 494.8344 | Val Qini: 0.8334 | EMA Qini: 0.8374 | Best EMA: 0.8672 (patience: 4/20)
Epoch 35/150 | Base Loss: 580.9150 | Total Loss: 580.9150 | Val Loss: 494.8875 | Val Qini: 0.8241 | EMA Qini: 0.8341 | Best EMA: 0.8672 (patience: 5/20)
Epoch 36/150 | Base Loss: 401.6415 | Total Loss: 401.6415 | Val Loss: 494.8683 | Val Qini: 0.8186 | EMA Qini: 0.8302 | Best EMA: 0.8672 (patience: 6/20)
Epoch 37/150 | Base Loss: 479.3009 | Total Loss: 479.3009 | Val Loss: 494.8624 | Val Qini: 0.8139 | EMA Qini: 0.8261 | Best EMA: 0.8672 (patience: 7/20)
Epoch 38/150 | Base Loss: 564.4887 | Total Loss: 564.4887 | Val Loss: 494.7981 | Val Qini: 0.8213 | EMA Qini: 0.8249 | Best EMA: 0.8672 (patience: 8/20)
Epoch 39/150 | Base Loss: 545.7709 | Total Loss: 545.7709 | Val Loss: 494.7682 | Val Qini: 0.8279 | EMA Qini: 0.8257 | Best EMA: 0.8672 (patience: 9/20)
Epoch 40/150 | Base Loss: 518.1372 | Total Loss: 518.1372 | Val Loss: 494.7360 | Val Qini: 0.8333 | EMA Qini: 0.8276 | Best EMA: 0.8672 (patience: 10/20)
Epoch 41/150 | Base Loss: 457.3046 | Total Loss: 457.3046 | Val Loss: 494.6976 | Val Qini: 0.8377 | EMA Qini: 0.8301 | Best EMA: 0.8672 (patience: 11/20)
Epoch 42/150 | Base Loss: 399.5695 | Total Loss: 399.5695 | Val Loss: 494.7339 | Val Qini: 0.8346 | EMA Qini: 0.8312 | Best EMA: 0.8672 (patience: 12/20)
Epoch 43/150 | Base Loss: 405.7318 | Total Loss: 405.7318 | Val Loss: 494.6929 | Val Qini: 0.8402 | EMA Qini: 0.8335 | Best EMA: 0.8672 (patience: 13/20)
Epoch 44/150 | Base Loss: 408.9550 | Total Loss: 408.9550 | Val Loss: 494.6887 | Val Qini: 0.8393 | EMA Qini: 0.8349 | Best EMA: 0.8672 (patience: 14/20)
Epoch 45/150 | Base Loss: 309.0464 | Total Loss: 309.0464 | Val Loss: 494.6771 | Val Qini: 0.8395 | EMA Qini: 0.8361 | Best EMA: 0.8672 (patience: 15/20)
Epoch 46/150 | Base Loss: 303.1717 | Total Loss: 303.1717 | Val Loss: 494.7020 | Val Qini: 0.8329 | EMA Qini: 0.8353 | Best EMA: 0.8672 (patience: 16/20)
Epoch 47/150 | Base Loss: 420.0374 | Total Loss: 420.0374 | Val Loss: 494.6930 | Val Qini: 0.8331 | EMA Qini: 0.8347 | Best EMA: 0.8672 (patience: 17/20)
Epoch 48/150 | Base Loss: 334.1310 | Total Loss: 334.1310 | Val Loss: 494.6846 | Val Qini: 0.8339 | EMA Qini: 0.8345 | Best EMA: 0.8672 (patience: 18/20)
Epoch 49/150 | Base Loss: 519.2485 | Total Loss: 519.2485 | Val Loss: 494.6507 | Val Qini: 0.8319 | EMA Qini: 0.8339 | Best EMA: 0.8672 (patience: 19/20)
Epoch 50/150 | Base Loss: 387.0362 | Total Loss: 387.0362 | Val Loss: 494.6111 | Val Qini: 0.8338 | EMA Qini: 0.8338 | Best EMA: 0.8672 (patience: 20/20)

🛑 Early stopping triggered at epoch 50!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 24
   Best EMA Qini: 0.8672
   Raw Qini at best EMA epoch: 0.8683
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 508.2264 | Total Loss: 508.2264 | Val Loss: 496.7608 | Val Qini: 0.6905 | EMA Qini: 0.6905 | Best EMA: 0.6905 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 478.3134 | Total Loss: 478.3134 | Val Loss: 496.2219 | Val Qini: 0.7343 | EMA Qini: 0.7015 | Best EMA: 0.7015 ⭐ NEW BEST EMA
Epoch 3/150 | Base Loss: 712.9709 | Total Loss: 712.9709 | Val Loss: 495.7784 | Val Qini: 0.7938 | EMA Qini: 0.7245 | Best EMA: 0.7245 ⭐ NEW BEST EMA
Epoch 4/150 | Base Loss: 309.6632 | Total Loss: 309.6632 | Val Loss: 495.5374 | Val Qini: 0.8155 | EMA Qini: 0.7473 | Best EMA: 0.7473 ⭐ NEW BEST EMA
Epoch 5/150 | Base Loss: 317.6162 | Total Loss: 317.6162 | Val Loss: 495.1737 | Val Qini: 0.8182 | EMA Qini: 0.7650 | Best EMA: 0.7650 ⭐ NEW BEST EMA
Epoch 6/150 | Base Loss: 402.7166 | Total Loss: 402.7166 | Val Loss: 495.1039 | Val Qini: 0.8398 | EMA Qini: 0.7837 | Best EMA: 0.7837 ⭐ NEW BEST EMA
Epoch 7/150 | Base Loss: 645.5240 | Total Loss: 645.5240 | Val Loss: 495.2803 | Val Qini: 0.8546 | EMA Qini: 0.8014 | Best EMA: 0.8014 ⭐ NEW BEST EMA
Epoch 8/150 | Base Loss: 427.9107 | Total Loss: 427.9107 | Val Loss: 494.8077 | Val Qini: 0.8621 | EMA Qini: 0.8166 | Best EMA: 0.8166 ⭐ NEW BEST EMA
Epoch 9/150 | Base Loss: 458.0792 | Total Loss: 458.0792 | Val Loss: 494.6906 | Val Qini: 0.8824 | EMA Qini: 0.8330 | Best EMA: 0.8330 ⭐ NEW BEST EMA
Epoch 10/150 | Base Loss: 397.7833 | Total Loss: 397.7833 | Val Loss: 495.1774 | Val Qini: 0.8735 | EMA Qini: 0.8432 | Best EMA: 0.8432 ⭐ NEW BEST EMA
Epoch 11/150 | Base Loss: 380.2642 | Total Loss: 380.2642 | Val Loss: 494.9897 | Val Qini: 0.8692 | EMA Qini: 0.8497 | Best EMA: 0.8497 ⭐ NEW BEST EMA
Epoch 12/150 | Base Loss: 382.2090 | Total Loss: 382.2090 | Val Loss: 494.7467 | Val Qini: 0.8828 | EMA Qini: 0.8579 | Best EMA: 0.8579 ⭐ NEW BEST EMA
Epoch 13/150 | Base Loss: 395.2760 | Total Loss: 395.2760 | Val Loss: 494.8542 | Val Qini: 0.8866 | EMA Qini: 0.8651 | Best EMA: 0.8651 ⭐ NEW BEST EMA
Epoch 14/150 | Base Loss: 192.1676 | Total Loss: 192.1676 | Val Loss: 494.8681 | Val Qini: 0.8931 | EMA Qini: 0.8721 | Best EMA: 0.8721 ⭐ NEW BEST EMA
Epoch 15/150 | Base Loss: 616.1143 | Total Loss: 616.1143 | Val Loss: 495.0237 | Val Qini: 0.8978 | EMA Qini: 0.8785 | Best EMA: 0.8785 ⭐ NEW BEST EMA
Epoch 16/150 | Base Loss: 490.0412 | Total Loss: 490.0412 | Val Loss: 494.6441 | Val Qini: 0.8984 | EMA Qini: 0.8835 | Best EMA: 0.8835 ⭐ NEW BEST EMA
Epoch 17/150 | Base Loss: 472.6212 | Total Loss: 472.6212 | Val Loss: 494.4714 | Val Qini: 0.8966 | EMA Qini: 0.8868 | Best EMA: 0.8868 ⭐ NEW BEST EMA
Epoch 18/150 | Base Loss: 345.3112 | Total Loss: 345.3112 | Val Loss: 494.4574 | Val Qini: 0.8922 | EMA Qini: 0.8881 | Best EMA: 0.8881 ⭐ NEW BEST EMA
Epoch 19/150 | Base Loss: 413.0132 | Total Loss: 413.0132 | Val Loss: 494.7946 | Val Qini: 0.8750 | EMA Qini: 0.8848 | Best EMA: 0.8881 (patience: 0/20)
Epoch 20/150 | Base Loss: 422.3474 | Total Loss: 422.3474 | Val Loss: 494.8921 | Val Qini: 0.8455 | EMA Qini: 0.8750 | Best EMA: 0.8881 (patience: 0/20)
Epoch 21/150 | Base Loss: 465.6073 | Total Loss: 465.6073 | Val Loss: 494.8806 | Val Qini: 0.8220 | EMA Qini: 0.8618 | Best EMA: 0.8881 (patience: 0/20)
Epoch 22/150 | Base Loss: 624.0388 | Total Loss: 624.0388 | Val Loss: 494.9374 | Val Qini: 0.8163 | EMA Qini: 0.8504 | Best EMA: 0.8881 (patience: 0/20)
Epoch 23/150 | Base Loss: 319.1693 | Total Loss: 319.1693 | Val Loss: 494.8668 | Val Qini: 0.8232 | EMA Qini: 0.8436 | Best EMA: 0.8881 (patience: 0/20)
Epoch 24/150 | Base Loss: 393.5131 | Total Loss: 393.5131 | Val Loss: 494.7397 | Val Qini: 0.8469 | EMA Qini: 0.8444 | Best EMA: 0.8881 (patience: 0/20)
Epoch 25/150 | Base Loss: 583.7496 | Total Loss: 583.7496 | Val Loss: 494.7168 | Val Qini: 0.8631 | EMA Qini: 0.8491 | Best EMA: 0.8881 (patience: 0/20)
Epoch 26/150 | Base Loss: 648.6542 | Total Loss: 648.6542 | Val Loss: 494.7913 | Val Qini: 0.8630 | EMA Qini: 0.8526 | Best EMA: 0.8881 (patience: 0/20)
Epoch 27/150 | Base Loss: 489.8544 | Total Loss: 489.8544 | Val Loss: 494.7420 | Val Qini: 0.8623 | EMA Qini: 0.8550 | Best EMA: 0.8881 (patience: 0/20)
Epoch 28/150 | Base Loss: 409.8040 | Total Loss: 409.8040 | Val Loss: 494.7258 | Val Qini: 0.8553 | EMA Qini: 0.8551 | Best EMA: 0.8881 (patience: 0/20)
Epoch 29/150 | Base Loss: 402.6807 | Total Loss: 402.6807 | Val Loss: 494.7726 | Val Qini: 0.8322 | EMA Qini: 0.8494 | Best EMA: 0.8881 (patience: 0/20)
Epoch 30/150 | Base Loss: 537.7446 | Total Loss: 537.7446 | Val Loss: 494.9064 | Val Qini: 0.8072 | EMA Qini: 0.8388 | Best EMA: 0.8881 (patience: 0/20)
Epoch 31/150 | Base Loss: 353.1815 | Total Loss: 353.1815 | Val Loss: 494.9546 | Val Qini: 0.7994 | EMA Qini: 0.8290 | Best EMA: 0.8881 (patience: 1/20)
Epoch 32/150 | Base Loss: 645.2842 | Total Loss: 645.2842 | Val Loss: 495.0148 | Val Qini: 0.7951 | EMA Qini: 0.8205 | Best EMA: 0.8881 (patience: 2/20)
Epoch 33/150 | Base Loss: 488.1935 | Total Loss: 488.1935 | Val Loss: 494.8921 | Val Qini: 0.8010 | EMA Qini: 0.8156 | Best EMA: 0.8881 (patience: 3/20)
Epoch 34/150 | Base Loss: 462.1793 | Total Loss: 462.1793 | Val Loss: 494.7107 | Val Qini: 0.8275 | EMA Qini: 0.8186 | Best EMA: 0.8881 (patience: 4/20)
Epoch 35/150 | Base Loss: 180.7185 | Total Loss: 180.7185 | Val Loss: 494.7288 | Val Qini: 0.8248 | EMA Qini: 0.8201 | Best EMA: 0.8881 (patience: 5/20)
Epoch 36/150 | Base Loss: 415.4410 | Total Loss: 415.4410 | Val Loss: 494.8232 | Val Qini: 0.8124 | EMA Qini: 0.8182 | Best EMA: 0.8881 (patience: 6/20)
Epoch 37/150 | Base Loss: 382.6274 | Total Loss: 382.6274 | Val Loss: 494.9534 | Val Qini: 0.8057 | EMA Qini: 0.8151 | Best EMA: 0.8881 (patience: 7/20)
Epoch 38/150 | Base Loss: 603.0197 | Total Loss: 603.0197 | Val Loss: 495.0060 | Val Qini: 0.8070 | EMA Qini: 0.8131 | Best EMA: 0.8881 (patience: 8/20)
Epoch 39/150 | Base Loss: 546.1305 | Total Loss: 546.1305 | Val Loss: 494.9724 | Val Qini: 0.8075 | EMA Qini: 0.8117 | Best EMA: 0.8881 (patience: 9/20)
Epoch 40/150 | Base Loss: 494.3913 | Total Loss: 494.3913 | Val Loss: 494.8814 | Val Qini: 0.8164 | EMA Qini: 0.8129 | Best EMA: 0.8881 (patience: 10/20)
Epoch 41/150 | Base Loss: 376.6674 | Total Loss: 376.6674 | Val Loss: 494.8617 | Val Qini: 0.8119 | EMA Qini: 0.8126 | Best EMA: 0.8881 (patience: 11/20)
Epoch 42/150 | Base Loss: 421.8621 | Total Loss: 421.8621 | Val Loss: 494.8704 | Val Qini: 0.8127 | EMA Qini: 0.8126 | Best EMA: 0.8881 (patience: 12/20)
Epoch 43/150 | Base Loss: 440.4679 | Total Loss: 440.4679 | Val Loss: 494.8641 | Val Qini: 0.8165 | EMA Qini: 0.8136 | Best EMA: 0.8881 (patience: 13/20)
Epoch 44/150 | Base Loss: 388.6327 | Total Loss: 388.6327 | Val Loss: 494.8926 | Val Qini: 0.8153 | EMA Qini: 0.8140 | Best EMA: 0.8881 (patience: 14/20)
Epoch 45/150 | Base Loss: 509.1598 | Total Loss: 509.1598 | Val Loss: 495.0066 | Val Qini: 0.8156 | EMA Qini: 0.8144 | Best EMA: 0.8881 (patience: 15/20)
Epoch 46/150 | Base Loss: 295.6067 | Total Loss: 295.6067 | Val Loss: 494.9996 | Val Qini: 0.8159 | EMA Qini: 0.8148 | Best EMA: 0.8881 (patience: 16/20)
Epoch 47/150 | Base Loss: 385.8734 | Total Loss: 385.8734 | Val Loss: 495.0223 | Val Qini: 0.8160 | EMA Qini: 0.8151 | Best EMA: 0.8881 (patience: 17/20)
Epoch 48/150 | Base Loss: 655.8311 | Total Loss: 655.8311 | Val Loss: 495.0105 | Val Qini: 0.8157 | EMA Qini: 0.8152 | Best EMA: 0.8881 (patience: 18/20)
Epoch 49/150 | Base Loss: 394.1975 | Total Loss: 394.1975 | Val Loss: 495.0041 | Val Qini: 0.8135 | EMA Qini: 0.8148 | Best EMA: 0.8881 (patience: 19/20)
Epoch 50/150 | Base Loss: 529.0109 | Total Loss: 529.0109 | Val Loss: 495.0372 | Val Qini: 0.8059 | EMA Qini: 0.8126 | Best EMA: 0.8881 (patience: 20/20)

🛑 Early stopping triggered at epoch 50!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 18
   Best EMA Qini: 0.8881
   Raw Qini at best EMA epoch: 0.8922
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 42
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 526.2933 | Total Loss: 526.2933 | Val Loss: 496.5745 | Val Qini: 0.6899 | EMA Qini: 0.6899 | Best EMA: 0.6899 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 428.1804 | Total Loss: 428.1804 | Val Loss: 496.2880 | Val Qini: 0.7309 | EMA Qini: 0.7002 | Best EMA: 0.7002 ⭐ NEW BEST EMA
Epoch 3/150 | Base Loss: 349.6061 | Total Loss: 349.6061 | Val Loss: 495.9592 | Val Qini: 0.7621 | EMA Qini: 0.7156 | Best EMA: 0.7156 ⭐ NEW BEST EMA
Epoch 4/150 | Base Loss: 604.8495 | Total Loss: 604.8495 | Val Loss: 495.7070 | Val Qini: 0.7790 | EMA Qini: 0.7315 | Best EMA: 0.7315 ⭐ NEW BEST EMA
Epoch 5/150 | Base Loss: 630.3573 | Total Loss: 630.3573 | Val Loss: 495.0036 | Val Qini: 0.7966 | EMA Qini: 0.7478 | Best EMA: 0.7478 ⭐ NEW BEST EMA
Epoch 6/150 | Base Loss: 321.4353 | Total Loss: 321.4353 | Val Loss: 495.0161 | Val Qini: 0.8300 | EMA Qini: 0.7683 | Best EMA: 0.7683 ⭐ NEW BEST EMA
Epoch 7/150 | Base Loss: 552.7003 | Total Loss: 552.7003 | Val Loss: 495.0099 | Val Qini: 0.8482 | EMA Qini: 0.7883 | Best EMA: 0.7883 ⭐ NEW BEST EMA
Epoch 8/150 | Base Loss: 741.5297 | Total Loss: 741.5297 | Val Loss: 494.5618 | Val Qini: 0.8500 | EMA Qini: 0.8037 | Best EMA: 0.8037 ⭐ NEW BEST EMA
Epoch 9/150 | Base Loss: 348.5464 | Total Loss: 348.5464 | Val Loss: 494.6200 | Val Qini: 0.8597 | EMA Qini: 0.8177 | Best EMA: 0.8177 ⭐ NEW BEST EMA
Epoch 10/150 | Base Loss: 248.8123 | Total Loss: 248.8123 | Val Loss: 494.8904 | Val Qini: 0.8660 | EMA Qini: 0.8298 | Best EMA: 0.8298 ⭐ NEW BEST EMA
Epoch 11/150 | Base Loss: 547.6367 | Total Loss: 547.6367 | Val Loss: 495.2047 | Val Qini: 0.8779 | EMA Qini: 0.8418 | Best EMA: 0.8418 ⭐ NEW BEST EMA
Epoch 12/150 | Base Loss: 540.2568 | Total Loss: 540.2568 | Val Loss: 494.4822 | Val Qini: 0.8954 | EMA Qini: 0.8552 | Best EMA: 0.8552 ⭐ NEW BEST EMA
Epoch 13/150 | Base Loss: 309.3562 | Total Loss: 309.3562 | Val Loss: 494.4133 | Val Qini: 0.8902 | EMA Qini: 0.8640 | Best EMA: 0.8640 ⭐ NEW BEST EMA
Epoch 14/150 | Base Loss: 307.7401 | Total Loss: 307.7401 | Val Loss: 494.6647 | Val Qini: 0.8781 | EMA Qini: 0.8675 | Best EMA: 0.8675 ⭐ NEW BEST EMA
Epoch 15/150 | Base Loss: 239.3475 | Total Loss: 239.3475 | Val Loss: 494.9630 | Val Qini: 0.8433 | EMA Qini: 0.8614 | Best EMA: 0.8675 (patience: 0/20)
Epoch 16/150 | Base Loss: 638.8641 | Total Loss: 638.8641 | Val Loss: 495.2099 | Val Qini: 0.8168 | EMA Qini: 0.8503 | Best EMA: 0.8675 (patience: 0/20)
Epoch 17/150 | Base Loss: 576.7244 | Total Loss: 576.7244 | Val Loss: 494.9582 | Val Qini: 0.8139 | EMA Qini: 0.8412 | Best EMA: 0.8675 (patience: 0/20)
Epoch 18/150 | Base Loss: 511.1833 | Total Loss: 511.1833 | Val Loss: 494.7978 | Val Qini: 0.8292 | EMA Qini: 0.8382 | Best EMA: 0.8675 (patience: 0/20)
Epoch 19/150 | Base Loss: 481.2745 | Total Loss: 481.2745 | Val Loss: 495.0506 | Val Qini: 0.7993 | EMA Qini: 0.8285 | Best EMA: 0.8675 (patience: 0/20)
Epoch 20/150 | Base Loss: 323.8871 | Total Loss: 323.8871 | Val Loss: 495.0098 | Val Qini: 0.7943 | EMA Qini: 0.8199 | Best EMA: 0.8675 (patience: 0/20)
Epoch 21/150 | Base Loss: 241.6462 | Total Loss: 241.6462 | Val Loss: 495.1199 | Val Qini: 0.7854 | EMA Qini: 0.8113 | Best EMA: 0.8675 (patience: 0/20)
Epoch 22/150 | Base Loss: 383.2063 | Total Loss: 383.2063 | Val Loss: 495.0311 | Val Qini: 0.7857 | EMA Qini: 0.8049 | Best EMA: 0.8675 (patience: 0/20)