In [1]:
#import
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import torch
from torch.utils.data import TensorDataset, DataLoader
from tarnet import Tarnet
import sys
from pathlib import Path
project_root = Path("/home/ducvu0904/Documents/Lab/RERUM")
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))
sys.path.append("..")
from utils import seed_everything
from metrics import auuc, auqc, lift, krcc

In [2]:
%time train_df = pd.read_csv(r"../dataset/Hillstrom/Men/train_men.csv")
%time test_df =  pd.read_csv(r"../dataset/Hillstrom/Men/test_men.csv")
%time val_df = pd.read_csv(r"../dataset/Hillstrom/Men/val_men.csv")

CPU times: user 25.3 ms, sys: 9.16 ms, total: 34.5 ms
Wall time: 33.9 ms
CPU times: user 11.1 ms, sys: 6.01 ms, total: 17.1 ms
Wall time: 17.1 ms
CPU times: user 3.5 ms, sys: 2.98 ms, total: 6.48 ms
Wall time: 6.48 ms

In [3]:
in_features = ['recency', 'history_segment', 'history', 'mens', 'womens',
       'zip_code', 'newbie', 'channel_Multichannel', 'channel_Phone', 'channel_Web']
label_feature = ['spend']
treatment_feature = ['treatment']

In [4]:
X_train = train_df[in_features].values.astype(float) # type: ignore
y_train = train_df[label_feature].values.astype(float) # type: ignore
t_train = train_df[treatment_feature].values.astype(float) # type: ignore

X_test = test_df[in_features].values.astype(float) # type: ignore
y_test = test_df[label_feature].values.astype(float) # type: ignore
t_test = test_df[treatment_feature].values.astype(float) # type: ignore

X_val = val_df[in_features].values.astype(float) # type: ignore
y_val = val_df[label_feature].values.astype(float) # type: ignore
t_val = val_df[treatment_feature].values.astype(float) # type: ignore

In [5]:
print('X_train[:10]', X_train[:1].astype(float))

X_train[:10] [[-0.21435131  1.6331766   1.0667411   0.90252386 -1.1010233   1.07039981
   1.00043033  2.70003843 -0.88552759 -0.88616046]]

In [6]:
print('y_train[:10]', y_train[:1].astype(float))

y_train[:10] [[0.]]

In [7]:
# Transform to tensor
def to_tensor(arr):
    return torch.tensor(arr, dtype=torch.float32)

x_men_train_t = to_tensor(X_train)
x_men_val_t = to_tensor(X_val)
x_men_test_t = to_tensor(X_test)

y_men_train_t = to_tensor(y_train).reshape(-1, 1)
y_men_val_t = to_tensor(y_val).reshape(-1, 1)
y_men_test_t = to_tensor(y_test).reshape(-1, 1)

# t_train/t_val/t_test cũng tương tự
t_men_train_t = to_tensor(t_train.astype(float)).reshape(-1, 1)
t_men_val_t = to_tensor(t_val.astype(float)).reshape(-1, 1)
t_men_test_t = to_tensor(t_test.astype(float)).reshape(-1, 1)

# Data loader
train_dataset = TensorDataset(x_men_train_t, t_men_train_t, y_men_train_t)
val_dataset = TensorDataset(x_men_val_t, t_men_val_t, y_men_val_t)
test_dataset = TensorDataset(x_men_test_t, t_men_test_t, y_men_test_t)

batch_size = 6400
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True, num_workers=0, pin_memory = True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False, num_workers=0, pin_memory = True)

print("-------------------------------------------------------------")
print("✅ Completed transform to tensor ✅")
print(f"Shape of train: x={x_men_train_t.shape}; y={y_men_train_t.shape}; t={t_men_train_t.shape}")
print(f"Shape of val: x={x_men_val_t.shape}; y={y_men_val_t.shape}; t={t_men_val_t.shape}")
print(f"Shape of test: x={x_men_test_t.shape}; y={y_men_test_t.shape}; t={t_men_test_t.shape}")

-------------------------------------------------------------
✅ Completed transform to tensor ✅
Shape of train: x=torch.Size([25567, 10]); y=torch.Size([25567, 1]); t=torch.Size([25567, 1])
Shape of val: x=torch.Size([4262, 10]); y=torch.Size([4262, 1]); t=torch.Size([4262, 1])
Shape of test: x=torch.Size([12784, 10]); y=torch.Size([12784, 1]); t=torch.Size([12784, 1])

In [8]:
epochs = 150
early_stop_metric = "ema_qini"
ema = True
ema_alpha = 0.25
patience = 20
early_stop_start = 30
print (f" epochs = {epochs}")
print (f" early stop = {early_stop_metric}")
print (f" use ema = {ema}")
print (f" ema alpha = {ema_alpha}")
print (f" patience = {patience}")
print (f" early stop start = {early_stop_start}")

 epochs = 150
 early stop = ema_qini
 use ema = True
 ema alpha = 0.25
 patience = 20
 early stop start = 30

In [9]:
import io
import optuna
from contextlib import redirect_stdout, redirect_stderr

# Minimize Optuna console noise
optuna.logging.set_verbosity(optuna.logging.WARNING)

# 1. Optuna search config (validation only)
seeds = [412312, 42, 1874, 902745, 1]
n_trials = 50
tpe_sampler_seed = 412312
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def objective(trial):
    grid_lr = trial.suggest_float("lr", 1e-5,  1e-3, log=True)
    grid_wd = trial.suggest_float("weight_decay", 1e-5, 1e-2, log=True)
    grid_outcome_dropout = trial.suggest_float("outcome_dropout", 0.0, 0.5)
    grid_shared_dropout = trial.suggest_float("shared_dropout", 0.0, 0.5)
    grid_outcome_hidden = trial.suggest_int("outcome_hidden", 50, 400, step=50)
    grid_shared_hidden = trial.suggest_int("shared_hidden", 50, 400, step=50)
    grid_uplift_ranking = trial.suggest_float("uplift_ranking", 1e-4, 100.0)
    # grid_reponse_ranking = trial.suggest_float("response_ranking", 1e-4, 100.0)
    # grid_ranking_start = trial.suggest_int("ranking_start", 0, 20, step=1)

    val_auqc_list = []
    val_ate_err_list = []
    for SEED in seeds:
        seed_everything(SEED)

        tarnet = Tarnet(
            input_dim=x_men_train_t.shape[1],
            epochs=epochs,
            learning_rate=grid_lr,
            weight_decay=grid_wd,
            use_ema=ema,
            ema_alpha=ema_alpha,
            patience=patience,
            shared_hidden=grid_shared_hidden,
            outcome_hidden=grid_outcome_hidden,
            outcome_dropout=grid_outcome_dropout,
            shared_dropout=grid_shared_dropout,
            early_stop_metric=early_stop_metric,
            early_stop_start_epoch=early_stop_start,
            uplift_ranking=grid_uplift_ranking,
            response_ranking=0,
            ranking_start_epoch=15
        )

        with redirect_stdout(io.StringIO()), redirect_stderr(io.StringIO()):
            tarnet.fit(train_loader, val_loader)

        x_men_val_t_on_device = x_men_val_t.to(device)
        y0_pred, y1_pred = tarnet.predict(x_men_val_t_on_device)

        uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
        y_true = y_men_val_t.detach().cpu().numpy().flatten()
        t_true = t_men_val_t.detach().cpu().numpy().flatten()
        
        current_val_auqc = auqc(y_true, t_true, uplift_pred, bins=100, plot=False)
        ate_pred = uplift_pred.mean()
        ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()
        current_val_ate_err = abs(ate_pred - ate_true)

        val_auqc_list.append(current_val_auqc)
        val_ate_err_list.append(current_val_ate_err)

    # Calculate aggregated metrics across the 5 validation seeds
    mean_auqc = float(np.mean(val_auqc_list))
    std_auqc = float(np.std(val_auqc_list))
    mean_ate_err = float(np.mean(val_ate_err_list))

    # Apply penalty for instability and miscalibration
    penalty_std = std_auqc * 1.0
    penalty_ate = mean_ate_err * 0.05

    final_score = mean_auqc - penalty_std - penalty_ate

    trial.set_user_attr("mean_val_auqc", mean_auqc)
    trial.set_user_attr("std_Val_auqc", std_auqc)
    trial.set_user_attr("mean_val_ate_err", mean_ate_err)
    trial.set_user_attr("final_score", final_score)
    return final_score

def print_trial_callback(study, trial):
    value = float(trial.value) if trial.value is not None else float("nan")
    best_trial = study.best_trial
    best_value = float(best_trial.value) if best_trial.value is not None else float("nan")
    print(
        f"Finished trial {trial.number}: val loss: {value:.4f} - "
        f"with hyperparameters: {trial.params} | "
        f"best trial: {best_trial.number} loss: {best_value:.4f}",
        flush=True
    )

sampler = optuna.samplers.TPESampler(seed=tpe_sampler_seed)
study = optuna.create_study(direction="maximize", sampler=sampler)
study.optimize(objective, n_trials=n_trials, show_progress_bar=True, callbacks=[print_trial_callback])

trial_rows = []
for t in study.trials:
    if t.value is None:
        continue
    trial_rows.append({
        "trial": t.number,
        "lr": round(float(t.params["lr"]), 4),
        "weight_decay": round(float(t.params["weight_decay"]), 4),
        "shared_hidden": int(t.params["shared_hidden"]),
        "outcome_hidden": int(t.params["outcome_hidden"]),
        "shared_dropout": round(float(t.params["shared_dropout"]), 3),
        "outcome_dropout": round(float(t.params["outcome_dropout"]), 3),
        "uplift_ranking": round(float(t.params["uplift_ranking"]), 4),
        # "response_ranking": round(float(t.params["response_ranking"]), 4),
        # "ranking_start": int(t.params["ranking_start"]),
        "mean_val_auqc": float(t.value),
        "std_Val_auqc": float(t.user_attrs.get("std_Val_auqc", np.nan))
    })

df_grid = pd.DataFrame(trial_rows).sort_values("mean_val_auqc", ascending=True).reset_index(drop=True)
best_params = study.best_params
best_cfg = pd.Series({
    "lr": float(best_params["lr"]),
    "weight_decay": float(best_params["weight_decay"]),
    "shared_hidden": int(best_params["shared_hidden"]),
    "outcome_hidden": int(best_params["outcome_hidden"]),
    "shared_dropout": float(best_params["shared_dropout"]),
    "outcome_dropout": float(best_params["outcome_dropout"]),
    "uplift_ranking": float(best_params["uplift_ranking"]),
    # "response_ranking": float(best_params["response_ranking"]),
    # "ranking_start": int(best_params["ranking_start"]),
    "mean_Val_auqc": float(study.best_value),
    "std_Val_auqc": float(study.best_trial.user_attrs.get("std_Val_auqc", np.nan))
})

/home/ducvu0904/miniconda3/envs/ai/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
  0%|          | 0/50 [00:00<?, ?it/s]

Finished trial 0: val loss: 0.7293 - with hyperparameters: {'lr': 9.008296332262975e-05, 'weight_decay': 0.00013625464993948335, 'outcome_dropout': 0.2041371296334657, 'shared_dropout': 0.2216925330468017, 'outcome_hidden': 250, 'shared_hidden': 350, 'uplift_ranking': 93.47556399591086} | best trial: 0 loss: 0.7293

Best trial: 0. Best value: 0.729331:   2%|▏         | 1/50 [01:33<1:16:45, 93.99s/it]

Finished trial 1: val loss: 0.7769 - with hyperparameters: {'lr': 0.0009073451879643805, 'weight_decay': 0.000589790629511907, 'outcome_dropout': 0.369412397917029, 'shared_dropout': 0.409458181536563, 'outcome_hidden': 150, 'shared_hidden': 200, 'uplift_ranking': 17.170498906204575} | best trial: 1 loss: 0.7769

Best trial: 1. Best value: 0.776946:   4%|▍         | 2/50 [02:57<1:10:15, 87.82s/it]

Finished trial 2: val loss: 0.5869 - with hyperparameters: {'lr': 2.700612208950715e-05, 'weight_decay': 0.0010085829414078888, 'outcome_dropout': 0.3837245500682909, 'shared_dropout': 0.3036315111433474, 'outcome_hidden': 250, 'shared_hidden': 250, 'uplift_ranking': 52.26225655329725} | best trial: 1 loss: 0.7769

Best trial: 1. Best value: 0.776946:   6%|▌         | 3/50 [06:32<1:54:23, 146.03s/it]

Finished trial 3: val loss: 0.7037 - with hyperparameters: {'lr': 0.0001576063533946549, 'weight_decay': 0.0012483591579398854, 'outcome_dropout': 0.35222969406923277, 'shared_dropout': 0.38715551224062644, 'outcome_hidden': 150, 'shared_hidden': 50, 'uplift_ranking': 71.29510078857636} | best trial: 1 loss: 0.7769

Best trial: 1. Best value: 0.776946:   8%|▊         | 4/50 [08:23<1:41:10, 131.96s/it]

Finished trial 4: val loss: 0.7817 - with hyperparameters: {'lr': 0.0003677462000570632, 'weight_decay': 3.752427887933668e-05, 'outcome_dropout': 0.44667568845277744, 'shared_dropout': 0.2041546423424419, 'outcome_hidden': 100, 'shared_hidden': 150, 'uplift_ranking': 61.64182960054719} | best trial: 4 loss: 0.7817

Best trial: 4. Best value: 0.78173:  10%|█         | 5/50 [09:52<1:27:19, 116.44s/it]

Finished trial 5: val loss: 0.7929 - with hyperparameters: {'lr': 0.00041378696361693963, 'weight_decay': 0.0008331931887866918, 'outcome_dropout': 0.2525825604032998, 'shared_dropout': 0.3277017809120966, 'outcome_hidden': 100, 'shared_hidden': 350, 'uplift_ranking': 31.58243139969367} | best trial: 5 loss: 0.7929

Best trial: 5. Best value: 0.79291:  12%|█▏        | 6/50 [11:16<1:17:16, 105.38s/it]

Finished trial 6: val loss: 0.6626 - with hyperparameters: {'lr': 8.559271671026663e-05, 'weight_decay': 0.007225177618054781, 'outcome_dropout': 0.22728212392032476, 'shared_dropout': 0.09606758791930864, 'outcome_hidden': 200, 'shared_hidden': 200, 'uplift_ranking': 56.63936764486751} | best trial: 5 loss: 0.7929

Best trial: 5. Best value: 0.79291:  14%|█▍        | 7/50 [13:30<1:22:22, 114.94s/it]

Finished trial 7: val loss: 0.6958 - with hyperparameters: {'lr': 0.00010216766891538833, 'weight_decay': 5.184120539780966e-05, 'outcome_dropout': 0.2576010310834246, 'shared_dropout': 0.05350499145397214, 'outcome_hidden': 150, 'shared_hidden': 250, 'uplift_ranking': 34.77743299285039} | best trial: 5 loss: 0.7929

Best trial: 5. Best value: 0.79291:  16%|█▌        | 8/50 [15:18<1:18:48, 112.58s/it]

Finished trial 8: val loss: 0.7505 - with hyperparameters: {'lr': 0.0007221532962021238, 'weight_decay': 1.0760307811412354e-05, 'outcome_dropout': 0.08218945973543107, 'shared_dropout': 0.23187527197465674, 'outcome_hidden': 400, 'shared_hidden': 100, 'uplift_ranking': 21.379644323924328} | best trial: 5 loss: 0.7929

Best trial: 5. Best value: 0.79291:  18%|█▊        | 9/50 [16:44<1:11:13, 104.24s/it]

Finished trial 9: val loss: 0.8038 - with hyperparameters: {'lr': 0.000327845276156302, 'weight_decay': 0.00431482463702901, 'outcome_dropout': 0.28845782467061054, 'shared_dropout': 0.20542323309788552, 'outcome_hidden': 350, 'shared_hidden': 150, 'uplift_ranking': 76.42676350929852} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  20%|██        | 10/50 [18:09<1:05:32, 98.30s/it]

Finished trial 10: val loss: 0.3491 - with hyperparameters: {'lr': 1.9169852703080138e-05, 'weight_decay': 0.009985103986280672, 'outcome_dropout': 0.019731049516608812, 'shared_dropout': 0.4985212367923584, 'outcome_hidden': 400, 'shared_hidden': 50, 'uplift_ranking': 98.06579132832944} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  22%|██▏       | 11/50 [21:13<1:21:03, 124.70s/it]

Finished trial 11: val loss: 0.8030 - with hyperparameters: {'lr': 0.00029477477561496617, 'weight_decay': 0.002739014519189906, 'outcome_dropout': 0.16280513744957995, 'shared_dropout': 0.15005578312215503, 'outcome_hidden': 50, 'shared_hidden': 400, 'uplift_ranking': 75.55247091889483} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  24%|██▍       | 12/50 [22:37<1:11:02, 112.17s/it]

Finished trial 12: val loss: 0.7692 - with hyperparameters: {'lr': 0.0002146519241020802, 'weight_decay': 0.0031338978217613344, 'outcome_dropout': 0.13202681359829763, 'shared_dropout': 0.13852618827545693, 'outcome_hidden': 300, 'shared_hidden': 400, 'uplift_ranking': 78.70351203620707} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  26%|██▌       | 13/50 [24:02<1:04:13, 104.14s/it]

Finished trial 13: val loss: 0.8001 - with hyperparameters: {'lr': 0.0003388534041377205, 'weight_decay': 0.001943335099605324, 'outcome_dropout': 0.1402331003196874, 'shared_dropout': 0.1398008604823424, 'outcome_hidden': 50, 'shared_hidden': 300, 'uplift_ranking': 80.2103186769064} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  28%|██▊       | 14/50 [25:27<59:01, 98.36s/it]

Finished trial 14: val loss: 0.6703 - with hyperparameters: {'lr': 4.960507196763965e-05, 'weight_decay': 0.0040409689510666124, 'outcome_dropout': 0.29977329467178726, 'shared_dropout': 0.01103715217262402, 'outcome_hidden': 300, 'shared_hidden': 150, 'uplift_ranking': 69.67441880652171} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  30%|███       | 15/50 [27:42<1:03:46, 109.33s/it]

Finished trial 15: val loss: 0.7599 - with hyperparameters: {'lr': 0.00021238981545295237, 'weight_decay': 0.00028129585353580674, 'outcome_dropout': 0.1690164870803045, 'shared_dropout': 0.16189523423848776, 'outcome_hidden': 350, 'shared_hidden': 400, 'uplift_ranking': 85.99072118727989} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  32%|███▏      | 16/50 [29:10<58:21, 102.97s/it]

Finished trial 16: val loss: 0.7821 - with hyperparameters: {'lr': 0.000518819970454552, 'weight_decay': 0.002835024267012269, 'outcome_dropout': 0.46874458069085156, 'shared_dropout': 0.2815951429362197, 'outcome_hidden': 50, 'shared_hidden': 150, 'uplift_ranking': 41.259453210530225} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  34%|███▍      | 17/50 [30:36<53:44, 97.71s/it]

Finished trial 17: val loss: 0.7971 - with hyperparameters: {'lr': 0.0002207685101894137, 'weight_decay': 0.00041119114815621965, 'outcome_dropout': 0.3135666236225674, 'shared_dropout': 0.08690891099809073, 'outcome_hidden': 350, 'shared_hidden': 300, 'uplift_ranking': 68.60707250822782} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  36%|███▌      | 18/50 [32:03<50:26, 94.57s/it]

Finished trial 18: val loss: 0.6485 - with hyperparameters: {'lr': 5.488782466721234e-05, 'weight_decay': 0.006526216784054679, 'outcome_dropout': 0.06332778160039984, 'shared_dropout': 0.17550914391635544, 'outcome_hidden': 200, 'shared_hidden': 100, 'uplift_ranking': 87.32809913119107} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  38%|███▊      | 19/50 [34:53<1:00:37, 117.35s/it]

Finished trial 19: val loss: 0.7801 - with hyperparameters: {'lr': 0.0006038381526339034, 'weight_decay': 0.00021666317044723092, 'outcome_dropout': 0.1708571952399055, 'shared_dropout': 0.26749838741521775, 'outcome_hidden': 300, 'shared_hidden': 300, 'uplift_ranking': 46.43086320199558} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  40%|████      | 20/50 [36:15<53:22, 106.76s/it]

Finished trial 20: val loss: 0.7496 - with hyperparameters: {'lr': 0.00013923712341516658, 'weight_decay': 0.001880109851082739, 'outcome_dropout': 0.2925176752733457, 'shared_dropout': 0.006767143661600472, 'outcome_hidden': 350, 'shared_hidden': 100, 'uplift_ranking': 5.299713600405205} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  42%|████▏     | 21/50 [37:35<47:40, 98.64s/it]

Finished trial 21: val loss: 0.7963 - with hyperparameters: {'lr': 0.000290108443260045, 'weight_decay': 0.00212760970275111, 'outcome_dropout': 0.12192654311254543, 'shared_dropout': 0.12645658590068093, 'outcome_hidden': 50, 'shared_hidden': 350, 'uplift_ranking': 80.29065985277097} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  44%|████▍     | 22/50 [38:55<43:24, 93.02s/it]

Finished trial 22: val loss: 0.7901 - with hyperparameters: {'lr': 0.0002941563186719906, 'weight_decay': 0.004887105381956339, 'outcome_dropout': 0.1905531352829024, 'shared_dropout': 0.18612550160004404, 'outcome_hidden': 100, 'shared_hidden': 300, 'uplift_ranking': 77.5697048819784} | best trial: 9 loss: 0.8038

Best trial: 9. Best value: 0.803781:  46%|████▌     | 23/50 [40:15<40:05, 89.08s/it]

Finished trial 23: val loss: 0.8088 - with hyperparameters: {'lr': 0.00044496475894736524, 'weight_decay': 0.001883550184001307, 'outcome_dropout': 0.12489771619138408, 'shared_dropout': 0.09653276824766449, 'outcome_hidden': 50, 'shared_hidden': 400, 'uplift_ranking': 62.73975244525921} | best trial: 23 loss: 0.8088

Best trial: 23. Best value: 0.80879:  48%|████▊     | 24/50 [41:35<37:24, 86.33s/it]

Finished trial 24: val loss: 0.6584 - with hyperparameters: {'lr': 1.005946601404122e-05, 'weight_decay': 0.0012249358969325158, 'outcome_dropout': 0.0017592619249313657, 'shared_dropout': 0.0716434505378224, 'outcome_hidden': 100, 'shared_hidden': 400, 'uplift_ranking': 62.71927847298185} | best trial: 23 loss: 0.8088

Best trial: 23. Best value: 0.80879:  50%|█████     | 25/50 [44:32<47:20, 113.61s/it]

Finished trial 25: val loss: 0.8130 - with hyperparameters: {'lr': 0.0009649841353542495, 'weight_decay': 0.0045419876277658575, 'outcome_dropout': 0.06630953616489539, 'shared_dropout': 0.10583688819773765, 'outcome_hidden': 50, 'shared_hidden': 400, 'uplift_ranking': 62.736535833653775} | best trial: 25 loss: 0.8130

Best trial: 25. Best value: 0.813005:  52%|█████▏    | 26/50 [45:52<41:25, 103.57s/it]

Finished trial 26: val loss: 0.8271 - with hyperparameters: {'lr': 0.0009841888620597439, 'weight_decay': 0.009530827335771068, 'outcome_dropout': 0.07139742366256396, 'shared_dropout': 0.04859503003695438, 'outcome_hidden': 200, 'shared_hidden': 350, 'uplift_ranking': 60.83071817853154} | best trial: 26 loss: 0.8271

Best trial: 26. Best value: 0.827077:  54%|█████▍    | 27/50 [47:13<37:01, 96.59s/it]

Finished trial 27: val loss: 0.8251 - with hyperparameters: {'lr': 0.000977402246631429, 'weight_decay': 0.00978229604926812, 'outcome_dropout': 0.06397620316832009, 'shared_dropout': 0.05585427993584548, 'outcome_hidden': 150, 'shared_hidden': 350, 'uplift_ranking': 59.41158186954482} | best trial: 26 loss: 0.8271

Best trial: 26. Best value: 0.827077:  56%|█████▌    | 28/50 [48:33<33:35, 91.60s/it]

Finished trial 28: val loss: 0.8353 - with hyperparameters: {'lr': 0.0009563615251329733, 'weight_decay': 0.009563254765555858, 'outcome_dropout': 0.05489730527184775, 'shared_dropout': 0.04468195348228169, 'outcome_hidden': 200, 'shared_hidden': 350, 'uplift_ranking': 47.378475735500174} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  58%|█████▊    | 29/50 [49:53<30:51, 88.19s/it]

Finished trial 29: val loss: 0.8277 - with hyperparameters: {'lr': 0.0007255421761225742, 'weight_decay': 0.00892374165905217, 'outcome_dropout': 0.09720945427100795, 'shared_dropout': 0.0423149106366181, 'outcome_hidden': 200, 'shared_hidden': 350, 'uplift_ranking': 46.66611720101568} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  60%|██████    | 30/50 [51:09<28:09, 84.49s/it]

Finished trial 30: val loss: 0.7756 - with hyperparameters: {'lr': 0.0007475744489348946, 'weight_decay': 0.00010639491727213597, 'outcome_dropout': 0.03339590964842751, 'shared_dropout': 0.031142716303921916, 'outcome_hidden': 250, 'shared_hidden': 350, 'uplift_ranking': 44.98365209300651} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  62%|██████▏   | 31/50 [52:24<25:52, 81.69s/it]

Finished trial 31: val loss: 0.8335 - with hyperparameters: {'lr': 0.000993826399832596, 'weight_decay': 0.009677778277478559, 'outcome_dropout': 0.09297251204597717, 'shared_dropout': 0.038476554441269295, 'outcome_hidden': 200, 'shared_hidden': 350, 'uplift_ranking': 53.3033039591961} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  64%|██████▍   | 32/50 [53:39<23:55, 79.76s/it]

Finished trial 32: val loss: 0.8151 - with hyperparameters: {'lr': 0.0005641259851416982, 'weight_decay': 0.006408607307678035, 'outcome_dropout': 0.08795098099704174, 'shared_dropout': 0.037591553670422405, 'outcome_hidden': 200, 'shared_hidden': 350, 'uplift_ranking': 32.76397132546962} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  66%|██████▌   | 33/50 [54:54<22:10, 78.25s/it]

Finished trial 33: val loss: 0.7972 - with hyperparameters: {'lr': 0.0007450929391878858, 'weight_decay': 0.008421525184198145, 'outcome_dropout': 0.03775217433261671, 'shared_dropout': 0.007234251146664712, 'outcome_hidden': 250, 'shared_hidden': 250, 'uplift_ranking': 52.496420158907796} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  68%|██████▊   | 34/50 [56:08<20:33, 77.08s/it]

Finished trial 34: val loss: 0.8187 - with hyperparameters: {'lr': 0.0007452461590690845, 'weight_decay': 0.00581932323269146, 'outcome_dropout': 0.09814983010955104, 'shared_dropout': 0.0629793711915318, 'outcome_hidden': 200, 'shared_hidden': 300, 'uplift_ranking': 39.526512477712814} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  70%|███████   | 35/50 [57:23<19:06, 76.40s/it]

Finished trial 35: val loss: 0.7850 - with hyperparameters: {'lr': 0.0005674443007107802, 'weight_decay': 0.0006138218573560152, 'outcome_dropout': 0.10729969584153513, 'shared_dropout': 0.035069959744945776, 'outcome_hidden': 150, 'shared_hidden': 350, 'uplift_ranking': 24.861150691271583} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  72%|███████▏  | 36/50 [58:39<17:47, 76.25s/it]

Finished trial 36: val loss: 0.8238 - with hyperparameters: {'lr': 0.0009521890905647449, 'weight_decay': 0.009671008465823326, 'outcome_dropout': 0.040639171993591613, 'shared_dropout': 0.12031407913339008, 'outcome_hidden': 250, 'shared_hidden': 300, 'uplift_ranking': 50.50747494247791} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  74%|███████▍  | 37/50 [59:53<16:23, 75.62s/it]

Finished trial 37: val loss: 0.8053 - with hyperparameters: {'lr': 0.0004671263037771487, 'weight_decay': 0.003707067060811865, 'outcome_dropout': 0.0015552607743086616, 'shared_dropout': 0.07824765848762927, 'outcome_hidden': 200, 'shared_hidden': 350, 'uplift_ranking': 54.878157224331126} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  76%|███████▌  | 38/50 [1:01:07<15:01, 75.11s/it]

Finished trial 38: val loss: 0.8218 - with hyperparameters: {'lr': 0.0006999757379616692, 'weight_decay': 0.005333508193455393, 'outcome_dropout': 0.20356556317712138, 'shared_dropout': 0.0322410662575507, 'outcome_hidden': 150, 'shared_hidden': 250, 'uplift_ranking': 45.381220628101495} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  78%|███████▊  | 39/50 [1:02:20<13:38, 74.42s/it]

Finished trial 39: val loss: 0.7603 - with hyperparameters: {'lr': 0.0008210370974872214, 'weight_decay': 1.560106437012262e-05, 'outcome_dropout': 0.151294546812499, 'shared_dropout': 0.3663715011381172, 'outcome_hidden': 200, 'shared_hidden': 200, 'uplift_ranking': 38.46117474991567} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  80%|████████  | 40/50 [1:03:33<12:20, 74.03s/it]

Finished trial 40: val loss: 0.7914 - with hyperparameters: {'lr': 0.00040867438272391255, 'weight_decay': 0.0008781919434662753, 'outcome_dropout': 0.38721916849500726, 'shared_dropout': 0.442578400898205, 'outcome_hidden': 250, 'shared_hidden': 350, 'uplift_ranking': 28.510245246422834} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  82%|████████▏ | 41/50 [1:04:47<11:06, 74.06s/it]

Finished trial 41: val loss: 0.8151 - with hyperparameters: {'lr': 0.0009471937063207165, 'weight_decay': 0.009653589790420174, 'outcome_dropout': 0.0644284308209504, 'shared_dropout': 0.06663006993744461, 'outcome_hidden': 150, 'shared_hidden': 350, 'uplift_ranking': 56.39517207929578} | best trial: 28 loss: 0.8353

Best trial: 28. Best value: 0.83528:  84%|████████▍ | 42/50 [1:06:01<09:51, 73.92s/it]

Finished trial 42: val loss: 0.8386 - with hyperparameters: {'lr': 0.0009666303465207976, 'weight_decay': 0.006912792122967834, 'outcome_dropout': 0.0639204432871469, 'shared_dropout': 0.04926661020063554, 'outcome_hidden': 150, 'shared_hidden': 300, 'uplift_ranking': 58.771307150706704} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613:  86%|████████▌ | 43/50 [1:07:14<08:36, 73.73s/it]

Finished trial 43: val loss: 0.8169 - with hyperparameters: {'lr': 0.000603192996046671, 'weight_decay': 0.006359468025938312, 'outcome_dropout': 0.09813249321987202, 'shared_dropout': 0.0029112241727702534, 'outcome_hidden': 200, 'shared_hidden': 300, 'uplift_ranking': 48.68503444547843} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613:  88%|████████▊ | 44/50 [1:08:27<07:21, 73.64s/it]

Finished trial 44: val loss: 0.8271 - with hyperparameters: {'lr': 0.0006662111245378386, 'weight_decay': 0.007522599646207753, 'outcome_dropout': 0.049250152921575356, 'shared_dropout': 0.044786498949028496, 'outcome_hidden': 150, 'shared_hidden': 250, 'uplift_ranking': 66.99322054605638} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613:  90%|█████████ | 45/50 [1:09:41<06:07, 73.60s/it]

Finished trial 45: val loss: 0.8099 - with hyperparameters: {'lr': 0.0006093806095071899, 'weight_decay': 0.003057227916986163, 'outcome_dropout': 0.04762637517993235, 'shared_dropout': 0.11308904747075188, 'outcome_hidden': 150, 'shared_hidden': 200, 'uplift_ranking': 66.97539413107859} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613:  92%|█████████▏| 46/50 [1:10:57<04:57, 74.42s/it]

Finished trial 46: val loss: 0.8140 - with hyperparameters: {'lr': 0.0004725257562091438, 'weight_decay': 0.0071723436497557495, 'outcome_dropout': 0.017648786171968328, 'shared_dropout': 0.02438902970403322, 'outcome_hidden': 100, 'shared_hidden': 250, 'uplift_ranking': 52.08351463726267} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613:  94%|█████████▍| 47/50 [1:12:13<03:44, 74.81s/it]

Finished trial 47: val loss: 0.8071 - with hyperparameters: {'lr': 0.000780739432774144, 'weight_decay': 0.004077800391071372, 'outcome_dropout': 0.2367998293259557, 'shared_dropout': 0.08497922299530225, 'outcome_hidden': 150, 'shared_hidden': 250, 'uplift_ranking': 73.05419622986416} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613:  96%|█████████▌| 48/50 [1:13:30<02:30, 75.36s/it]

Finished trial 48: val loss: 0.8288 - with hyperparameters: {'lr': 0.0006741260078695676, 'weight_decay': 0.005644539631676795, 'outcome_dropout': 0.1183301961511507, 'shared_dropout': 0.22280842242068646, 'outcome_hidden': 100, 'shared_hidden': 300, 'uplift_ranking': 13.663489674156082} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613:  98%|█████████▊| 49/50 [1:14:46<01:15, 75.66s/it]

Finished trial 49: val loss: 0.7971 - with hyperparameters: {'lr': 0.00041378365694889413, 'weight_decay': 0.002417480658795926, 'outcome_dropout': 0.112202574782212, 'shared_dropout': 0.23894554774436494, 'outcome_hidden': 100, 'shared_hidden': 300, 'uplift_ranking': 14.844011073419296} | best trial: 42 loss: 0.8386

Best trial: 42. Best value: 0.838613: 100%|██████████| 50/50 [1:16:01<00:00, 91.23s/it]

In [10]:
from IPython.display import display

if 'study' not in globals():
    print('Run Cell 10 (Optuna tuning) first.')
else:
    print(f"Best trial: {study.best_trial.number}")
    print(f"Best mean_Val_AUQC: {study.best_value:.6f}")
    print(f"Best params: {study.best_params}")

if 'best_cfg' in globals():
    print('\nBest config table:')
    display(best_cfg.to_frame().T)
else:
    print('\nbest_cfg not found.')

if 'df_grid' in globals():
    print('\nTop 10 trials:')
    display(df_grid.head(10))
else:
    print('\ndf_grid not found.')

if 'df_results' in globals():
    print('\nPer-seed test results:')
    display(df_results)
    print('\nTest metrics mean ± std:')
    display(df_results.drop(columns='Seed').agg(['mean', 'std']))

Best trial: 42
Best mean_Val_AUQC: 0.838613
Best params: {'lr': 0.0009666303465207976, 'weight_decay': 0.006912792122967834, 'outcome_dropout': 0.0639204432871469, 'shared_dropout': 0.04926661020063554, 'outcome_hidden': 150, 'shared_hidden': 300, 'uplift_ranking': 58.771307150706704}

Best config table:

,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,uplift_ranking,mean_Val_auqc,std_Val_auqc
0,0.000967,0.006913,300.0,150.0,0.049267,0.06392,58.771307,0.838613,0.008826

Top 10 trials:

,trial,lr,weight_decay,shared_hidden,outcome_hidden,shared_dropout,outcome_dropout,uplift_ranking,mean_val_auqc,std_Val_auqc
0,10,0.0000,0.0100,50,400,0.499,0.020,98.0658,0.349108,0.195771
1,2,0.0000,0.0010,250,250,0.304,0.384,52.2623,0.586915,0.075047
2,18,0.0001,0.0065,100,200,0.176,0.063,87.3281,0.648539,0.036337
3,24,0.0000,0.0012,400,100,0.072,0.002,62.7193,0.658387,0.029072
4,6,0.0001,0.0072,200,200,0.096,0.227,56.6394,0.662597,0.058124
5,14,0.0000,0.0040,150,300,0.011,0.300,69.6744,0.670309,0.075499
6,7,0.0001,0.0001,250,150,0.054,0.258,34.7774,0.695824,0.032029
7,3,0.0002,0.0012,50,150,0.387,0.352,71.2951,0.703718,0.069528
8,0,0.0001,0.0001,350,250,0.222,0.204,93.4756,0.729331,0.025795
9,20,0.0001,0.0019,100,350,0.007,0.293,5.2997,0.749571,0.009581

In [15]:
import pandas as pd
import numpy as np
import torch

# 1. Evaluate selected config on test set (after tuning)
seeds = [412312, 42, 1874, 902745, 1]
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
all_runs = []

if 'best_cfg' not in globals():
    raise ValueError("best_cfg not found. Run grid-search cell first.")

best_lr = float(best_cfg['lr'])
best_wd = float(best_cfg['weight_decay'])
best_shared_hidden = int(best_cfg['shared_hidden'])
best_outcome_hidden = int(best_cfg['outcome_hidden'])
best_shared_dropout = float(best_cfg['shared_dropout'])
best_outcome_dropout = float(best_cfg['outcome_dropout'])
best_uplift_ranking = int(best_cfg['uplift_ranking'])
# best_response_ranking = int(best_cfg['response_ranking'])
# best_ranking_start = int(best_cfg['ranking_start'])

print("Evaluating on test with best validation config:")
print(f"  lr={best_lr:.1e}, weight_decay={best_wd:.1e}")
print(f"  shared_hidden={best_shared_hidden}, outcome_hidden={best_outcome_hidden}")
print(f"  shared_dropout={best_shared_dropout:.3f}, outcome_dropout={best_outcome_dropout:.3f}")
# print(f"  uplift_ranking={best_uplift_ranking}, response_ranking={best_response_ranking}")
print(f"  uplift_ranking={best_uplift_ranking}")
print(f"Number of seeds: {len(seeds)}")

# 2. Loop over seeds for robust test evaluation
for SEED in seeds:
    seed_everything(SEED)

    tarnet = Tarnet(
        input_dim=x_men_train_t.shape[1],
        epochs=epochs,
        learning_rate=best_lr,
        weight_decay=best_wd,
        use_ema=ema,
        ema_alpha=ema_alpha,
        patience=patience,
        shared_hidden=best_shared_hidden,
        outcome_hidden=best_outcome_hidden,
        outcome_dropout=best_outcome_dropout,
        shared_dropout=best_shared_dropout,
        early_stop_metric=early_stop_metric,
        early_stop_start_epoch=early_stop_start,
        uplift_ranking=best_uplift_ranking,
        response_ranking=0,
        ranking_start_epoch=0

    )

    tarnet.fit(train_loader, val_loader)

    # Test prediction
    x_men_test_t_on_device = x_men_test_t.to(device)
    y0_pred, y1_pred = tarnet.predict(x_men_test_t_on_device)

    uplift_pred = (y1_pred - y0_pred).detach().cpu().numpy().flatten()
    y_true = y_men_test_t.detach().cpu().numpy().flatten()
    t_true = t_men_test_t.detach().cpu().numpy().flatten()

    # ATE error
    ate_pred = uplift_pred.mean()
    ate_true = y_true[t_true == 1].mean() - y_true[t_true == 0].mean()

    all_runs.append({
        'Seed': SEED,
        'AUUC': auuc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'AUQC': auqc(y_true, t_true, uplift_pred, bins=100, plot=False),
        'Lift': lift(y_true, t_true, uplift_pred, h=0.3),
        'KRCC': krcc(y_true, t_true, uplift_pred, bins=100),
        'ATE_Err': abs(ate_pred - ate_true)
    })
    print(f"  Done Seed {SEED}")

# 3. Aggregate final test metrics
df_results = pd.DataFrame(all_runs)

print("\n" + "=" * 85)
print(f"{'PER-SEED DETAILS (TEST SET)':^85}")
print("=" * 85)
print(df_results.to_string(index=False, formatters={
    'AUUC': '{:,.4f}'.format,
    'AUQC': '{:,.4f}'.format,
    'Lift': '{:,.4f}'.format,
    'KRCC': '{:,.4f}'.format,
    'ATE_Err': '{:,.4f}'.format
}))

mean_res = df_results.drop(columns='Seed').mean()
std_res = df_results.drop(columns='Seed').std()

print("=" * 85)
print(f"{'TEST SUMMARY (MEAN ± STD)':^85}")
print("-" * 85)
for metric in ['AUUC', 'AUQC', 'Lift', 'KRCC', 'ATE_Err']:
    print(f"{metric:<10}: {mean_res[metric]:.4f} ± {std_res[metric]:.4f}")
print("=" * 85)

Evaluating on test with best validation config:
  lr=9.7e-04, weight_decay=6.9e-03
  shared_hidden=300, outcome_hidden=150
  shared_dropout=0.049, outcome_dropout=0.064
  uplift_ranking=58
Number of seeds: 5
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 626.1480 | Uplift Loss: 658.107666 | Total Loss: 1284.2556 | Val Loss: 498.9572 | Val Qini: 0.7342 | EMA Qini: 0.7342 | Best EMA: 0.7342 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 262.4183 | Uplift Loss: 418.606232 | Total Loss: 681.0245 | Val Loss: 498.7781 | Val Qini: 0.7260 | EMA Qini: 0.7322 | Best EMA: 0.7342 (patience: 0/20)
Epoch 3/150 | Base Loss: 289.3818 | Uplift Loss: 341.326202 | Total Loss: 630.7080 | Val Loss: 498.6027 | Val Qini: 0.6941 | EMA Qini: 0.7227 | Best EMA: 0.7342 (patience: 0/20)
Epoch 4/150 | Base Loss: 656.5126 | Uplift Loss: 352.821411 | Total Loss: 1009.3340 | Val Loss: 498.3657 | Val Qini: 0.6945 | EMA Qini: 0.7156 | Best EMA: 0.7342 (patience: 0/20)
Epoch 5/150 | Base Loss: 568.7241 | Uplift Loss: 643.449097 | Total Loss: 1212.1731 | Val Loss: 498.5923 | Val Qini: 0.6216 | EMA Qini: 0.6921 | Best EMA: 0.7342 (patience: 0/20)
Epoch 6/150 | Base Loss: 509.9341 | Uplift Loss: 534.928650 | Total Loss: 1044.8628 | Val Loss: 498.6542 | Val Qini: 0.5595 | EMA Qini: 0.6590 | Best EMA: 0.7342 (patience: 0/20)
Epoch 7/150 | Base Loss: 384.1805 | Uplift Loss: 411.331329 | Total Loss: 795.5118 | Val Loss: 498.6712 | Val Qini: 0.5204 | EMA Qini: 0.6243 | Best EMA: 0.7342 (patience: 0/20)
Epoch 8/150 | Base Loss: 273.1951 | Uplift Loss: 148.014282 | Total Loss: 421.2094 | Val Loss: 498.1095 | Val Qini: 0.6308 | EMA Qini: 0.6259 | Best EMA: 0.7342 (patience: 0/20)
Epoch 9/150 | Base Loss: 438.8357 | Uplift Loss: 395.088684 | Total Loss: 833.9244 | Val Loss: 499.3020 | Val Qini: 0.5709 | EMA Qini: 0.6122 | Best EMA: 0.7342 (patience: 0/20)
Epoch 10/150 | Base Loss: 339.2990 | Uplift Loss: 327.051636 | Total Loss: 666.3506 | Val Loss: 500.7541 | Val Qini: 0.4996 | EMA Qini: 0.5840 | Best EMA: 0.7342 (patience: 0/20)
Epoch 11/150 | Base Loss: 495.2375 | Uplift Loss: -38.148014 | Total Loss: 457.0895 | Val Loss: 499.1244 | Val Qini: 0.6322 | EMA Qini: 0.5961 | Best EMA: 0.7342 (patience: 0/20)
Epoch 12/150 | Base Loss: 416.4006 | Uplift Loss: 618.379456 | Total Loss: 1034.7800 | Val Loss: 500.5985 | Val Qini: 0.5967 | EMA Qini: 0.5962 | Best EMA: 0.7342 (patience: 0/20)
Epoch 13/150 | Base Loss: 513.6489 | Uplift Loss: 510.400055 | Total Loss: 1024.0490 | Val Loss: 502.2660 | Val Qini: 0.5972 | EMA Qini: 0.5965 | Best EMA: 0.7342 (patience: 0/20)
Epoch 14/150 | Base Loss: 381.2697 | Uplift Loss: 334.335876 | Total Loss: 715.6056 | Val Loss: 506.0246 | Val Qini: 0.5675 | EMA Qini: 0.5892 | Best EMA: 0.7342 (patience: 0/20)
Epoch 15/150 | Base Loss: 593.3975 | Uplift Loss: 625.980896 | Total Loss: 1219.3784 | Val Loss: 510.6514 | Val Qini: 0.6330 | EMA Qini: 0.6002 | Best EMA: 0.7342 (patience: 0/20)
Epoch 16/150 | Base Loss: 343.1480 | Uplift Loss: 433.927155 | Total Loss: 777.0751 | Val Loss: 517.2468 | Val Qini: 0.5975 | EMA Qini: 0.5995 | Best EMA: 0.7342 (patience: 0/20)
Epoch 17/150 | Base Loss: 672.3096 | Uplift Loss: -416.944794 | Total Loss: 255.3648 | Val Loss: 536.2417 | Val Qini: 0.5508 | EMA Qini: 0.5873 | Best EMA: 0.7342 (patience: 0/20)
Epoch 18/150 | Base Loss: 444.2416 | Uplift Loss: 10.431389 | Total Loss: 454.6730 | Val Loss: 546.4635 | Val Qini: 0.5673 | EMA Qini: 0.5823 | Best EMA: 0.7342 (patience: 0/20)
Epoch 19/150 | Base Loss: 400.4492 | Uplift Loss: -568.039856 | Total Loss: -167.5907 | Val Loss: 549.9799 | Val Qini: 0.6215 | EMA Qini: 0.5921 | Best EMA: 0.7342 (patience: 0/20)
Epoch 20/150 | Base Loss: 507.0822 | Uplift Loss: 3.921312 | Total Loss: 511.0035 | Val Loss: 613.9765 | Val Qini: 0.5570 | EMA Qini: 0.5833 | Best EMA: 0.7342 (patience: 0/20)
Epoch 21/150 | Base Loss: 458.2559 | Uplift Loss: 300.499969 | Total Loss: 758.7559 | Val Loss: 705.2244 | Val Qini: 0.4700 | EMA Qini: 0.5550 | Best EMA: 0.7342 (patience: 0/20)
Epoch 22/150 | Base Loss: 631.1609 | Uplift Loss: -464.941101 | Total Loss: 166.2198 | Val Loss: 678.3739 | Val Qini: 0.4673 | EMA Qini: 0.5331 | Best EMA: 0.7342 (patience: 0/20)
Epoch 23/150 | Base Loss: 740.4987 | Uplift Loss: 79.913391 | Total Loss: 820.4120 | Val Loss: 782.7177 | Val Qini: 0.5198 | EMA Qini: 0.5298 | Best EMA: 0.7342 (patience: 0/20)
Epoch 24/150 | Base Loss: 687.2675 | Uplift Loss: -576.589722 | Total Loss: 110.6777 | Val Loss: 946.3606 | Val Qini: 0.5306 | EMA Qini: 0.5300 | Best EMA: 0.7342 (patience: 0/20)
Epoch 25/150 | Base Loss: 989.8126 | Uplift Loss: -1025.720459 | Total Loss: -35.9078 | Val Loss: 988.0913 | Val Qini: 0.5423 | EMA Qini: 0.5331 | Best EMA: 0.7342 (patience: 0/20)
Epoch 26/150 | Base Loss: 701.6874 | Uplift Loss: -611.017822 | Total Loss: 90.6696 | Val Loss: 960.7810 | Val Qini: 0.5273 | EMA Qini: 0.5316 | Best EMA: 0.7342 (patience: 0/20)
Epoch 27/150 | Base Loss: 678.8566 | Uplift Loss: -1960.318359 | Total Loss: -1281.4617 | Val Loss: 818.0414 | Val Qini: 0.5927 | EMA Qini: 0.5469 | Best EMA: 0.7342 (patience: 0/20)
Epoch 28/150 | Base Loss: 834.6089 | Uplift Loss: -1290.824219 | Total Loss: -456.2153 | Val Loss: 1050.1321 | Val Qini: 0.5174 | EMA Qini: 0.5395 | Best EMA: 0.7342 (patience: 0/20)
Epoch 29/150 | Base Loss: 1190.2896 | Uplift Loss: -2982.477295 | Total Loss: -1792.1877 | Val Loss: 1347.6462 | Val Qini: 0.4279 | EMA Qini: 0.5116 | Best EMA: 0.7342 (patience: 0/20)
Epoch 30/150 | Base Loss: 1291.0952 | Uplift Loss: 11.324585 | Total Loss: 1302.4198 | Val Loss: 1244.1196 | Val Qini: 0.5065 | EMA Qini: 0.5103 | Best EMA: 0.7342 (patience: 0/20)
Epoch 31/150 | Base Loss: 848.1469 | Uplift Loss: -636.665100 | Total Loss: 211.4818 | Val Loss: 872.7932 | Val Qini: 0.6544 | EMA Qini: 0.5463 | Best EMA: 0.7342 (patience: 1/20)
Epoch 32/150 | Base Loss: 851.6923 | Uplift Loss: -945.206909 | Total Loss: -93.5146 | Val Loss: 1042.3416 | Val Qini: 0.5434 | EMA Qini: 0.5456 | Best EMA: 0.7342 (patience: 2/20)
Epoch 33/150 | Base Loss: 979.8915 | Uplift Loss: -5324.804688 | Total Loss: -4344.9131 | Val Loss: 1260.5693 | Val Qini: 0.4141 | EMA Qini: 0.5127 | Best EMA: 0.7342 (patience: 3/20)
Epoch 34/150 | Base Loss: 1290.4513 | Uplift Loss: -1582.869141 | Total Loss: -292.4178 | Val Loss: 1325.8805 | Val Qini: 0.4759 | EMA Qini: 0.5035 | Best EMA: 0.7342 (patience: 4/20)
Epoch 35/150 | Base Loss: 1120.8726 | Uplift Loss: -1876.692383 | Total Loss: -755.8198 | Val Loss: 1109.4724 | Val Qini: 0.6497 | EMA Qini: 0.5401 | Best EMA: 0.7342 (patience: 5/20)
Epoch 36/150 | Base Loss: 877.2029 | Uplift Loss: -2903.860107 | Total Loss: -2026.6572 | Val Loss: 1051.8848 | Val Qini: 0.6459 | EMA Qini: 0.5665 | Best EMA: 0.7342 (patience: 6/20)
Epoch 37/150 | Base Loss: 1133.8689 | Uplift Loss: -2501.764648 | Total Loss: -1367.8958 | Val Loss: 1352.4955 | Val Qini: 0.5364 | EMA Qini: 0.5590 | Best EMA: 0.7342 (patience: 7/20)
Epoch 38/150 | Base Loss: 1235.0187 | Uplift Loss: -1557.039795 | Total Loss: -322.0211 | Val Loss: 1467.7942 | Val Qini: 0.5439 | EMA Qini: 0.5552 | Best EMA: 0.7342 (patience: 8/20)
Epoch 39/150 | Base Loss: 1210.6302 | Uplift Loss: -3657.554932 | Total Loss: -2446.9248 | Val Loss: 1376.5542 | Val Qini: 0.6107 | EMA Qini: 0.5691 | Best EMA: 0.7342 (patience: 9/20)
Epoch 40/150 | Base Loss: 1170.8589 | Uplift Loss: -2427.281006 | Total Loss: -1256.4221 | Val Loss: 1459.3071 | Val Qini: 0.5269 | EMA Qini: 0.5586 | Best EMA: 0.7342 (patience: 10/20)
Epoch 41/150 | Base Loss: 1232.3252 | Uplift Loss: -1810.160034 | Total Loss: -577.8348 | Val Loss: 1357.9114 | Val Qini: 0.5043 | EMA Qini: 0.5450 | Best EMA: 0.7342 (patience: 11/20)
Epoch 42/150 | Base Loss: 1082.3989 | Uplift Loss: -4052.623779 | Total Loss: -2970.2249 | Val Loss: 1282.7029 | Val Qini: 0.5350 | EMA Qini: 0.5425 | Best EMA: 0.7342 (patience: 12/20)
Epoch 43/150 | Base Loss: 1525.2130 | Uplift Loss: -2944.027344 | Total Loss: -1418.8143 | Val Loss: 1720.1550 | Val Qini: 0.4335 | EMA Qini: 0.5152 | Best EMA: 0.7342 (patience: 13/20)
Epoch 44/150 | Base Loss: 1502.2958 | Uplift Loss: -1488.361572 | Total Loss: 13.9342 | Val Loss: 1597.6689 | Val Qini: 0.5953 | EMA Qini: 0.5353 | Best EMA: 0.7342 (patience: 14/20)
Epoch 45/150 | Base Loss: 1228.6649 | Uplift Loss: -3009.735352 | Total Loss: -1781.0704 | Val Loss: 1405.7456 | Val Qini: 0.5854 | EMA Qini: 0.5478 | Best EMA: 0.7342 (patience: 15/20)
Epoch 46/150 | Base Loss: 1340.2566 | Uplift Loss: -1727.387329 | Total Loss: -387.1307 | Val Loss: 1611.3525 | Val Qini: 0.5591 | EMA Qini: 0.5506 | Best EMA: 0.7342 (patience: 16/20)
Epoch 47/150 | Base Loss: 1675.9294 | Uplift Loss: 565.529175 | Total Loss: 2241.4585 | Val Loss: 1859.4824 | Val Qini: 0.5176 | EMA Qini: 0.5424 | Best EMA: 0.7342 (patience: 17/20)
Epoch 48/150 | Base Loss: 1235.6497 | Uplift Loss: -2201.259277 | Total Loss: -965.6096 | Val Loss: 1580.7758 | Val Qini: 0.5682 | EMA Qini: 0.5488 | Best EMA: 0.7342 (patience: 18/20)
Epoch 49/150 | Base Loss: 1419.2662 | Uplift Loss: -5617.937500 | Total Loss: -4198.6714 | Val Loss: 1456.7236 | Val Qini: 0.6664 | EMA Qini: 0.5782 | Best EMA: 0.7342 (patience: 19/20)
Epoch 50/150 | Base Loss: 1470.9060 | Uplift Loss: -502.770386 | Total Loss: 968.1356 | Val Loss: 1750.6980 | Val Qini: 0.5844 | EMA Qini: 0.5797 | Best EMA: 0.7342 (patience: 20/20)

🛑 Early stopping triggered at epoch 50!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 1
   Best EMA Qini: 0.7342
   Raw Qini at best EMA epoch: 0.7342
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 412312
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 578.5925 | Uplift Loss: 620.399109 | Total Loss: 1198.9917 | Val Loss: 498.5626 | Val Qini: 0.6831 | EMA Qini: 0.6831 | Best EMA: 0.6831 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 438.3231 | Uplift Loss: 442.549225 | Total Loss: 880.8723 | Val Loss: 498.3806 | Val Qini: 0.7354 | EMA Qini: 0.6962 | Best EMA: 0.6962 ⭐ NEW BEST EMA
Epoch 3/150 | Base Loss: 303.3149 | Uplift Loss: 415.149506 | Total Loss: 718.4644 | Val Loss: 498.3030 | Val Qini: 0.6869 | EMA Qini: 0.6939 | Best EMA: 0.6962 (patience: 0/20)
Epoch 4/150 | Base Loss: 610.4500 | Uplift Loss: -34.052132 | Total Loss: 576.3978 | Val Loss: 498.1625 | Val Qini: 0.6471 | EMA Qini: 0.6822 | Best EMA: 0.6962 (patience: 0/20)
Epoch 5/150 | Base Loss: 450.9614 | Uplift Loss: 394.851379 | Total Loss: 845.8128 | Val Loss: 498.1612 | Val Qini: 0.6075 | EMA Qini: 0.6635 | Best EMA: 0.6962 (patience: 0/20)
Epoch 6/150 | Base Loss: 358.7495 | Uplift Loss: 506.176971 | Total Loss: 864.9264 | Val Loss: 498.5225 | Val Qini: 0.5666 | EMA Qini: 0.6393 | Best EMA: 0.6962 (patience: 0/20)
Epoch 7/150 | Base Loss: 351.0320 | Uplift Loss: 165.156921 | Total Loss: 516.1888 | Val Loss: 498.8688 | Val Qini: 0.4892 | EMA Qini: 0.6017 | Best EMA: 0.6962 (patience: 0/20)
Epoch 8/150 | Base Loss: 465.3706 | Uplift Loss: 653.048401 | Total Loss: 1118.4191 | Val Loss: 497.5033 | Val Qini: 0.5429 | EMA Qini: 0.5870 | Best EMA: 0.6962 (patience: 0/20)
Epoch 9/150 | Base Loss: 285.0426 | Uplift Loss: 253.908997 | Total Loss: 538.9517 | Val Loss: 498.0939 | Val Qini: 0.5065 | EMA Qini: 0.5669 | Best EMA: 0.6962 (patience: 0/20)
Epoch 10/150 | Base Loss: 466.3863 | Uplift Loss: 339.119324 | Total Loss: 805.5056 | Val Loss: 500.4805 | Val Qini: 0.4747 | EMA Qini: 0.5438 | Best EMA: 0.6962 (patience: 0/20)
Epoch 11/150 | Base Loss: 483.2586 | Uplift Loss: 156.077667 | Total Loss: 639.3363 | Val Loss: 499.6916 | Val Qini: 0.5619 | EMA Qini: 0.5483 | Best EMA: 0.6962 (patience: 0/20)
Epoch 12/150 | Base Loss: 343.0440 | Uplift Loss: 235.228180 | Total Loss: 578.2722 | Val Loss: 500.0202 | Val Qini: 0.5309 | EMA Qini: 0.5440 | Best EMA: 0.6962 (patience: 0/20)
Epoch 13/150 | Base Loss: 435.8609 | Uplift Loss: 137.347107 | Total Loss: 573.2080 | Val Loss: 502.0002 | Val Qini: 0.5464 | EMA Qini: 0.5446 | Best EMA: 0.6962 (patience: 0/20)
Epoch 14/150 | Base Loss: 675.1290 | Uplift Loss: 122.292694 | Total Loss: 797.4216 | Val Loss: 505.6688 | Val Qini: 0.5345 | EMA Qini: 0.5421 | Best EMA: 0.6962 (patience: 0/20)
Epoch 15/150 | Base Loss: 515.8870 | Uplift Loss: 80.490753 | Total Loss: 596.3778 | Val Loss: 509.0150 | Val Qini: 0.5431 | EMA Qini: 0.5423 | Best EMA: 0.6962 (patience: 0/20)
Epoch 16/150 | Base Loss: 639.5022 | Uplift Loss: 130.807098 | Total Loss: 770.3093 | Val Loss: 518.2446 | Val Qini: 0.5288 | EMA Qini: 0.5390 | Best EMA: 0.6962 (patience: 0/20)
Epoch 17/150 | Base Loss: 353.7579 | Uplift Loss: -122.465164 | Total Loss: 231.2927 | Val Loss: 532.0453 | Val Qini: 0.5189 | EMA Qini: 0.5339 | Best EMA: 0.6962 (patience: 0/20)
Epoch 18/150 | Base Loss: 548.7433 | Uplift Loss: 488.282410 | Total Loss: 1037.0258 | Val Loss: 550.6282 | Val Qini: 0.5665 | EMA Qini: 0.5421 | Best EMA: 0.6962 (patience: 0/20)
Epoch 19/150 | Base Loss: 607.7320 | Uplift Loss: 83.750580 | Total Loss: 691.4825 | Val Loss: 590.4561 | Val Qini: 0.5168 | EMA Qini: 0.5357 | Best EMA: 0.6962 (patience: 0/20)
Epoch 20/150 | Base Loss: 642.4108 | Uplift Loss: 232.510101 | Total Loss: 874.9209 | Val Loss: 630.0908 | Val Qini: 0.5145 | EMA Qini: 0.5304 | Best EMA: 0.6962 (patience: 0/20)
Epoch 21/150 | Base Loss: 586.8354 | Uplift Loss: -271.971008 | Total Loss: 314.8644 | Val Loss: 644.7311 | Val Qini: 0.4987 | EMA Qini: 0.5225 | Best EMA: 0.6962 (patience: 0/20)
Epoch 22/150 | Base Loss: 688.6926 | Uplift Loss: -1260.145142 | Total Loss: -571.4525 | Val Loss: 683.6914 | Val Qini: 0.4637 | EMA Qini: 0.5078 | Best EMA: 0.6962 (patience: 0/20)
Epoch 23/150 | Base Loss: 596.1998 | Uplift Loss: -947.685486 | Total Loss: -351.4857 | Val Loss: 735.9476 | Val Qini: 0.4547 | EMA Qini: 0.4945 | Best EMA: 0.6962 (patience: 0/20)
Epoch 24/150 | Base Loss: 643.2748 | Uplift Loss: 164.812271 | Total Loss: 808.0871 | Val Loss: 844.3181 | Val Qini: 0.4278 | EMA Qini: 0.4779 | Best EMA: 0.6962 (patience: 0/20)
Epoch 25/150 | Base Loss: 664.0161 | Uplift Loss: -926.544800 | Total Loss: -262.5287 | Val Loss: 844.7306 | Val Qini: 0.4486 | EMA Qini: 0.4705 | Best EMA: 0.6962 (patience: 0/20)
Epoch 26/150 | Base Loss: 828.7257 | Uplift Loss: -2092.478027 | Total Loss: -1263.7523 | Val Loss: 793.6860 | Val Qini: 0.4815 | EMA Qini: 0.4733 | Best EMA: 0.6962 (patience: 0/20)
Epoch 27/150 | Base Loss: 674.4174 | Uplift Loss: -460.839417 | Total Loss: 213.5780 | Val Loss: 850.7820 | Val Qini: 0.4623 | EMA Qini: 0.4705 | Best EMA: 0.6962 (patience: 0/20)
Epoch 28/150 | Base Loss: 707.7307 | Uplift Loss: -2612.901855 | Total Loss: -1905.1711 | Val Loss: 863.5421 | Val Qini: 0.4526 | EMA Qini: 0.4660 | Best EMA: 0.6962 (patience: 0/20)
Epoch 29/150 | Base Loss: 850.5845 | Uplift Loss: -665.902710 | Total Loss: 184.6818 | Val Loss: 901.6627 | Val Qini: 0.4464 | EMA Qini: 0.4611 | Best EMA: 0.6962 (patience: 0/20)
Epoch 30/150 | Base Loss: 794.9249 | Uplift Loss: 709.857117 | Total Loss: 1504.7820 | Val Loss: 924.9399 | Val Qini: 0.4510 | EMA Qini: 0.4586 | Best EMA: 0.6962 (patience: 0/20)
Epoch 31/150 | Base Loss: 851.3581 | Uplift Loss: -1845.994507 | Total Loss: -994.6364 | Val Loss: 915.7728 | Val Qini: 0.4946 | EMA Qini: 0.4676 | Best EMA: 0.6962 (patience: 1/20)
Epoch 32/150 | Base Loss: 731.9650 | Uplift Loss: -388.265076 | Total Loss: 343.6999 | Val Loss: 986.7999 | Val Qini: 0.4822 | EMA Qini: 0.4713 | Best EMA: 0.6962 (patience: 2/20)
Epoch 33/150 | Base Loss: 820.4846 | Uplift Loss: -1829.282227 | Total Loss: -1008.7976 | Val Loss: 1050.7135 | Val Qini: 0.4677 | EMA Qini: 0.4704 | Best EMA: 0.6962 (patience: 3/20)
Epoch 34/150 | Base Loss: 837.3044 | Uplift Loss: -3358.260742 | Total Loss: -2520.9563 | Val Loss: 1101.2358 | Val Qini: 0.4443 | EMA Qini: 0.4638 | Best EMA: 0.6962 (patience: 4/20)
Epoch 35/150 | Base Loss: 688.3157 | Uplift Loss: -896.528503 | Total Loss: -208.2128 | Val Loss: 1109.3058 | Val Qini: 0.4661 | EMA Qini: 0.4644 | Best EMA: 0.6962 (patience: 5/20)
Epoch 36/150 | Base Loss: 1200.4880 | Uplift Loss: -2480.313721 | Total Loss: -1279.8257 | Val Loss: 1072.5563 | Val Qini: 0.4671 | EMA Qini: 0.4651 | Best EMA: 0.6962 (patience: 6/20)
Epoch 37/150 | Base Loss: 1038.0035 | Uplift Loss: -978.440002 | Total Loss: 59.5635 | Val Loss: 1127.5150 | Val Qini: 0.4604 | EMA Qini: 0.4639 | Best EMA: 0.6962 (patience: 7/20)
Epoch 38/150 | Base Loss: 951.4105 | Uplift Loss: -1409.447998 | Total Loss: -458.0375 | Val Loss: 1208.1069 | Val Qini: 0.4444 | EMA Qini: 0.4590 | Best EMA: 0.6962 (patience: 8/20)
Epoch 39/150 | Base Loss: 869.1885 | Uplift Loss: -1769.946655 | Total Loss: -900.7582 | Val Loss: 1211.5485 | Val Qini: 0.4537 | EMA Qini: 0.4577 | Best EMA: 0.6962 (patience: 9/20)
Epoch 40/150 | Base Loss: 1136.9626 | Uplift Loss: -3304.073242 | Total Loss: -2167.1106 | Val Loss: 1183.0894 | Val Qini: 0.4628 | EMA Qini: 0.4590 | Best EMA: 0.6962 (patience: 10/20)
Epoch 41/150 | Base Loss: 1027.6705 | Uplift Loss: -926.185486 | Total Loss: 101.4850 | Val Loss: 1218.5437 | Val Qini: 0.4621 | EMA Qini: 0.4598 | Best EMA: 0.6962 (patience: 11/20)
Epoch 42/150 | Base Loss: 1025.2949 | Uplift Loss: 386.353119 | Total Loss: 1411.6481 | Val Loss: 1289.7935 | Val Qini: 0.4561 | EMA Qini: 0.4588 | Best EMA: 0.6962 (patience: 12/20)
Epoch 43/150 | Base Loss: 1158.7310 | Uplift Loss: -3428.285889 | Total Loss: -2269.5549 | Val Loss: 1222.9957 | Val Qini: 0.4479 | EMA Qini: 0.4561 | Best EMA: 0.6962 (patience: 13/20)
Epoch 44/150 | Base Loss: 924.8712 | Uplift Loss: -1766.336304 | Total Loss: -841.4651 | Val Loss: 1224.1688 | Val Qini: 0.4459 | EMA Qini: 0.4536 | Best EMA: 0.6962 (patience: 14/20)
Epoch 45/150 | Base Loss: 1267.7764 | Uplift Loss: -2792.926758 | Total Loss: -1525.1504 | Val Loss: 1227.9868 | Val Qini: 0.4444 | EMA Qini: 0.4513 | Best EMA: 0.6962 (patience: 15/20)
Epoch 46/150 | Base Loss: 1181.0619 | Uplift Loss: -1849.724731 | Total Loss: -668.6628 | Val Loss: 1300.8379 | Val Qini: 0.4296 | EMA Qini: 0.4459 | Best EMA: 0.6962 (patience: 16/20)
Epoch 47/150 | Base Loss: 1142.0996 | Uplift Loss: -2126.035645 | Total Loss: -983.9360 | Val Loss: 1288.2878 | Val Qini: 0.4382 | EMA Qini: 0.4439 | Best EMA: 0.6962 (patience: 17/20)
Epoch 48/150 | Base Loss: 1115.7808 | Uplift Loss: -953.145142 | Total Loss: 162.6356 | Val Loss: 1263.6134 | Val Qini: 0.4473 | EMA Qini: 0.4448 | Best EMA: 0.6962 (patience: 18/20)
Epoch 49/150 | Base Loss: 954.7827 | Uplift Loss: -808.981201 | Total Loss: 145.8015 | Val Loss: 1242.9950 | Val Qini: 0.4608 | EMA Qini: 0.4488 | Best EMA: 0.6962 (patience: 19/20)
Epoch 50/150 | Base Loss: 1019.9339 | Uplift Loss: -778.654175 | Total Loss: 241.2797 | Val Loss: 1248.8867 | Val Qini: 0.4680 | EMA Qini: 0.4536 | Best EMA: 0.6962 (patience: 20/20)

🛑 Early stopping triggered at epoch 50!
   No improvement in EMA Qini for 20 epochs

✅ Training completed! Restored model to epoch 2
   Best EMA Qini: 0.6962
   Raw Qini at best EMA epoch: 0.7354
   Strategy: Selected epoch with highest smoothed (EMA) Qini
  Done Seed 42
🔃🔃🔃Begin training Tarnet🔃🔃🔃
📊 Early Stop Metric: EMA_QINI
📊 Early Stop Start Epoch: 31
📊 Strategy: Best EMA Qini (alpha=0.25)
   Restore to epoch with highest smoothed (EMA) Qini score
   Patience: 20 epochs
Epoch 1/150 | Base Loss: 409.4721 | Uplift Loss: 558.083679 | Total Loss: 967.5558 | Val Loss: 498.6795 | Val Qini: 0.7294 | EMA Qini: 0.7294 | Best EMA: 0.7294 ⭐ NEW BEST EMA
Epoch 2/150 | Base Loss: 356.3149 | Uplift Loss: 353.514984 | Total Loss: 709.8298 | Val Loss: 498.4807 | Val Qini: 0.7447 | EMA Qini: 0.7332 | Best EMA: 0.7332 ⭐ NEW BEST EMA